// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/backup.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message to hex-encode and store securely for account recovery.
type IdentityBackup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hex string of the identity.
	IdentityKey string `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	// The signed events for the canonical identity chain at the time of creating
	// this backup.
	IdentityChain []*EventBundle `protobuf:"bytes,2,rep,name=identity_chain,json=identityChain,proto3" json:"identity_chain,omitempty"`
	// The private key corresponding to the recovery public key in the latest
	// identity document.
	RecoveryKey   *PrivateKey `protobuf:"bytes,3,opt,name=recovery_key,json=recoveryKey,proto3" json:"recovery_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityBackup) Reset() {
	*x = IdentityBackup{}
	mi := &file_polycentric_v2_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityBackup) ProtoMessage() {}

func (x *IdentityBackup) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityBackup.ProtoReflect.Descriptor instead.
func (*IdentityBackup) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_backup_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityBackup) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

func (x *IdentityBackup) GetIdentityChain() []*EventBundle {
	if x != nil {
		return x.IdentityChain
	}
	return nil
}

func (x *IdentityBackup) GetRecoveryKey() *PrivateKey {
	if x != nil {
		return x.RecoveryKey
	}
	return nil
}

var File_polycentric_v2_backup_proto protoreflect.FileDescriptor

const file_polycentric_v2_backup_proto_rawDesc = "" +
	"\n" +
	"\x1bpolycentric/v2/backup.proto\x12\x0epolycentric.v2\x1a\x1cpolycentric/v2/keypair.proto\x1a\x1dpolycentric/v2/identity.proto\x1a\x1bpolycentric/v2/events.proto\"\xb6\x01\n" +
	"\x0eIdentityBackup\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\tR\videntityKey\x12B\n" +
	"\x0eidentity_chain\x18\x02 \x03(\v2\x1b.polycentric.v2.EventBundleR\ridentityChain\x12=\n" +
	"\frecovery_key\x18\x03 \x01(\v2\x1a.polycentric.v2.PrivateKeyR\vrecoveryKeyB\xcd\x01\n" +
	"\x12com.polycentric.v2B\vBackupProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_backup_proto_rawDescOnce sync.Once
	file_polycentric_v2_backup_proto_rawDescData []byte
)

func file_polycentric_v2_backup_proto_rawDescGZIP() []byte {
	file_polycentric_v2_backup_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_backup_proto_rawDesc), len(file_polycentric_v2_backup_proto_rawDesc)))
	})
	return file_polycentric_v2_backup_proto_rawDescData
}

var file_polycentric_v2_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_polycentric_v2_backup_proto_goTypes = []any{
	(*IdentityBackup)(nil), // 0: polycentric.v2.IdentityBackup
	(*EventBundle)(nil),    // 1: polycentric.v2.EventBundle
	(*PrivateKey)(nil),     // 2: polycentric.v2.PrivateKey
}
var file_polycentric_v2_backup_proto_depIdxs = []int32{
	1, // 0: polycentric.v2.IdentityBackup.identity_chain:type_name -> polycentric.v2.EventBundle
	2, // 1: polycentric.v2.IdentityBackup.recovery_key:type_name -> polycentric.v2.PrivateKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_polycentric_v2_backup_proto_init() }
func file_polycentric_v2_backup_proto_init() {
	if File_polycentric_v2_backup_proto != nil {
		return
	}
	file_polycentric_v2_keypair_proto_init()
	file_polycentric_v2_identity_proto_init()
	file_polycentric_v2_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_backup_proto_rawDesc), len(file_polycentric_v2_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycentric_v2_backup_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_backup_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_backup_proto_msgTypes,
	}.Build()
	File_polycentric_v2_backup_proto = out.File
	file_polycentric_v2_backup_proto_goTypes = nil
	file_polycentric_v2_backup_proto_depIdxs = nil
}
