// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/common.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentDigestType int32

const (
	ContentDigestType_CONTENT_DIGEST_TYPE_UNSPECIFIED ContentDigestType = 0
	ContentDigestType_CONTENT_DIGEST_TYPE_SHA256      ContentDigestType = 1
)

// Enum value maps for ContentDigestType.
var (
	ContentDigestType_name = map[int32]string{
		0: "CONTENT_DIGEST_TYPE_UNSPECIFIED",
		1: "CONTENT_DIGEST_TYPE_SHA256",
	}
	ContentDigestType_value = map[string]int32{
		"CONTENT_DIGEST_TYPE_UNSPECIFIED": 0,
		"CONTENT_DIGEST_TYPE_SHA256":      1,
	}
)

func (x ContentDigestType) Enum() *ContentDigestType {
	p := new(ContentDigestType)
	*p = x
	return p
}

func (x ContentDigestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentDigestType) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_common_proto_enumTypes[0].Descriptor()
}

func (ContentDigestType) Type() protoreflect.EnumType {
	return &file_polycentric_v2_common_proto_enumTypes[0]
}

func (x ContentDigestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentDigestType.Descriptor instead.
func (ContentDigestType) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_common_proto_rawDescGZIP(), []int{0}
}

// Returned by paginated feeds to aid in future queries.
type PageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque string that can be included in a request to the server to receive
	// the previous page of data.
	StartCursor string `protobuf:"bytes,1,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	// Opaque string that can be included in a request to the server to receive
	// the next page of data.
	EndCursor string `protobuf:"bytes,2,opt,name=end_cursor,json=endCursor,proto3" json:"end_cursor,omitempty"`
	// True if there is likely more data preceding `start_cursor`.
	HasPreviousPage bool `protobuf:"varint,3,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	// True if there is likely more data following `end_cursor`.
	HasNextPage   bool `protobuf:"varint,4,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_polycentric_v2_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_common_proto_rawDescGZIP(), []int{0}
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil {
		return x.EndCursor
	}
	return ""
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

// Sent by clients to servers for fetching paginated data.
type PageParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max events to return.
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Request data preceding this start cursor in the feed.
	BackwardToken *string `protobuf:"bytes,2,opt,name=backward_token,json=backwardToken,proto3,oneof" json:"backward_token,omitempty"`
	// Request data following this end cursor in the feed.
	ForwardToken  *string `protobuf:"bytes,3,opt,name=forward_token,json=forwardToken,proto3,oneof" json:"forward_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageParams) Reset() {
	*x = PageParams{}
	mi := &file_polycentric_v2_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageParams) ProtoMessage() {}

func (x *PageParams) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageParams.ProtoReflect.Descriptor instead.
func (*PageParams) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageParams) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *PageParams) GetBackwardToken() string {
	if x != nil && x.BackwardToken != nil {
		return *x.BackwardToken
	}
	return ""
}

func (x *PageParams) GetForwardToken() string {
	if x != nil && x.ForwardToken != nil {
		return *x.ForwardToken
	}
	return ""
}

type ContentDigest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ContentDigestType      `protobuf:"varint,1,opt,name=type,proto3,enum=polycentric.v2.ContentDigestType" json:"type,omitempty"`
	// We hash the serialized bytes
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentDigest) Reset() {
	*x = ContentDigest{}
	mi := &file_polycentric_v2_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentDigest) ProtoMessage() {}

func (x *ContentDigest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentDigest.ProtoReflect.Descriptor instead.
func (*ContentDigest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_common_proto_rawDescGZIP(), []int{2}
}

func (x *ContentDigest) GetType() ContentDigestType {
	if x != nil {
		return x.Type
	}
	return ContentDigestType_CONTENT_DIGEST_TYPE_UNSPECIFIED
}

func (x *ContentDigest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_polycentric_v2_common_proto protoreflect.FileDescriptor

const file_polycentric_v2_common_proto_rawDesc = "" +
	"\n" +
	"\x1bpolycentric/v2/common.proto\x12\x0epolycentric.v2\"\x9c\x01\n" +
	"\bPageInfo\x12!\n" +
	"\fstart_cursor\x18\x01 \x01(\tR\vstartCursor\x12\x1d\n" +
	"\n" +
	"end_cursor\x18\x02 \x01(\tR\tendCursor\x12*\n" +
	"\x11has_previous_page\x18\x03 \x01(\bR\x0fhasPreviousPage\x12\"\n" +
	"\rhas_next_page\x18\x04 \x01(\bR\vhasNextPage\"\xac\x01\n" +
	"\n" +
	"PageParams\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12*\n" +
	"\x0ebackward_token\x18\x02 \x01(\tH\x01R\rbackwardToken\x88\x01\x01\x12(\n" +
	"\rforward_token\x18\x03 \x01(\tH\x02R\fforwardToken\x88\x01\x01B\b\n" +
	"\x06_limitB\x11\n" +
	"\x0f_backward_tokenB\x10\n" +
	"\x0e_forward_token\"\\\n" +
	"\rContentDigest\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.polycentric.v2.ContentDigestTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value*X\n" +
	"\x11ContentDigestType\x12#\n" +
	"\x1fCONTENT_DIGEST_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONTENT_DIGEST_TYPE_SHA256\x10\x01B\xcd\x01\n" +
	"\x12com.polycentric.v2B\vCommonProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_common_proto_rawDescOnce sync.Once
	file_polycentric_v2_common_proto_rawDescData []byte
)

func file_polycentric_v2_common_proto_rawDescGZIP() []byte {
	file_polycentric_v2_common_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_common_proto_rawDesc), len(file_polycentric_v2_common_proto_rawDesc)))
	})
	return file_polycentric_v2_common_proto_rawDescData
}

var file_polycentric_v2_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polycentric_v2_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_polycentric_v2_common_proto_goTypes = []any{
	(ContentDigestType)(0), // 0: polycentric.v2.ContentDigestType
	(*PageInfo)(nil),       // 1: polycentric.v2.PageInfo
	(*PageParams)(nil),     // 2: polycentric.v2.PageParams
	(*ContentDigest)(nil),  // 3: polycentric.v2.ContentDigest
}
var file_polycentric_v2_common_proto_depIdxs = []int32{
	0, // 0: polycentric.v2.ContentDigest.type:type_name -> polycentric.v2.ContentDigestType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_polycentric_v2_common_proto_init() }
func file_polycentric_v2_common_proto_init() {
	if File_polycentric_v2_common_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_common_proto_rawDesc), len(file_polycentric_v2_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycentric_v2_common_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_common_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_common_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_common_proto_msgTypes,
	}.Build()
	File_polycentric_v2_common_proto = out.File
	file_polycentric_v2_common_proto_goTypes = nil
	file_polycentric_v2_common_proto_depIdxs = nil
}
