// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/content.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportCategory int32

const (
	ReportCategory_REPORT_CATEGORY_UNSPECIFIED       ReportCategory = 0
	ReportCategory_REPORT_CATEGORY_SPAM              ReportCategory = 1
	ReportCategory_REPORT_CATEGORY_CHILD_SAFETY      ReportCategory = 3
	ReportCategory_REPORT_CATEGORY_COPYRIGHT         ReportCategory = 6
	ReportCategory_REPORT_CATEGORY_SERVER_POLICY     ReportCategory = 7
	ReportCategory_REPORT_CATEGORY_VIOLENCE          ReportCategory = 8
	ReportCategory_REPORT_CATEGORY_SELF_HARM         ReportCategory = 9
	ReportCategory_REPORT_CATEGORY_SEXUALLY_EXPLICIT ReportCategory = 10
	ReportCategory_REPORT_CATEGORY_HATE              ReportCategory = 11
)

// Enum value maps for ReportCategory.
var (
	ReportCategory_name = map[int32]string{
		0:  "REPORT_CATEGORY_UNSPECIFIED",
		1:  "REPORT_CATEGORY_SPAM",
		3:  "REPORT_CATEGORY_CHILD_SAFETY",
		6:  "REPORT_CATEGORY_COPYRIGHT",
		7:  "REPORT_CATEGORY_SERVER_POLICY",
		8:  "REPORT_CATEGORY_VIOLENCE",
		9:  "REPORT_CATEGORY_SELF_HARM",
		10: "REPORT_CATEGORY_SEXUALLY_EXPLICIT",
		11: "REPORT_CATEGORY_HATE",
	}
	ReportCategory_value = map[string]int32{
		"REPORT_CATEGORY_UNSPECIFIED":       0,
		"REPORT_CATEGORY_SPAM":              1,
		"REPORT_CATEGORY_CHILD_SAFETY":      3,
		"REPORT_CATEGORY_COPYRIGHT":         6,
		"REPORT_CATEGORY_SERVER_POLICY":     7,
		"REPORT_CATEGORY_VIOLENCE":          8,
		"REPORT_CATEGORY_SELF_HARM":         9,
		"REPORT_CATEGORY_SEXUALLY_EXPLICIT": 10,
		"REPORT_CATEGORY_HATE":              11,
	}
)

func (x ReportCategory) Enum() *ReportCategory {
	p := new(ReportCategory)
	*p = x
	return p
}

func (x ReportCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_content_proto_enumTypes[0].Descriptor()
}

func (ReportCategory) Type() protoreflect.EnumType {
	return &file_polycentric_v2_content_proto_enumTypes[0]
}

func (x ReportCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportCategory.Descriptor instead.
func (ReportCategory) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{0}
}

// Content of the event
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ContentBody:
	//
	//	*Content_Post
	//	*Content_Delete
	//	*Content_Follow
	//	*Content_Block
	//	*Content_Reaction
	//	*Content_AttributedToReaction
	//	*Content_ProfileUpdate
	//	*Content_Identity
	//	*Content_Repost
	//	*Content_Report
	//	*Content_Labels
	//	*Content_VerificationClaim
	//	*Content_VerificationVerify
	//	*Content_VerificationTarget
	ContentBody   isContent_ContentBody `protobuf_oneof:"content_body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_polycentric_v2_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetContentBody() isContent_ContentBody {
	if x != nil {
		return x.ContentBody
	}
	return nil
}

func (x *Content) GetPost() *Post {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Post); ok {
			return x.Post
		}
	}
	return nil
}

func (x *Content) GetDelete() *Delete {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Content) GetFollow() *Follow {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Follow); ok {
			return x.Follow
		}
	}
	return nil
}

func (x *Content) GetBlock() *Block {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *Content) GetReaction() *Reaction {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Reaction); ok {
			return x.Reaction
		}
	}
	return nil
}

func (x *Content) GetAttributedToReaction() *AttributedToReaction {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_AttributedToReaction); ok {
			return x.AttributedToReaction
		}
	}
	return nil
}

func (x *Content) GetProfileUpdate() *ProfileUpdate {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_ProfileUpdate); ok {
			return x.ProfileUpdate
		}
	}
	return nil
}

func (x *Content) GetIdentity() *Identity {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Identity); ok {
			return x.Identity
		}
	}
	return nil
}

func (x *Content) GetRepost() *Repost {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Repost); ok {
			return x.Repost
		}
	}
	return nil
}

func (x *Content) GetReport() *Report {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *Content) GetLabels() *Labels {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_Labels); ok {
			return x.Labels
		}
	}
	return nil
}

func (x *Content) GetVerificationClaim() *VerificationClaim {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_VerificationClaim); ok {
			return x.VerificationClaim
		}
	}
	return nil
}

func (x *Content) GetVerificationVerify() *VerificationVerify {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_VerificationVerify); ok {
			return x.VerificationVerify
		}
	}
	return nil
}

func (x *Content) GetVerificationTarget() *VerificationTarget {
	if x != nil {
		if x, ok := x.ContentBody.(*Content_VerificationTarget); ok {
			return x.VerificationTarget
		}
	}
	return nil
}

type isContent_ContentBody interface {
	isContent_ContentBody()
}

type Content_Post struct {
	Post *Post `protobuf:"bytes,2,opt,name=post,proto3,oneof"`
}

type Content_Delete struct {
	Delete *Delete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type Content_Follow struct {
	Follow *Follow `protobuf:"bytes,4,opt,name=follow,proto3,oneof"`
}

type Content_Block struct {
	Block *Block `protobuf:"bytes,5,opt,name=block,proto3,oneof"`
}

type Content_Reaction struct {
	Reaction *Reaction `protobuf:"bytes,6,opt,name=reaction,proto3,oneof"`
}

type Content_AttributedToReaction struct {
	AttributedToReaction *AttributedToReaction `protobuf:"bytes,15,opt,name=attributed_to_reaction,json=attributedToReaction,proto3,oneof"`
}

type Content_ProfileUpdate struct {
	ProfileUpdate *ProfileUpdate `protobuf:"bytes,7,opt,name=profile_update,json=profileUpdate,proto3,oneof"`
}

type Content_Identity struct {
	Identity *Identity `protobuf:"bytes,8,opt,name=identity,proto3,oneof"`
}

type Content_Repost struct {
	Repost *Repost `protobuf:"bytes,9,opt,name=repost,proto3,oneof"`
}

type Content_Report struct {
	Report *Report `protobuf:"bytes,10,opt,name=report,proto3,oneof"`
}

type Content_Labels struct {
	Labels *Labels `protobuf:"bytes,11,opt,name=labels,proto3,oneof"`
}

type Content_VerificationClaim struct {
	// Verifications (see verifications.proto)
	VerificationClaim *VerificationClaim `protobuf:"bytes,12,opt,name=verification_claim,json=verificationClaim,proto3,oneof"`
}

type Content_VerificationVerify struct {
	VerificationVerify *VerificationVerify `protobuf:"bytes,13,opt,name=verification_verify,json=verificationVerify,proto3,oneof"`
}

type Content_VerificationTarget struct {
	VerificationTarget *VerificationTarget `protobuf:"bytes,14,opt,name=verification_target,json=verificationTarget,proto3,oneof"`
}

func (*Content_Post) isContent_ContentBody() {}

func (*Content_Delete) isContent_ContentBody() {}

func (*Content_Follow) isContent_ContentBody() {}

func (*Content_Block) isContent_ContentBody() {}

func (*Content_Reaction) isContent_ContentBody() {}

func (*Content_AttributedToReaction) isContent_ContentBody() {}

func (*Content_ProfileUpdate) isContent_ContentBody() {}

func (*Content_Identity) isContent_ContentBody() {}

func (*Content_Repost) isContent_ContentBody() {}

func (*Content_Report) isContent_ContentBody() {}

func (*Content_Labels) isContent_ContentBody() {}

func (*Content_VerificationClaim) isContent_ContentBody() {}

func (*Content_VerificationVerify) isContent_ContentBody() {}

func (*Content_VerificationTarget) isContent_ContentBody() {}

// Serialized content. This is what we do the ContentDigest / Checksum on.
type SerializedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentBytes  []byte                 `protobuf:"bytes,1,opt,name=content_bytes,json=contentBytes,proto3" json:"content_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedContent) Reset() {
	*x = SerializedContent{}
	mi := &file_polycentric_v2_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedContent) ProtoMessage() {}

func (x *SerializedContent) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedContent.ProtoReflect.Descriptor instead.
func (*SerializedContent) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{1}
}

func (x *SerializedContent) GetContentBytes() []byte {
	if x != nil {
		return x.ContentBytes
	}
	return nil
}

type Post struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Main text content of the post
	Text  string     `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Reply *PostReply `protobuf:"bytes,2,opt,name=reply,proto3,oneof" json:"reply,omitempty"`
	// Multiple images
	Images []*ImageSet `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Quote  *EventKey   `protobuf:"bytes,4,opt,name=quote,proto3,oneof" json:"quote,omitempty"`
	// Link previews for URLs in the post text
	Links []*Link `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	// Labels the creator / client applies themselves
	Labels []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	// If any, where the post is attributed to.
	AttributedTo  []*AttributedTo `protobuf:"bytes,7,rep,name=attributed_to,json=attributedTo,proto3" json:"attributed_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_polycentric_v2_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{2}
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Post) GetReply() *PostReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *Post) GetImages() []*ImageSet {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Post) GetQuote() *EventKey {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *Post) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Post) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Post) GetAttributedTo() []*AttributedTo {
	if x != nil {
		return x.AttributedTo
	}
	return nil
}

type AttributedTo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to To:
	//
	//	*AttributedTo_Link
	To            isAttributedTo_To `protobuf_oneof:"to"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedTo) Reset() {
	*x = AttributedTo{}
	mi := &file_polycentric_v2_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedTo) ProtoMessage() {}

func (x *AttributedTo) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedTo.ProtoReflect.Descriptor instead.
func (*AttributedTo) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{3}
}

func (x *AttributedTo) GetTo() isAttributedTo_To {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *AttributedTo) GetLink() *Link {
	if x != nil {
		if x, ok := x.To.(*AttributedTo_Link); ok {
			return x.Link
		}
	}
	return nil
}

type isAttributedTo_To interface {
	isAttributedTo_To()
}

type AttributedTo_Link struct {
	// Remote resource
	Link *Link `protobuf:"bytes,1,opt,name=link,proto3,oneof"`
}

func (*AttributedTo_Link) isAttributedTo_To() {}

type PostReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initial post in the reply chain.
	Root *EventKey `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Post that is being replied to
	Parent        *EventKey `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReply) Reset() {
	*x = PostReply{}
	mi := &file_polycentric_v2_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReply) ProtoMessage() {}

func (x *PostReply) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReply.ProtoReflect.Descriptor instead.
func (*PostReply) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{4}
}

func (x *PostReply) GetRoot() *EventKey {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *PostReply) GetParent() *EventKey {
	if x != nil {
		return x.Parent
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_polycentric_v2_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{5}
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Link) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Repost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *EventKey              `protobuf:"bytes,1,opt,name=post,proto3,oneof" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repost) Reset() {
	*x = Repost{}
	mi := &file_polycentric_v2_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repost) ProtoMessage() {}

func (x *Repost) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repost.ProtoReflect.Descriptor instead.
func (*Repost) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{6}
}

func (x *Repost) GetPost() *EventKey {
	if x != nil {
		return x.Post
	}
	return nil
}

// When processed by a server it should check if the data is referenced by any events
// If the Content is linked elswhere, the DELETE is ignored and the server should keep the data.
// If the Content is not linked elsewhere then it can be deleted / purged by the server.
// Essentially, a DELETE means; Ignore (or forget about) the contents of a previous event.
type Delete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event key to be deleted
	EventKey      *EventKey `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_polycentric_v2_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{7}
}

func (x *Delete) GetEventKey() *EventKey {
	if x != nil {
		return x.EventKey
	}
	return nil
}

type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_polycentric_v2_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{8}
}

func (x *Follow) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_polycentric_v2_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{9}
}

func (x *Block) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type Reaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key of the event being reacted to
	EventKey *EventKey `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	// Optional emoji
	Emoji *string `protobuf:"bytes,2,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	// Upvote = true. Downvote = false.
	Positive      bool `protobuf:"varint,3,opt,name=positive,proto3" json:"positive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_polycentric_v2_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{10}
}

func (x *Reaction) GetEventKey() *EventKey {
	if x != nil {
		return x.EventKey
	}
	return nil
}

func (x *Reaction) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *Reaction) GetPositive() bool {
	if x != nil {
		return x.Positive
	}
	return false
}

// A reaction targeting something that is not an in-network event — e.g. a URL
// (reacting to a video). The out-of-network counterpart of `Reaction`.
type AttributedToReaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the reaction is attributed to (e.g. a link/URL).
	AttributedTo *AttributedTo `protobuf:"bytes,1,opt,name=attributed_to,json=attributedTo,proto3" json:"attributed_to,omitempty"`
	// Optional emoji
	Emoji *string `protobuf:"bytes,2,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	// Upvote = true. Downvote = false.
	Positive      bool `protobuf:"varint,3,opt,name=positive,proto3" json:"positive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedToReaction) Reset() {
	*x = AttributedToReaction{}
	mi := &file_polycentric_v2_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedToReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedToReaction) ProtoMessage() {}

func (x *AttributedToReaction) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedToReaction.ProtoReflect.Descriptor instead.
func (*AttributedToReaction) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{11}
}

func (x *AttributedToReaction) GetAttributedTo() *AttributedTo {
	if x != nil {
		return x.AttributedTo
	}
	return nil
}

func (x *AttributedToReaction) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *AttributedToReaction) GetPositive() bool {
	if x != nil {
		return x.Positive
	}
	return false
}

type ProfileUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A friendly display name for the user
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Reference to the Blob for the avatar (support multiple different sizes)
	Avatar *ImageSet `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// Reference to the Blob of a banner (support multiple different sizes)
	Banner *ImageSet `protobuf:"bytes,3,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	// Bio
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// A domain-based alias (e.g. user@domain.com) the profile claims for itself.
	Alias         *string `protobuf:"bytes,5,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdate) Reset() {
	*x = ProfileUpdate{}
	mi := &file_polycentric_v2_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdate) ProtoMessage() {}

func (x *ProfileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdate.ProtoReflect.Descriptor instead.
func (*ProfileUpdate) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{12}
}

func (x *ProfileUpdate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProfileUpdate) GetAvatar() *ImageSet {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *ProfileUpdate) GetBanner() *ImageSet {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *ProfileUpdate) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProfileUpdate) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

// If an uploaded Blob is uploaded to the servers Object Storage and not
// then attached added to the Content repository, the server will delete from Object Storage.
type Blob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest/Checksum of the blob
	Digest        *ContentDigest `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	MimeType      string         `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64          `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_polycentric_v2_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{13}
}

func (x *Blob) GetDigest() *ContentDigest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Blob) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Blob) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Single image with reference to the blob
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          *Blob                  `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_polycentric_v2_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{14}
}

func (x *Image) GetBlob() *Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Collection of different variants of an image
type ImageSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSet) Reset() {
	*x = ImageSet{}
	mi := &file_polycentric_v2_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSet) ProtoMessage() {}

func (x *ImageSet) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSet.ProtoReflect.Descriptor instead.
func (*ImageSet) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{15}
}

func (x *ImageSet) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Report struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event that is being reported
	EventKey       *EventKey      `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	Category       ReportCategory `protobuf:"varint,2,opt,name=category,proto3,enum=polycentric.v2.ReportCategory" json:"category,omitempty"`
	AdditionalInfo string         `protobuf:"bytes,3,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_polycentric_v2_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{16}
}

func (x *Report) GetEventKey() *EventKey {
	if x != nil {
		return x.EventKey
	}
	return nil
}

func (x *Report) GetCategory() ReportCategory {
	if x != nil {
		return x.Category
	}
	return ReportCategory_REPORT_CATEGORY_UNSPECIFIED
}

func (x *Report) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

type Labels struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event that is being labeled
	EventKey      *EventKey `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	LabelValues   []string  `protobuf:"bytes,2,rep,name=label_values,json=labelValues,proto3" json:"label_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Labels) Reset() {
	*x = Labels{}
	mi := &file_polycentric_v2_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{17}
}

func (x *Labels) GetEventKey() *EventKey {
	if x != nil {
		return x.EventKey
	}
	return nil
}

func (x *Labels) GetLabelValues() []string {
	if x != nil {
		return x.LabelValues
	}
	return nil
}

// *
// gRPC requests
type SyncContentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest that was created from the serialized content_bytes
	Digest *ContentDigest `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Serialized Content message
	ContentBytes  []byte `protobuf:"bytes,2,opt,name=content_bytes,json=contentBytes,proto3" json:"content_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncContentRequest) Reset() {
	*x = SyncContentRequest{}
	mi := &file_polycentric_v2_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContentRequest) ProtoMessage() {}

func (x *SyncContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContentRequest.ProtoReflect.Descriptor instead.
func (*SyncContentRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{18}
}

func (x *SyncContentRequest) GetDigest() *ContentDigest {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *SyncContentRequest) GetContentBytes() []byte {
	if x != nil {
		return x.ContentBytes
	}
	return nil
}

type SyncContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncContentResponse) Reset() {
	*x = SyncContentResponse{}
	mi := &file_polycentric_v2_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContentResponse) ProtoMessage() {}

func (x *SyncContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContentResponse.ProtoReflect.Descriptor instead.
func (*SyncContentResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{19}
}

// *
// Request message for upoading a blob
type UploadBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference message of the blob (mime type, content digest).
	Blob *Blob `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	// Body (content) of the blob
	Body          []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlobRequest) Reset() {
	*x = UploadBlobRequest{}
	mi := &file_polycentric_v2_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlobRequest) ProtoMessage() {}

func (x *UploadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlobRequest.ProtoReflect.Descriptor instead.
func (*UploadBlobRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{20}
}

func (x *UploadBlobRequest) GetBlob() *Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *UploadBlobRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type UploadBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlobResponse) Reset() {
	*x = UploadBlobResponse{}
	mi := &file_polycentric_v2_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlobResponse) ProtoMessage() {}

func (x *UploadBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlobResponse.ProtoReflect.Descriptor instead.
func (*UploadBlobResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{21}
}

// *
// Request message for fetching link metadata for a URL.
type UrlInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL to fetch metadata for.
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlInfoRequest) Reset() {
	*x = UrlInfoRequest{}
	mi := &file_polycentric_v2_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlInfoRequest) ProtoMessage() {}

func (x *UrlInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlInfoRequest.ProtoReflect.Descriptor instead.
func (*UrlInfoRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{22}
}

func (x *UrlInfoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// *
// Response for UrlInfo: the fetched link-preview metadata.
type UrlInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlInfoResponse) Reset() {
	*x = UrlInfoResponse{}
	mi := &file_polycentric_v2_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlInfoResponse) ProtoMessage() {}

func (x *UrlInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlInfoResponse.ProtoReflect.Descriptor instead.
func (*UrlInfoResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_content_proto_rawDescGZIP(), []int{23}
}

func (x *UrlInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UrlInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UrlInfoResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_polycentric_v2_content_proto protoreflect.FileDescriptor

const file_polycentric_v2_content_proto_rawDesc = "" +
	"\n" +
	"\x1cpolycentric/v2/content.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1epolycentric/v2/event_key.proto\x1a\x1dpolycentric/v2/identity.proto\x1a\"polycentric/v2/verifications.proto\"\x86\a\n" +
	"\aContent\x12*\n" +
	"\x04post\x18\x02 \x01(\v2\x14.polycentric.v2.PostH\x00R\x04post\x120\n" +
	"\x06delete\x18\x03 \x01(\v2\x16.polycentric.v2.DeleteH\x00R\x06delete\x120\n" +
	"\x06follow\x18\x04 \x01(\v2\x16.polycentric.v2.FollowH\x00R\x06follow\x12-\n" +
	"\x05block\x18\x05 \x01(\v2\x15.polycentric.v2.BlockH\x00R\x05block\x126\n" +
	"\breaction\x18\x06 \x01(\v2\x18.polycentric.v2.ReactionH\x00R\breaction\x12\\\n" +
	"\x16attributed_to_reaction\x18\x0f \x01(\v2$.polycentric.v2.AttributedToReactionH\x00R\x14attributedToReaction\x12F\n" +
	"\x0eprofile_update\x18\a \x01(\v2\x1d.polycentric.v2.ProfileUpdateH\x00R\rprofileUpdate\x126\n" +
	"\bidentity\x18\b \x01(\v2\x18.polycentric.v2.IdentityH\x00R\bidentity\x120\n" +
	"\x06repost\x18\t \x01(\v2\x16.polycentric.v2.RepostH\x00R\x06repost\x120\n" +
	"\x06report\x18\n" +
	" \x01(\v2\x16.polycentric.v2.ReportH\x00R\x06report\x120\n" +
	"\x06labels\x18\v \x01(\v2\x16.polycentric.v2.LabelsH\x00R\x06labels\x12R\n" +
	"\x12verification_claim\x18\f \x01(\v2!.polycentric.v2.VerificationClaimH\x00R\x11verificationClaim\x12U\n" +
	"\x13verification_verify\x18\r \x01(\v2\".polycentric.v2.VerificationVerifyH\x00R\x12verificationVerify\x12U\n" +
	"\x13verification_target\x18\x0e \x01(\v2\".polycentric.v2.VerificationTargetH\x00R\x12verificationTargetB\x0e\n" +
	"\fcontent_body\"8\n" +
	"\x11SerializedContent\x12#\n" +
	"\rcontent_bytes\x18\x01 \x01(\fR\fcontentBytes\"\xd2\x02\n" +
	"\x04Post\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x124\n" +
	"\x05reply\x18\x02 \x01(\v2\x19.polycentric.v2.PostReplyH\x00R\x05reply\x88\x01\x01\x120\n" +
	"\x06images\x18\x03 \x03(\v2\x18.polycentric.v2.ImageSetR\x06images\x123\n" +
	"\x05quote\x18\x04 \x01(\v2\x18.polycentric.v2.EventKeyH\x01R\x05quote\x88\x01\x01\x12*\n" +
	"\x05links\x18\x05 \x03(\v2\x14.polycentric.v2.LinkR\x05links\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x12A\n" +
	"\rattributed_to\x18\a \x03(\v2\x1c.polycentric.v2.AttributedToR\fattributedToB\b\n" +
	"\x06_replyB\b\n" +
	"\x06_quote\"@\n" +
	"\fAttributedTo\x12*\n" +
	"\x04link\x18\x01 \x01(\v2\x14.polycentric.v2.LinkH\x00R\x04linkB\x04\n" +
	"\x02to\"k\n" +
	"\tPostReply\x12,\n" +
	"\x04root\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\x04root\x120\n" +
	"\x06parent\x18\x02 \x01(\v2\x18.polycentric.v2.EventKeyR\x06parent\"f\n" +
	"\x04Link\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"D\n" +
	"\x06Repost\x121\n" +
	"\x04post\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyH\x00R\x04post\x88\x01\x01B\a\n" +
	"\x05_post\"?\n" +
	"\x06Delete\x125\n" +
	"\tevent_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\beventKey\"$\n" +
	"\x06Follow\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"#\n" +
	"\x05Block\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\x82\x01\n" +
	"\bReaction\x125\n" +
	"\tevent_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\beventKey\x12\x19\n" +
	"\x05emoji\x18\x02 \x01(\tH\x00R\x05emoji\x88\x01\x01\x12\x1a\n" +
	"\bpositive\x18\x03 \x01(\bR\bpositiveB\b\n" +
	"\x06_emoji\"\x9a\x01\n" +
	"\x14AttributedToReaction\x12A\n" +
	"\rattributed_to\x18\x01 \x01(\v2\x1c.polycentric.v2.AttributedToR\fattributedTo\x12\x19\n" +
	"\x05emoji\x18\x02 \x01(\tH\x00R\x05emoji\x88\x01\x01\x12\x1a\n" +
	"\bpositive\x18\x03 \x01(\bR\bpositiveB\b\n" +
	"\x06_emoji\"\x91\x02\n" +
	"\rProfileUpdate\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x125\n" +
	"\x06avatar\x18\x02 \x01(\v2\x18.polycentric.v2.ImageSetH\x01R\x06avatar\x88\x01\x01\x125\n" +
	"\x06banner\x18\x03 \x01(\v2\x18.polycentric.v2.ImageSetH\x02R\x06banner\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05alias\x18\x05 \x01(\tH\x04R\x05alias\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_avatarB\t\n" +
	"\a_bannerB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_alias\"n\n" +
	"\x04Blob\x125\n" +
	"\x06digest\x18\x01 \x01(\v2\x1d.polycentric.v2.ContentDigestR\x06digest\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"_\n" +
	"\x05Image\x12(\n" +
	"\x04blob\x18\x01 \x01(\v2\x14.polycentric.v2.BlobR\x04blob\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"9\n" +
	"\bImageSet\x12-\n" +
	"\x06images\x18\x01 \x03(\v2\x15.polycentric.v2.ImageR\x06images\"\xa4\x01\n" +
	"\x06Report\x125\n" +
	"\tevent_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\beventKey\x12:\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1e.polycentric.v2.ReportCategoryR\bcategory\x12'\n" +
	"\x0fadditional_info\x18\x03 \x01(\tR\x0eadditionalInfo\"b\n" +
	"\x06Labels\x125\n" +
	"\tevent_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\beventKey\x12!\n" +
	"\flabel_values\x18\x02 \x03(\tR\vlabelValues\"p\n" +
	"\x12SyncContentRequest\x125\n" +
	"\x06digest\x18\x01 \x01(\v2\x1d.polycentric.v2.ContentDigestR\x06digest\x12#\n" +
	"\rcontent_bytes\x18\x02 \x01(\fR\fcontentBytes\"\x15\n" +
	"\x13SyncContentResponse\"Q\n" +
	"\x11UploadBlobRequest\x12(\n" +
	"\x04blob\x18\x01 \x01(\v2\x14.polycentric.v2.BlobR\x04blob\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"\x14\n" +
	"\x12UploadBlobResponse\"\"\n" +
	"\x0eUrlInfoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"_\n" +
	"\x0fUrlInfoResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image*\x8a\x03\n" +
	"\x0eReportCategory\x12\x1f\n" +
	"\x1bREPORT_CATEGORY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REPORT_CATEGORY_SPAM\x10\x01\x12 \n" +
	"\x1cREPORT_CATEGORY_CHILD_SAFETY\x10\x03\x12\x1d\n" +
	"\x19REPORT_CATEGORY_COPYRIGHT\x10\x06\x12!\n" +
	"\x1dREPORT_CATEGORY_SERVER_POLICY\x10\a\x12\x1c\n" +
	"\x18REPORT_CATEGORY_VIOLENCE\x10\b\x12\x1d\n" +
	"\x19REPORT_CATEGORY_SELF_HARM\x10\t\x12%\n" +
	"!REPORT_CATEGORY_SEXUALLY_EXPLICIT\x10\n" +
	"\x12\x18\n" +
	"\x14REPORT_CATEGORY_HATE\x10\v\"\x04\b\x02\x10\x02\"\x04\b\x04\x10\x04\"\x04\b\x05\x10\x05*\x15REPORT_CATEGORY_ABUSE*\x19REPORT_CATEGORY_TERRORISM*\x17REPORT_CATEGORY_ILLEGAL2\x89\x02\n" +
	"\x0eContentService\x12V\n" +
	"\vSyncContent\x12\".polycentric.v2.SyncContentRequest\x1a#.polycentric.v2.SyncContentResponse\x12S\n" +
	"\n" +
	"UploadBlob\x12!.polycentric.v2.UploadBlobRequest\x1a\".polycentric.v2.UploadBlobResponse\x12J\n" +
	"\aUrlInfo\x12\x1e.polycentric.v2.UrlInfoRequest\x1a\x1f.polycentric.v2.UrlInfoResponseB\xce\x01\n" +
	"\x12com.polycentric.v2B\fContentProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_content_proto_rawDescOnce sync.Once
	file_polycentric_v2_content_proto_rawDescData []byte
)

func file_polycentric_v2_content_proto_rawDescGZIP() []byte {
	file_polycentric_v2_content_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_content_proto_rawDesc), len(file_polycentric_v2_content_proto_rawDesc)))
	})
	return file_polycentric_v2_content_proto_rawDescData
}

var file_polycentric_v2_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polycentric_v2_content_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_polycentric_v2_content_proto_goTypes = []any{
	(ReportCategory)(0),          // 0: polycentric.v2.ReportCategory
	(*Content)(nil),              // 1: polycentric.v2.Content
	(*SerializedContent)(nil),    // 2: polycentric.v2.SerializedContent
	(*Post)(nil),                 // 3: polycentric.v2.Post
	(*AttributedTo)(nil),         // 4: polycentric.v2.AttributedTo
	(*PostReply)(nil),            // 5: polycentric.v2.PostReply
	(*Link)(nil),                 // 6: polycentric.v2.Link
	(*Repost)(nil),               // 7: polycentric.v2.Repost
	(*Delete)(nil),               // 8: polycentric.v2.Delete
	(*Follow)(nil),               // 9: polycentric.v2.Follow
	(*Block)(nil),                // 10: polycentric.v2.Block
	(*Reaction)(nil),             // 11: polycentric.v2.Reaction
	(*AttributedToReaction)(nil), // 12: polycentric.v2.AttributedToReaction
	(*ProfileUpdate)(nil),        // 13: polycentric.v2.ProfileUpdate
	(*Blob)(nil),                 // 14: polycentric.v2.Blob
	(*Image)(nil),                // 15: polycentric.v2.Image
	(*ImageSet)(nil),             // 16: polycentric.v2.ImageSet
	(*Report)(nil),               // 17: polycentric.v2.Report
	(*Labels)(nil),               // 18: polycentric.v2.Labels
	(*SyncContentRequest)(nil),   // 19: polycentric.v2.SyncContentRequest
	(*SyncContentResponse)(nil),  // 20: polycentric.v2.SyncContentResponse
	(*UploadBlobRequest)(nil),    // 21: polycentric.v2.UploadBlobRequest
	(*UploadBlobResponse)(nil),   // 22: polycentric.v2.UploadBlobResponse
	(*UrlInfoRequest)(nil),       // 23: polycentric.v2.UrlInfoRequest
	(*UrlInfoResponse)(nil),      // 24: polycentric.v2.UrlInfoResponse
	(*Identity)(nil),             // 25: polycentric.v2.Identity
	(*VerificationClaim)(nil),    // 26: polycentric.v2.VerificationClaim
	(*VerificationVerify)(nil),   // 27: polycentric.v2.VerificationVerify
	(*VerificationTarget)(nil),   // 28: polycentric.v2.VerificationTarget
	(*EventKey)(nil),             // 29: polycentric.v2.EventKey
	(*ContentDigest)(nil),        // 30: polycentric.v2.ContentDigest
}
var file_polycentric_v2_content_proto_depIdxs = []int32{
	3,  // 0: polycentric.v2.Content.post:type_name -> polycentric.v2.Post
	8,  // 1: polycentric.v2.Content.delete:type_name -> polycentric.v2.Delete
	9,  // 2: polycentric.v2.Content.follow:type_name -> polycentric.v2.Follow
	10, // 3: polycentric.v2.Content.block:type_name -> polycentric.v2.Block
	11, // 4: polycentric.v2.Content.reaction:type_name -> polycentric.v2.Reaction
	12, // 5: polycentric.v2.Content.attributed_to_reaction:type_name -> polycentric.v2.AttributedToReaction
	13, // 6: polycentric.v2.Content.profile_update:type_name -> polycentric.v2.ProfileUpdate
	25, // 7: polycentric.v2.Content.identity:type_name -> polycentric.v2.Identity
	7,  // 8: polycentric.v2.Content.repost:type_name -> polycentric.v2.Repost
	17, // 9: polycentric.v2.Content.report:type_name -> polycentric.v2.Report
	18, // 10: polycentric.v2.Content.labels:type_name -> polycentric.v2.Labels
	26, // 11: polycentric.v2.Content.verification_claim:type_name -> polycentric.v2.VerificationClaim
	27, // 12: polycentric.v2.Content.verification_verify:type_name -> polycentric.v2.VerificationVerify
	28, // 13: polycentric.v2.Content.verification_target:type_name -> polycentric.v2.VerificationTarget
	5,  // 14: polycentric.v2.Post.reply:type_name -> polycentric.v2.PostReply
	16, // 15: polycentric.v2.Post.images:type_name -> polycentric.v2.ImageSet
	29, // 16: polycentric.v2.Post.quote:type_name -> polycentric.v2.EventKey
	6,  // 17: polycentric.v2.Post.links:type_name -> polycentric.v2.Link
	4,  // 18: polycentric.v2.Post.attributed_to:type_name -> polycentric.v2.AttributedTo
	6,  // 19: polycentric.v2.AttributedTo.link:type_name -> polycentric.v2.Link
	29, // 20: polycentric.v2.PostReply.root:type_name -> polycentric.v2.EventKey
	29, // 21: polycentric.v2.PostReply.parent:type_name -> polycentric.v2.EventKey
	29, // 22: polycentric.v2.Repost.post:type_name -> polycentric.v2.EventKey
	29, // 23: polycentric.v2.Delete.event_key:type_name -> polycentric.v2.EventKey
	29, // 24: polycentric.v2.Reaction.event_key:type_name -> polycentric.v2.EventKey
	4,  // 25: polycentric.v2.AttributedToReaction.attributed_to:type_name -> polycentric.v2.AttributedTo
	16, // 26: polycentric.v2.ProfileUpdate.avatar:type_name -> polycentric.v2.ImageSet
	16, // 27: polycentric.v2.ProfileUpdate.banner:type_name -> polycentric.v2.ImageSet
	30, // 28: polycentric.v2.Blob.digest:type_name -> polycentric.v2.ContentDigest
	14, // 29: polycentric.v2.Image.blob:type_name -> polycentric.v2.Blob
	15, // 30: polycentric.v2.ImageSet.images:type_name -> polycentric.v2.Image
	29, // 31: polycentric.v2.Report.event_key:type_name -> polycentric.v2.EventKey
	0,  // 32: polycentric.v2.Report.category:type_name -> polycentric.v2.ReportCategory
	29, // 33: polycentric.v2.Labels.event_key:type_name -> polycentric.v2.EventKey
	30, // 34: polycentric.v2.SyncContentRequest.digest:type_name -> polycentric.v2.ContentDigest
	14, // 35: polycentric.v2.UploadBlobRequest.blob:type_name -> polycentric.v2.Blob
	19, // 36: polycentric.v2.ContentService.SyncContent:input_type -> polycentric.v2.SyncContentRequest
	21, // 37: polycentric.v2.ContentService.UploadBlob:input_type -> polycentric.v2.UploadBlobRequest
	23, // 38: polycentric.v2.ContentService.UrlInfo:input_type -> polycentric.v2.UrlInfoRequest
	20, // 39: polycentric.v2.ContentService.SyncContent:output_type -> polycentric.v2.SyncContentResponse
	22, // 40: polycentric.v2.ContentService.UploadBlob:output_type -> polycentric.v2.UploadBlobResponse
	24, // 41: polycentric.v2.ContentService.UrlInfo:output_type -> polycentric.v2.UrlInfoResponse
	39, // [39:42] is the sub-list for method output_type
	36, // [36:39] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_polycentric_v2_content_proto_init() }
func file_polycentric_v2_content_proto_init() {
	if File_polycentric_v2_content_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_event_key_proto_init()
	file_polycentric_v2_identity_proto_init()
	file_polycentric_v2_verifications_proto_init()
	file_polycentric_v2_content_proto_msgTypes[0].OneofWrappers = []any{
		(*Content_Post)(nil),
		(*Content_Delete)(nil),
		(*Content_Follow)(nil),
		(*Content_Block)(nil),
		(*Content_Reaction)(nil),
		(*Content_AttributedToReaction)(nil),
		(*Content_ProfileUpdate)(nil),
		(*Content_Identity)(nil),
		(*Content_Repost)(nil),
		(*Content_Report)(nil),
		(*Content_Labels)(nil),
		(*Content_VerificationClaim)(nil),
		(*Content_VerificationVerify)(nil),
		(*Content_VerificationTarget)(nil),
	}
	file_polycentric_v2_content_proto_msgTypes[2].OneofWrappers = []any{}
	file_polycentric_v2_content_proto_msgTypes[3].OneofWrappers = []any{
		(*AttributedTo_Link)(nil),
	}
	file_polycentric_v2_content_proto_msgTypes[6].OneofWrappers = []any{}
	file_polycentric_v2_content_proto_msgTypes[10].OneofWrappers = []any{}
	file_polycentric_v2_content_proto_msgTypes[11].OneofWrappers = []any{}
	file_polycentric_v2_content_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_content_proto_rawDesc), len(file_polycentric_v2_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_content_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_content_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_content_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_content_proto_msgTypes,
	}.Build()
	File_polycentric_v2_content_proto = out.File
	file_polycentric_v2_content_proto_goTypes = nil
	file_polycentric_v2_content_proto_depIdxs = nil
}
