// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/events.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contains the sequences (of the same event collection) that the current KeyPair is aware of.
// The order of the sequences is determined by the keys listed in the relevant identity document:
// The rotation keys first and then the signing keys, with duplicates skipped when they appear again.
// Use `Identity::deduplicated_keys()` to get the keys in this order.
type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      []uint64               `protobuf:"varint,1,rep,packed,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_polycentric_v2_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetSequence() []uint64 {
	if x != nil {
		return x.Sequence
	}
	return nil
}

// The application that authored an event.
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name, e.g. "Harbor".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Reverse-DNS package or bundle identifier, e.g. "org.futo.polycentric".
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Version of the application, e.g. "1.2.0".
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Website of the application, e.g. "https://harbor.social".
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_polycentric_v2_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{1}
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Application) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Event messages reference, but do not include, content
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key for the event
	Key *EventKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Reference to the sequence, of the Identity Collection (1), that holds the identity document
	IdentitySequence uint64 `protobuf:"varint,2,opt,name=identity_sequence,json=identitySequence,proto3" json:"identity_sequence,omitempty"`
	// Vector clock
	VectorClock *VectorClock `protobuf:"bytes,3,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	// Signature of the previous event signed by the same key. Assists in creating
	// immutable collections.
	PreviousSignature []byte `protobuf:"bytes,4,opt,name=previous_signature,json=previousSignature,proto3" json:"previous_signature,omitempty"`
	// Digest of the content
	ContentDigest *ContentDigest `protobuf:"bytes,6,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	// Timestamp, in milliseconds, of when the event was created
	CreatedAt uint64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// RFC 6962 Merkle root over this signer's prior signatures in this collection
	// (leaf_count = key.sequence - 1). Lets later events attest to the writer's
	// history; consumed by EventProof for membership verification.
	PreviousRoot []byte `protobuf:"bytes,8,opt,name=previous_root,json=previousRoot,proto3" json:"previous_root,omitempty"`
	// The application that created the event. Absent when unknown.
	Application   *Application `protobuf:"bytes,9,opt,name=application,proto3,oneof" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_polycentric_v2_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetKey() *EventKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Event) GetIdentitySequence() uint64 {
	if x != nil {
		return x.IdentitySequence
	}
	return 0
}

func (x *Event) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *Event) GetPreviousSignature() []byte {
	if x != nil {
		return x.PreviousSignature
	}
	return nil
}

func (x *Event) GetContentDigest() *ContentDigest {
	if x != nil {
		return x.ContentDigest
	}
	return nil
}

func (x *Event) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetPreviousRoot() []byte {
	if x != nil {
		return x.PreviousRoot
	}
	return nil
}

func (x *Event) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type SignedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signature of events_bytes below (not the Event message)
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Serialized representation of the Event message that is signed against
	EventBytes    []byte `protobuf:"bytes,2,opt,name=event_bytes,json=eventBytes,proto3" json:"event_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedEvent) Reset() {
	*x = SignedEvent{}
	mi := &file_polycentric_v2_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEvent) ProtoMessage() {}

func (x *SignedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEvent.ProtoReflect.Descriptor instead.
func (*SignedEvent) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{3}
}

func (x *SignedEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedEvent) GetEventBytes() []byte {
	if x != nil {
		return x.EventBytes
	}
	return nil
}

// Bundle of the SignedEvent and SerializedContent messages
// We use SerializedContent so that the checksum of the content
// can be verified
type EventBundle struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedEvent       *SignedEvent           `protobuf:"bytes,1,opt,name=signed_event,json=signedEvent,proto3" json:"signed_event,omitempty"`
	SerializedContent *SerializedContent     `protobuf:"bytes,2,opt,name=serialized_content,json=serializedContent,proto3,oneof" json:"serialized_content,omitempty"`
	EventProofs       []*EventProof          `protobuf:"bytes,3,rep,name=event_proofs,json=eventProofs,proto3" json:"event_proofs,omitempty"`
	Meta              *EventMetadata         `protobuf:"bytes,4,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventBundle) Reset() {
	*x = EventBundle{}
	mi := &file_polycentric_v2_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBundle) ProtoMessage() {}

func (x *EventBundle) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBundle.ProtoReflect.Descriptor instead.
func (*EventBundle) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventBundle) GetSignedEvent() *SignedEvent {
	if x != nil {
		return x.SignedEvent
	}
	return nil
}

func (x *EventBundle) GetSerializedContent() *SerializedContent {
	if x != nil {
		return x.SerializedContent
	}
	return nil
}

func (x *EventBundle) GetEventProofs() []*EventProof {
	if x != nil {
		return x.EventProofs
	}
	return nil
}

func (x *EventBundle) GetMeta() *EventMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Merkle inclusion proof: the SignedEvent in this bundle is the leaf at
// `leaf_index` in the tree rooted at the `EventProofTarget` identified by
// `target_signature`.
type EventProof struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetSignature []byte                 `protobuf:"bytes,1,opt,name=target_signature,json=targetSignature,proto3" json:"target_signature,omitempty"`
	// Canonical position of this event in the target's tree.
	LeafIndex uint64 `protobuf:"varint,2,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	// RFC 6962 audit path: sibling hashes from leaf toward root.
	AuditPath     [][]byte `protobuf:"bytes,3,rep,name=audit_path,json=auditPath,proto3" json:"audit_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProof) Reset() {
	*x = EventProof{}
	mi := &file_polycentric_v2_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProof) ProtoMessage() {}

func (x *EventProof) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProof.ProtoReflect.Descriptor instead.
func (*EventProof) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{5}
}

func (x *EventProof) GetTargetSignature() []byte {
	if x != nil {
		return x.TargetSignature
	}
	return nil
}

func (x *EventProof) GetLeafIndex() uint64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *EventProof) GetAuditPath() [][]byte {
	if x != nil {
		return x.AuditPath
	}
	return nil
}

// Optional helper data that servers can include to help clients better present
// information to users.
type EventMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This server's estimate for how many replies a post has.
	ReplyCount *int32 `protobuf:"varint,1,opt,name=reply_count,json=replyCount,proto3,oneof" json:"reply_count,omitempty"`
	// This server's estimate for the total number of reactions a post has.
	ReactionCount *int32 `protobuf:"varint,2,opt,name=reaction_count,json=reactionCount,proto3,oneof" json:"reaction_count,omitempty"`
	// This server's estimate for the total number of positive reactions a post has.
	UpvoteCount *int32 `protobuf:"varint,3,opt,name=upvote_count,json=upvoteCount,proto3,oneof" json:"upvote_count,omitempty"`
	// This server's estimate for the total number of negative reactions a post has.
	DownvoteCount *int32 `protobuf:"varint,4,opt,name=downvote_count,json=downvoteCount,proto3,oneof" json:"downvote_count,omitempty"`
	// This server's estimate for the count for each reaction type a post has.
	EmojiReactions []*ReactionTally `protobuf:"bytes,5,rep,name=emoji_reactions,json=emojiReactions,proto3" json:"emoji_reactions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_polycentric_v2_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventMetadata) GetReplyCount() int32 {
	if x != nil && x.ReplyCount != nil {
		return *x.ReplyCount
	}
	return 0
}

func (x *EventMetadata) GetReactionCount() int32 {
	if x != nil && x.ReactionCount != nil {
		return *x.ReactionCount
	}
	return 0
}

func (x *EventMetadata) GetUpvoteCount() int32 {
	if x != nil && x.UpvoteCount != nil {
		return *x.UpvoteCount
	}
	return 0
}

func (x *EventMetadata) GetDownvoteCount() int32 {
	if x != nil && x.DownvoteCount != nil {
		return *x.DownvoteCount
	}
	return 0
}

func (x *EventMetadata) GetEmojiReactions() []*ReactionTally {
	if x != nil {
		return x.EmojiReactions
	}
	return nil
}

// Conveys the number of times a specific reaction was given.
type ReactionTally struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emoji         string                 `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Positive      bool                   `protobuf:"varint,2,opt,name=positive,proto3" json:"positive,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionTally) Reset() {
	*x = ReactionTally{}
	mi := &file_polycentric_v2_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionTally) ProtoMessage() {}

func (x *ReactionTally) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionTally.ProtoReflect.Descriptor instead.
func (*ReactionTally) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{7}
}

func (x *ReactionTally) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *ReactionTally) GetPositive() bool {
	if x != nil {
		return x.Positive
	}
	return false
}

func (x *ReactionTally) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Hints are additional events that the server provides that may be
// useful to the client and avoid additional network requests.
// For example, a reply to post event could return the root/parent posts along with the
// most recent profile event
type EventHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBundle   *EventBundle           `protobuf:"bytes,1,opt,name=event_bundle,json=eventBundle,proto3" json:"event_bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventHint) Reset() {
	*x = EventHint{}
	mi := &file_polycentric_v2_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHint) ProtoMessage() {}

func (x *EventHint) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHint.ProtoReflect.Descriptor instead.
func (*EventHint) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{8}
}

func (x *EventHint) GetEventBundle() *EventBundle {
	if x != nil {
		return x.EventBundle
	}
	return nil
}

type ListEventsFilters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collection to filter events by
	Collection *int32 `protobuf:"varint,1,opt,name=collection,proto3,oneof" json:"collection,omitempty"`
	// Identity key to filter events by
	Identity *string `protobuf:"bytes,2,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
	// Filter events to those signed by this public key
	SignedBy *PublicKey `protobuf:"bytes,3,opt,name=signed_by,json=signedBy,proto3,oneof" json:"signed_by,omitempty"`
	// Return sequences greater than
	SequenceGt *int64 `protobuf:"varint,4,opt,name=sequence_gt,json=sequenceGt,proto3,oneof" json:"sequence_gt,omitempty"`
	// Return sequences less than
	SequenceLt *int64 `protobuf:"varint,5,opt,name=sequence_lt,json=sequenceLt,proto3,oneof" json:"sequence_lt,omitempty"`
	// When an event matches a head's identity, collection, and signer,
	// only return it if its sequence number is higher than the head
	Heads         []*EventKey `protobuf:"bytes,6,rep,name=heads,proto3" json:"heads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsFilters) Reset() {
	*x = ListEventsFilters{}
	mi := &file_polycentric_v2_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsFilters) ProtoMessage() {}

func (x *ListEventsFilters) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsFilters.ProtoReflect.Descriptor instead.
func (*ListEventsFilters) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{9}
}

func (x *ListEventsFilters) GetCollection() int32 {
	if x != nil && x.Collection != nil {
		return *x.Collection
	}
	return 0
}

func (x *ListEventsFilters) GetIdentity() string {
	if x != nil && x.Identity != nil {
		return *x.Identity
	}
	return ""
}

func (x *ListEventsFilters) GetSignedBy() *PublicKey {
	if x != nil {
		return x.SignedBy
	}
	return nil
}

func (x *ListEventsFilters) GetSequenceGt() int64 {
	if x != nil && x.SequenceGt != nil {
		return *x.SequenceGt
	}
	return 0
}

func (x *ListEventsFilters) GetSequenceLt() int64 {
	if x != nil && x.SequenceLt != nil {
		return *x.SequenceLt
	}
	return 0
}

func (x *ListEventsFilters) GetHeads() []*EventKey {
	if x != nil {
		return x.Heads
	}
	return nil
}

type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters
	Filters *ListEventsFilters `protobuf:"bytes,1,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	// Max number of events to return
	Size          *int32 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_polycentric_v2_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventsRequest) GetFilters() *ListEventsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListEventsRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBundles  []*EventBundle         `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	EventHints    []*EventHint           `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_polycentric_v2_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{11}
}

func (x *ListEventsResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *ListEventsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type PutEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBundles  []*EventBundle         `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEventsRequest) Reset() {
	*x = PutEventsRequest{}
	mi := &file_polycentric_v2_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEventsRequest) ProtoMessage() {}

func (x *PutEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEventsRequest.ProtoReflect.Descriptor instead.
func (*PutEventsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{12}
}

func (x *PutEventsRequest) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

// Per-event failure reported by PutEvents. The call as a whole still
// succeeds — these entries are diagnostic for events the server
// skipped.
type PutEventError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the failed entry in PutEventsRequest.event_bundles.
	EventBundleIndex uint32 `protobuf:"varint,1,opt,name=event_bundle_index,json=eventBundleIndex,proto3" json:"event_bundle_index,omitempty"`
	// Human-readable reason mirroring the gRPC Status ingest would
	// otherwise have returned for this event in isolation.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEventError) Reset() {
	*x = PutEventError{}
	mi := &file_polycentric_v2_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEventError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEventError) ProtoMessage() {}

func (x *PutEventError) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEventError.ProtoReflect.Descriptor instead.
func (*PutEventError) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{13}
}

func (x *PutEventError) GetEventBundleIndex() uint32 {
	if x != nil {
		return x.EventBundleIndex
	}
	return 0
}

func (x *PutEventError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PutEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per event the server could not store. Empty when every
	// event in the request was accepted.
	Errors []*PutEventError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Blobs referenced by the events that the server does not have.
	// Client should upload these.
	RequestedBlobs []*Blob `protobuf:"bytes,2,rep,name=requested_blobs,json=requestedBlobs,proto3" json:"requested_blobs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutEventsResponse) Reset() {
	*x = PutEventsResponse{}
	mi := &file_polycentric_v2_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEventsResponse) ProtoMessage() {}

func (x *PutEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEventsResponse.ProtoReflect.Descriptor instead.
func (*PutEventsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{14}
}

func (x *PutEventsResponse) GetErrors() []*PutEventError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *PutEventsResponse) GetRequestedBlobs() []*Blob {
	if x != nil {
		return x.RequestedBlobs
	}
	return nil
}

type ListHeadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeadsRequest) Reset() {
	*x = ListHeadsRequest{}
	mi := &file_polycentric_v2_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeadsRequest) ProtoMessage() {}

func (x *ListHeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeadsRequest.ProtoReflect.Descriptor instead.
func (*ListHeadsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{15}
}

func (x *ListHeadsRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ListHeadsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each event key represents the greatest sequence number
	// with the same (identity, public key, collection) known by this server
	Heads         []*EventKey `protobuf:"bytes,1,rep,name=heads,proto3" json:"heads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHeadsResponse) Reset() {
	*x = ListHeadsResponse{}
	mi := &file_polycentric_v2_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeadsResponse) ProtoMessage() {}

func (x *ListHeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeadsResponse.ProtoReflect.Descriptor instead.
func (*ListHeadsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{16}
}

func (x *ListHeadsResponse) GetHeads() []*EventKey {
	if x != nil {
		return x.Heads
	}
	return nil
}

type GetReactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event key of the event to get reactions for
	Target *EventKey `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Return only reactions with this emoji set
	EmojiFilter   *string     `protobuf:"bytes,2,opt,name=emoji_filter,json=emojiFilter,proto3,oneof" json:"emoji_filter,omitempty"`
	PageParams    *PageParams `protobuf:"bytes,3,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionsRequest) Reset() {
	*x = GetReactionsRequest{}
	mi := &file_polycentric_v2_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsRequest) ProtoMessage() {}

func (x *GetReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetReactionsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{17}
}

func (x *GetReactionsRequest) GetTarget() *EventKey {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GetReactionsRequest) GetEmojiFilter() string {
	if x != nil && x.EmojiFilter != nil {
		return *x.EmojiFilter
	}
	return ""
}

func (x *GetReactionsRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

type GetReactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBundles  []*EventBundle         `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	EventHints    []*EventHint           `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3,oneof" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionsResponse) Reset() {
	*x = GetReactionsResponse{}
	mi := &file_polycentric_v2_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsResponse) ProtoMessage() {}

func (x *GetReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsResponse.ProtoReflect.Descriptor instead.
func (*GetReactionsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{18}
}

func (x *GetReactionsResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *GetReactionsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

func (x *GetReactionsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetAttributedToReactionCountsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attributed target (e.g. a video URL) to get reaction counts for.
	AttributedTo  *AttributedTo `protobuf:"bytes,1,opt,name=attributed_to,json=attributedTo,proto3" json:"attributed_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributedToReactionCountsRequest) Reset() {
	*x = GetAttributedToReactionCountsRequest{}
	mi := &file_polycentric_v2_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributedToReactionCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributedToReactionCountsRequest) ProtoMessage() {}

func (x *GetAttributedToReactionCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributedToReactionCountsRequest.ProtoReflect.Descriptor instead.
func (*GetAttributedToReactionCountsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{19}
}

func (x *GetAttributedToReactionCountsRequest) GetAttributedTo() *AttributedTo {
	if x != nil {
		return x.AttributedTo
	}
	return nil
}

type GetAttributedToReactionCountsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's estimate for positive reactions on the target.
	UpvoteCount int64 `protobuf:"varint,1,opt,name=upvote_count,json=upvoteCount,proto3" json:"upvote_count,omitempty"`
	// The server's estimate for negative reactions on the target.
	DownvoteCount int64 `protobuf:"varint,2,opt,name=downvote_count,json=downvoteCount,proto3" json:"downvote_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributedToReactionCountsResponse) Reset() {
	*x = GetAttributedToReactionCountsResponse{}
	mi := &file_polycentric_v2_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributedToReactionCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributedToReactionCountsResponse) ProtoMessage() {}

func (x *GetAttributedToReactionCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributedToReactionCountsResponse.ProtoReflect.Descriptor instead.
func (*GetAttributedToReactionCountsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_events_proto_rawDescGZIP(), []int{20}
}

func (x *GetAttributedToReactionCountsResponse) GetUpvoteCount() int64 {
	if x != nil {
		return x.UpvoteCount
	}
	return 0
}

func (x *GetAttributedToReactionCountsResponse) GetDownvoteCount() int64 {
	if x != nil {
		return x.DownvoteCount
	}
	return 0
}

var File_polycentric_v2_events_proto protoreflect.FileDescriptor

const file_polycentric_v2_events_proto_rawDesc = "" +
	"\n" +
	"\x1bpolycentric/v2/events.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1cpolycentric/v2/content.proto\x1a\x1epolycentric/v2/event_key.proto\x1a\x1cpolycentric/v2/keypair.proto\")\n" +
	"\vVectorClock\x12\x1a\n" +
	"\bsequence\x18\x01 \x03(\x04R\bsequence\"]\n" +
	"\vApplication\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\xad\x03\n" +
	"\x05Event\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\x03key\x12+\n" +
	"\x11identity_sequence\x18\x02 \x01(\x04R\x10identitySequence\x12>\n" +
	"\fvector_clock\x18\x03 \x01(\v2\x1b.polycentric.v2.VectorClockR\vvectorClock\x12-\n" +
	"\x12previous_signature\x18\x04 \x01(\fR\x11previousSignature\x12D\n" +
	"\x0econtent_digest\x18\x06 \x01(\v2\x1d.polycentric.v2.ContentDigestR\rcontentDigest\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x04R\tcreatedAt\x12#\n" +
	"\rprevious_root\x18\b \x01(\fR\fpreviousRoot\x12B\n" +
	"\vapplication\x18\t \x01(\v2\x1b.polycentric.v2.ApplicationH\x00R\vapplication\x88\x01\x01B\x0e\n" +
	"\f_application\"L\n" +
	"\vSignedEvent\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1f\n" +
	"\vevent_bytes\x18\x02 \x01(\fR\n" +
	"eventBytes\"\xbb\x02\n" +
	"\vEventBundle\x12>\n" +
	"\fsigned_event\x18\x01 \x01(\v2\x1b.polycentric.v2.SignedEventR\vsignedEvent\x12U\n" +
	"\x12serialized_content\x18\x02 \x01(\v2!.polycentric.v2.SerializedContentH\x00R\x11serializedContent\x88\x01\x01\x12=\n" +
	"\fevent_proofs\x18\x03 \x03(\v2\x1a.polycentric.v2.EventProofR\veventProofs\x126\n" +
	"\x04meta\x18\x04 \x01(\v2\x1d.polycentric.v2.EventMetadataH\x01R\x04meta\x88\x01\x01B\x15\n" +
	"\x13_serialized_contentB\a\n" +
	"\x05_meta\"u\n" +
	"\n" +
	"EventProof\x12)\n" +
	"\x10target_signature\x18\x01 \x01(\fR\x0ftargetSignature\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x02 \x01(\x04R\tleafIndex\x12\x1d\n" +
	"\n" +
	"audit_path\x18\x03 \x03(\fR\tauditPath\"\xc4\x02\n" +
	"\rEventMetadata\x12$\n" +
	"\vreply_count\x18\x01 \x01(\x05H\x00R\n" +
	"replyCount\x88\x01\x01\x12*\n" +
	"\x0ereaction_count\x18\x02 \x01(\x05H\x01R\rreactionCount\x88\x01\x01\x12&\n" +
	"\fupvote_count\x18\x03 \x01(\x05H\x02R\vupvoteCount\x88\x01\x01\x12*\n" +
	"\x0edownvote_count\x18\x04 \x01(\x05H\x03R\rdownvoteCount\x88\x01\x01\x12F\n" +
	"\x0femoji_reactions\x18\x05 \x03(\v2\x1d.polycentric.v2.ReactionTallyR\x0eemojiReactionsB\x0e\n" +
	"\f_reply_countB\x11\n" +
	"\x0f_reaction_countB\x0f\n" +
	"\r_upvote_countB\x11\n" +
	"\x0f_downvote_count\"W\n" +
	"\rReactionTally\x12\x14\n" +
	"\x05emoji\x18\x01 \x01(\tR\x05emoji\x12\x1a\n" +
	"\bpositive\x18\x02 \x01(\bR\bpositive\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"K\n" +
	"\tEventHint\x12>\n" +
	"\fevent_bundle\x18\x01 \x01(\v2\x1b.polycentric.v2.EventBundleR\veventBundle\"\xdc\x02\n" +
	"\x11ListEventsFilters\x12#\n" +
	"\n" +
	"collection\x18\x01 \x01(\x05H\x00R\n" +
	"collection\x88\x01\x01\x12\x1f\n" +
	"\bidentity\x18\x02 \x01(\tH\x01R\bidentity\x88\x01\x01\x12;\n" +
	"\tsigned_by\x18\x03 \x01(\v2\x19.polycentric.v2.PublicKeyH\x02R\bsignedBy\x88\x01\x01\x12$\n" +
	"\vsequence_gt\x18\x04 \x01(\x03H\x03R\n" +
	"sequenceGt\x88\x01\x01\x12$\n" +
	"\vsequence_lt\x18\x05 \x01(\x03H\x04R\n" +
	"sequenceLt\x88\x01\x01\x12.\n" +
	"\x05heads\x18\x06 \x03(\v2\x18.polycentric.v2.EventKeyR\x05headsB\r\n" +
	"\v_collectionB\v\n" +
	"\t_identityB\f\n" +
	"\n" +
	"_signed_byB\x0e\n" +
	"\f_sequence_gtB\x0e\n" +
	"\f_sequence_lt\"\x83\x01\n" +
	"\x11ListEventsRequest\x12@\n" +
	"\afilters\x18\x01 \x01(\v2!.polycentric.v2.ListEventsFiltersH\x00R\afilters\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x01R\x04size\x88\x01\x01B\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_size\"\x92\x01\n" +
	"\x12ListEventsResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"T\n" +
	"\x10PutEventsRequest\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\"W\n" +
	"\rPutEventError\x12,\n" +
	"\x12event_bundle_index\x18\x01 \x01(\rR\x10eventBundleIndex\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x01\n" +
	"\x11PutEventsResponse\x125\n" +
	"\x06errors\x18\x01 \x03(\v2\x1d.polycentric.v2.PutEventErrorR\x06errors\x12=\n" +
	"\x0frequested_blobs\x18\x02 \x03(\v2\x14.polycentric.v2.BlobR\x0erequestedBlobs\".\n" +
	"\x10ListHeadsRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"C\n" +
	"\x11ListHeadsResponse\x12.\n" +
	"\x05heads\x18\x01 \x03(\v2\x18.polycentric.v2.EventKeyR\x05heads\"\xd2\x01\n" +
	"\x13GetReactionsRequest\x120\n" +
	"\x06target\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\x06target\x12&\n" +
	"\femoji_filter\x18\x02 \x01(\tH\x00R\vemojiFilter\x88\x01\x01\x12@\n" +
	"\vpage_params\x18\x03 \x01(\v2\x1a.polycentric.v2.PageParamsH\x01R\n" +
	"pageParams\x88\x01\x01B\x0f\n" +
	"\r_emoji_filterB\x0e\n" +
	"\f_page_params\"\xde\x01\n" +
	"\x14GetReactionsResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\x12:\n" +
	"\tpage_info\x18\x03 \x01(\v2\x18.polycentric.v2.PageInfoH\x00R\bpageInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_page_info\"i\n" +
	"$GetAttributedToReactionCountsRequest\x12A\n" +
	"\rattributed_to\x18\x01 \x01(\v2\x1c.polycentric.v2.AttributedToR\fattributedTo\"q\n" +
	"%GetAttributedToReactionCountsResponse\x12!\n" +
	"\fupvote_count\x18\x01 \x01(\x03R\vupvoteCount\x12%\n" +
	"\x0edownvote_count\x18\x02 \x01(\x03R\rdownvoteCount2\xf5\x03\n" +
	"\x10EventSyncService\x12S\n" +
	"\n" +
	"ListEvents\x12!.polycentric.v2.ListEventsRequest\x1a\".polycentric.v2.ListEventsResponse\x12P\n" +
	"\tPutEvents\x12 .polycentric.v2.PutEventsRequest\x1a!.polycentric.v2.PutEventsResponse\x12P\n" +
	"\tListHeads\x12 .polycentric.v2.ListHeadsRequest\x1a!.polycentric.v2.ListHeadsResponse\x12Y\n" +
	"\fGetReactions\x12#.polycentric.v2.GetReactionsRequest\x1a$.polycentric.v2.GetReactionsResponse\x12\x8c\x01\n" +
	"\x1dGetAttributedToReactionCounts\x124.polycentric.v2.GetAttributedToReactionCountsRequest\x1a5.polycentric.v2.GetAttributedToReactionCountsResponseB\xcd\x01\n" +
	"\x12com.polycentric.v2B\vEventsProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_events_proto_rawDescOnce sync.Once
	file_polycentric_v2_events_proto_rawDescData []byte
)

func file_polycentric_v2_events_proto_rawDescGZIP() []byte {
	file_polycentric_v2_events_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_events_proto_rawDesc), len(file_polycentric_v2_events_proto_rawDesc)))
	})
	return file_polycentric_v2_events_proto_rawDescData
}

var file_polycentric_v2_events_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_polycentric_v2_events_proto_goTypes = []any{
	(*VectorClock)(nil),                           // 0: polycentric.v2.VectorClock
	(*Application)(nil),                           // 1: polycentric.v2.Application
	(*Event)(nil),                                 // 2: polycentric.v2.Event
	(*SignedEvent)(nil),                           // 3: polycentric.v2.SignedEvent
	(*EventBundle)(nil),                           // 4: polycentric.v2.EventBundle
	(*EventProof)(nil),                            // 5: polycentric.v2.EventProof
	(*EventMetadata)(nil),                         // 6: polycentric.v2.EventMetadata
	(*ReactionTally)(nil),                         // 7: polycentric.v2.ReactionTally
	(*EventHint)(nil),                             // 8: polycentric.v2.EventHint
	(*ListEventsFilters)(nil),                     // 9: polycentric.v2.ListEventsFilters
	(*ListEventsRequest)(nil),                     // 10: polycentric.v2.ListEventsRequest
	(*ListEventsResponse)(nil),                    // 11: polycentric.v2.ListEventsResponse
	(*PutEventsRequest)(nil),                      // 12: polycentric.v2.PutEventsRequest
	(*PutEventError)(nil),                         // 13: polycentric.v2.PutEventError
	(*PutEventsResponse)(nil),                     // 14: polycentric.v2.PutEventsResponse
	(*ListHeadsRequest)(nil),                      // 15: polycentric.v2.ListHeadsRequest
	(*ListHeadsResponse)(nil),                     // 16: polycentric.v2.ListHeadsResponse
	(*GetReactionsRequest)(nil),                   // 17: polycentric.v2.GetReactionsRequest
	(*GetReactionsResponse)(nil),                  // 18: polycentric.v2.GetReactionsResponse
	(*GetAttributedToReactionCountsRequest)(nil),  // 19: polycentric.v2.GetAttributedToReactionCountsRequest
	(*GetAttributedToReactionCountsResponse)(nil), // 20: polycentric.v2.GetAttributedToReactionCountsResponse
	(*EventKey)(nil),                              // 21: polycentric.v2.EventKey
	(*ContentDigest)(nil),                         // 22: polycentric.v2.ContentDigest
	(*SerializedContent)(nil),                     // 23: polycentric.v2.SerializedContent
	(*PublicKey)(nil),                             // 24: polycentric.v2.PublicKey
	(*Blob)(nil),                                  // 25: polycentric.v2.Blob
	(*PageParams)(nil),                            // 26: polycentric.v2.PageParams
	(*PageInfo)(nil),                              // 27: polycentric.v2.PageInfo
	(*AttributedTo)(nil),                          // 28: polycentric.v2.AttributedTo
}
var file_polycentric_v2_events_proto_depIdxs = []int32{
	21, // 0: polycentric.v2.Event.key:type_name -> polycentric.v2.EventKey
	0,  // 1: polycentric.v2.Event.vector_clock:type_name -> polycentric.v2.VectorClock
	22, // 2: polycentric.v2.Event.content_digest:type_name -> polycentric.v2.ContentDigest
	1,  // 3: polycentric.v2.Event.application:type_name -> polycentric.v2.Application
	3,  // 4: polycentric.v2.EventBundle.signed_event:type_name -> polycentric.v2.SignedEvent
	23, // 5: polycentric.v2.EventBundle.serialized_content:type_name -> polycentric.v2.SerializedContent
	5,  // 6: polycentric.v2.EventBundle.event_proofs:type_name -> polycentric.v2.EventProof
	6,  // 7: polycentric.v2.EventBundle.meta:type_name -> polycentric.v2.EventMetadata
	7,  // 8: polycentric.v2.EventMetadata.emoji_reactions:type_name -> polycentric.v2.ReactionTally
	4,  // 9: polycentric.v2.EventHint.event_bundle:type_name -> polycentric.v2.EventBundle
	24, // 10: polycentric.v2.ListEventsFilters.signed_by:type_name -> polycentric.v2.PublicKey
	21, // 11: polycentric.v2.ListEventsFilters.heads:type_name -> polycentric.v2.EventKey
	9,  // 12: polycentric.v2.ListEventsRequest.filters:type_name -> polycentric.v2.ListEventsFilters
	4,  // 13: polycentric.v2.ListEventsResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	8,  // 14: polycentric.v2.ListEventsResponse.event_hints:type_name -> polycentric.v2.EventHint
	4,  // 15: polycentric.v2.PutEventsRequest.event_bundles:type_name -> polycentric.v2.EventBundle
	13, // 16: polycentric.v2.PutEventsResponse.errors:type_name -> polycentric.v2.PutEventError
	25, // 17: polycentric.v2.PutEventsResponse.requested_blobs:type_name -> polycentric.v2.Blob
	21, // 18: polycentric.v2.ListHeadsResponse.heads:type_name -> polycentric.v2.EventKey
	21, // 19: polycentric.v2.GetReactionsRequest.target:type_name -> polycentric.v2.EventKey
	26, // 20: polycentric.v2.GetReactionsRequest.page_params:type_name -> polycentric.v2.PageParams
	4,  // 21: polycentric.v2.GetReactionsResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	8,  // 22: polycentric.v2.GetReactionsResponse.event_hints:type_name -> polycentric.v2.EventHint
	27, // 23: polycentric.v2.GetReactionsResponse.page_info:type_name -> polycentric.v2.PageInfo
	28, // 24: polycentric.v2.GetAttributedToReactionCountsRequest.attributed_to:type_name -> polycentric.v2.AttributedTo
	10, // 25: polycentric.v2.EventSyncService.ListEvents:input_type -> polycentric.v2.ListEventsRequest
	12, // 26: polycentric.v2.EventSyncService.PutEvents:input_type -> polycentric.v2.PutEventsRequest
	15, // 27: polycentric.v2.EventSyncService.ListHeads:input_type -> polycentric.v2.ListHeadsRequest
	17, // 28: polycentric.v2.EventSyncService.GetReactions:input_type -> polycentric.v2.GetReactionsRequest
	19, // 29: polycentric.v2.EventSyncService.GetAttributedToReactionCounts:input_type -> polycentric.v2.GetAttributedToReactionCountsRequest
	11, // 30: polycentric.v2.EventSyncService.ListEvents:output_type -> polycentric.v2.ListEventsResponse
	14, // 31: polycentric.v2.EventSyncService.PutEvents:output_type -> polycentric.v2.PutEventsResponse
	16, // 32: polycentric.v2.EventSyncService.ListHeads:output_type -> polycentric.v2.ListHeadsResponse
	18, // 33: polycentric.v2.EventSyncService.GetReactions:output_type -> polycentric.v2.GetReactionsResponse
	20, // 34: polycentric.v2.EventSyncService.GetAttributedToReactionCounts:output_type -> polycentric.v2.GetAttributedToReactionCountsResponse
	30, // [30:35] is the sub-list for method output_type
	25, // [25:30] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_polycentric_v2_events_proto_init() }
func file_polycentric_v2_events_proto_init() {
	if File_polycentric_v2_events_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_content_proto_init()
	file_polycentric_v2_event_key_proto_init()
	file_polycentric_v2_keypair_proto_init()
	file_polycentric_v2_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_polycentric_v2_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_polycentric_v2_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_polycentric_v2_events_proto_msgTypes[9].OneofWrappers = []any{}
	file_polycentric_v2_events_proto_msgTypes[10].OneofWrappers = []any{}
	file_polycentric_v2_events_proto_msgTypes[17].OneofWrappers = []any{}
	file_polycentric_v2_events_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_events_proto_rawDesc), len(file_polycentric_v2_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_events_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_events_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_events_proto_msgTypes,
	}.Build()
	File_polycentric_v2_events_proto = out.File
	file_polycentric_v2_events_proto_goTypes = nil
	file_polycentric_v2_events_proto_depIdxs = nil
}
