// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/event_key.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventKey's are the unique identitifiers of Events
type EventKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collection of the stream the event is connected with
	// Reserved collections are:
	// 1 -> Polycentric Identity
	// 2 -> Polycentric feed
	// 3 -> Polycentric profile
	// 4 -> Polycentric interactions (likes etc)
	// 5 -> Polycentric social graph (follows)
	// 6 -> Polycentric reports
	// 7 -> Polycentric labels
	// 8 -> Polycentric verifications
	Collection int32 `protobuf:"varint,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// Identity Key (sha256 hash of the initial Identity content)
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// Public key that signed the event
	SignedBy *PublicKey `protobuf:"bytes,3,opt,name=signed_by,json=signedBy,proto3" json:"signed_by,omitempty"`
	// Sequence number of the event in the collection (our logical clock)
	Sequence      uint64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventKey) Reset() {
	*x = EventKey{}
	mi := &file_polycentric_v2_event_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventKey) ProtoMessage() {}

func (x *EventKey) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_event_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventKey.ProtoReflect.Descriptor instead.
func (*EventKey) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_event_key_proto_rawDescGZIP(), []int{0}
}

func (x *EventKey) GetCollection() int32 {
	if x != nil {
		return x.Collection
	}
	return 0
}

func (x *EventKey) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *EventKey) GetSignedBy() *PublicKey {
	if x != nil {
		return x.SignedBy
	}
	return nil
}

func (x *EventKey) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_polycentric_v2_event_key_proto protoreflect.FileDescriptor

const file_polycentric_v2_event_key_proto_rawDesc = "" +
	"\n" +
	"\x1epolycentric/v2/event_key.proto\x12\x0epolycentric.v2\x1a\x1cpolycentric/v2/keypair.proto\"\x9a\x01\n" +
	"\bEventKey\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\x05R\n" +
	"collection\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x126\n" +
	"\tsigned_by\x18\x03 \x01(\v2\x19.polycentric.v2.PublicKeyR\bsignedBy\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequenceB\xcf\x01\n" +
	"\x12com.polycentric.v2B\rEventKeyProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_event_key_proto_rawDescOnce sync.Once
	file_polycentric_v2_event_key_proto_rawDescData []byte
)

func file_polycentric_v2_event_key_proto_rawDescGZIP() []byte {
	file_polycentric_v2_event_key_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_event_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_event_key_proto_rawDesc), len(file_polycentric_v2_event_key_proto_rawDesc)))
	})
	return file_polycentric_v2_event_key_proto_rawDescData
}

var file_polycentric_v2_event_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_polycentric_v2_event_key_proto_goTypes = []any{
	(*EventKey)(nil),  // 0: polycentric.v2.EventKey
	(*PublicKey)(nil), // 1: polycentric.v2.PublicKey
}
var file_polycentric_v2_event_key_proto_depIdxs = []int32{
	1, // 0: polycentric.v2.EventKey.signed_by:type_name -> polycentric.v2.PublicKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_polycentric_v2_event_key_proto_init() }
func file_polycentric_v2_event_key_proto_init() {
	if File_polycentric_v2_event_key_proto != nil {
		return
	}
	file_polycentric_v2_keypair_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_event_key_proto_rawDesc), len(file_polycentric_v2_event_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycentric_v2_event_key_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_event_key_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_event_key_proto_msgTypes,
	}.Build()
	File_polycentric_v2_event_key_proto = out.File
	file_polycentric_v2_event_key_proto_goTypes = nil
	file_polycentric_v2_event_key_proto_depIdxs = nil
}
