// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/feeds.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedAlgorithm int32

const (
	FeedAlgorithm_FEED_ALGORITHM_UNSPECIFIED FeedAlgorithm = 0
	FeedAlgorithm_FEED_ALGORITHM_FOLLOWING   FeedAlgorithm = 1
	FeedAlgorithm_FEED_ALGORITHM_SUGGESTED   FeedAlgorithm = 2
)

// Enum value maps for FeedAlgorithm.
var (
	FeedAlgorithm_name = map[int32]string{
		0: "FEED_ALGORITHM_UNSPECIFIED",
		1: "FEED_ALGORITHM_FOLLOWING",
		2: "FEED_ALGORITHM_SUGGESTED",
	}
	FeedAlgorithm_value = map[string]int32{
		"FEED_ALGORITHM_UNSPECIFIED": 0,
		"FEED_ALGORITHM_FOLLOWING":   1,
		"FEED_ALGORITHM_SUGGESTED":   2,
	}
)

func (x FeedAlgorithm) Enum() *FeedAlgorithm {
	p := new(FeedAlgorithm)
	*p = x
	return p
}

func (x FeedAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_feeds_proto_enumTypes[0].Descriptor()
}

func (FeedAlgorithm) Type() protoreflect.EnumType {
	return &file_polycentric_v2_feeds_proto_enumTypes[0]
}

func (x FeedAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedAlgorithm.Descriptor instead.
func (FeedAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{0}
}

type GetIdentityFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity to return the posts of
	Identity   string      `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	PageParams *PageParams `protobuf:"bytes,2,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	// Label values for which the requester does not want to see content
	OmitLabels    []string `protobuf:"bytes,3,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityFeedRequest) Reset() {
	*x = GetIdentityFeedRequest{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityFeedRequest) ProtoMessage() {}

func (x *GetIdentityFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityFeedRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityFeedRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{0}
}

func (x *GetIdentityFeedRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetIdentityFeedRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

func (x *GetIdentityFeedRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

type GetFollowingFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the follower to return the feed for
	FollowerIdentity string      `protobuf:"bytes,1,opt,name=follower_identity,json=followerIdentity,proto3" json:"follower_identity,omitempty"`
	PageParams       *PageParams `protobuf:"bytes,2,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	// Label values for which the requester does not want to see content
	OmitLabels    []string     `protobuf:"bytes,3,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	SortBy        *SortPostsBy `protobuf:"varint,4,opt,name=sort_by,json=sortBy,proto3,enum=polycentric.v2.SortPostsBy,oneof" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingFeedRequest) Reset() {
	*x = GetFollowingFeedRequest{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingFeedRequest) ProtoMessage() {}

func (x *GetFollowingFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingFeedRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingFeedRequest) GetFollowerIdentity() string {
	if x != nil {
		return x.FollowerIdentity
	}
	return ""
}

func (x *GetFollowingFeedRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

func (x *GetFollowingFeedRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

func (x *GetFollowingFeedRequest) GetSortBy() SortPostsBy {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return SortPostsBy_SORT_POSTS_BY_DEFAULT
}

type GetExploreFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the caller to return relevant posts for
	Identity   *string     `protobuf:"bytes,1,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
	PageParams *PageParams `protobuf:"bytes,2,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	// Label values for which the requester does not want to see content
	OmitLabels    []string     `protobuf:"bytes,3,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	SortBy        *SortPostsBy `protobuf:"varint,4,opt,name=sort_by,json=sortBy,proto3,enum=polycentric.v2.SortPostsBy,oneof" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExploreFeedRequest) Reset() {
	*x = GetExploreFeedRequest{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExploreFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExploreFeedRequest) ProtoMessage() {}

func (x *GetExploreFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExploreFeedRequest.ProtoReflect.Descriptor instead.
func (*GetExploreFeedRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{2}
}

func (x *GetExploreFeedRequest) GetIdentity() string {
	if x != nil && x.Identity != nil {
		return *x.Identity
	}
	return ""
}

func (x *GetExploreFeedRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

func (x *GetExploreFeedRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

func (x *GetExploreFeedRequest) GetSortBy() SortPostsBy {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return SortPostsBy_SORT_POSTS_BY_DEFAULT
}

type GetFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBundles  []*EventBundle         `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	EventHints    []*EventHint           `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3,oneof" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *GetFeedResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

func (x *GetFeedResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetPostThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        []*EventBundle         `protobuf:"bytes,1,rep,name=thread,proto3" json:"thread,omitempty"`
	EventHints    []*EventHint           `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostThreadResponse) Reset() {
	*x = GetPostThreadResponse{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostThreadResponse) ProtoMessage() {}

func (x *GetPostThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostThreadResponse.ProtoReflect.Descriptor instead.
func (*GetPostThreadResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostThreadResponse) GetThread() []*EventBundle {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *GetPostThreadResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

// Request candidate posts matching these filters.
type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OmitLabels    []string               `protobuf:"bytes,3,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetPostRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GetPostRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

// All candidate post events matching the request's filter.
type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*EventBundle         `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	EventHints    []*EventHint           `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostResponse) GetCandidates() []*EventBundle {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GetPostResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type GetPostThreadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent post to return the thread for
	EventKey *EventKey `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	Limit    int32     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Label values for which the requester does not want to see content
	OmitLabels    []string `protobuf:"bytes,3,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostThreadRequest) Reset() {
	*x = GetPostThreadRequest{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostThreadRequest) ProtoMessage() {}

func (x *GetPostThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostThreadRequest.ProtoReflect.Descriptor instead.
func (*GetPostThreadRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostThreadRequest) GetEventKey() *EventKey {
	if x != nil {
		return x.EventKey
	}
	return nil
}

func (x *GetPostThreadRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPostThreadRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

type GetAttributionFeedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribution to match posts against. A post is included when any of
	// its `attributed_to` entries is similar to this one — for a link,
	// similar means the same URL, ignoring other Link metadata.
	AttributedTo *AttributedTo `protobuf:"bytes,1,opt,name=attributed_to,json=attributedTo,proto3" json:"attributed_to,omitempty"`
	PageParams   *PageParams   `protobuf:"bytes,2,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	// Label values for which the requester does not want to see content
	OmitLabels    []string `protobuf:"bytes,3,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributionFeedRequest) Reset() {
	*x = GetAttributionFeedRequest{}
	mi := &file_polycentric_v2_feeds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributionFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributionFeedRequest) ProtoMessage() {}

func (x *GetAttributionFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_feeds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributionFeedRequest.ProtoReflect.Descriptor instead.
func (*GetAttributionFeedRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_feeds_proto_rawDescGZIP(), []int{8}
}

func (x *GetAttributionFeedRequest) GetAttributedTo() *AttributedTo {
	if x != nil {
		return x.AttributedTo
	}
	return nil
}

func (x *GetAttributionFeedRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

func (x *GetAttributionFeedRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

var File_polycentric_v2_feeds_proto protoreflect.FileDescriptor

const file_polycentric_v2_feeds_proto_rawDesc = "" +
	"\n" +
	"\x1apolycentric/v2/feeds.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1bpolycentric/v2/search.proto\x1a\x1cpolycentric/v2/content.proto\x1a\x1epolycentric/v2/event_key.proto\x1a\x1bpolycentric/v2/events.proto\"\xa7\x01\n" +
	"\x16GetIdentityFeedRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12@\n" +
	"\vpage_params\x18\x02 \x01(\v2\x1a.polycentric.v2.PageParamsH\x00R\n" +
	"pageParams\x88\x01\x01\x12\x1f\n" +
	"\vomit_labels\x18\x03 \x03(\tR\n" +
	"omitLabelsB\x0e\n" +
	"\f_page_params\"\x80\x02\n" +
	"\x17GetFollowingFeedRequest\x12+\n" +
	"\x11follower_identity\x18\x01 \x01(\tR\x10followerIdentity\x12@\n" +
	"\vpage_params\x18\x02 \x01(\v2\x1a.polycentric.v2.PageParamsH\x00R\n" +
	"pageParams\x88\x01\x01\x12\x1f\n" +
	"\vomit_labels\x18\x03 \x03(\tR\n" +
	"omitLabels\x129\n" +
	"\asort_by\x18\x04 \x01(\x0e2\x1b.polycentric.v2.SortPostsByH\x01R\x06sortBy\x88\x01\x01B\x0e\n" +
	"\f_page_paramsB\n" +
	"\n" +
	"\b_sort_by\"\xff\x01\n" +
	"\x15GetExploreFeedRequest\x12\x1f\n" +
	"\bidentity\x18\x01 \x01(\tH\x00R\bidentity\x88\x01\x01\x12@\n" +
	"\vpage_params\x18\x02 \x01(\v2\x1a.polycentric.v2.PageParamsH\x01R\n" +
	"pageParams\x88\x01\x01\x12\x1f\n" +
	"\vomit_labels\x18\x03 \x03(\tR\n" +
	"omitLabels\x129\n" +
	"\asort_by\x18\x04 \x01(\x0e2\x1b.polycentric.v2.SortPostsByH\x02R\x06sortBy\x88\x01\x01B\v\n" +
	"\t_identityB\x0e\n" +
	"\f_page_paramsB\n" +
	"\n" +
	"\b_sort_by\"\xd9\x01\n" +
	"\x0fGetFeedResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\x12:\n" +
	"\tpage_info\x18\x03 \x01(\v2\x18.polycentric.v2.PageInfoH\x00R\bpageInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_page_info\"\x88\x01\n" +
	"\x15GetPostThreadResponse\x123\n" +
	"\x06thread\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\x06thread\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"i\n" +
	"\x0eGetPostRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vomit_labels\x18\x03 \x03(\tR\n" +
	"omitLabels\"\x8a\x01\n" +
	"\x0fGetPostResponse\x12;\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\n" +
	"candidates\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"\x84\x01\n" +
	"\x14GetPostThreadRequest\x125\n" +
	"\tevent_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\beventKey\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vomit_labels\x18\x03 \x03(\tR\n" +
	"omitLabels\"\xd1\x01\n" +
	"\x19GetAttributionFeedRequest\x12A\n" +
	"\rattributed_to\x18\x01 \x01(\v2\x1c.polycentric.v2.AttributedToR\fattributedTo\x12@\n" +
	"\vpage_params\x18\x02 \x01(\v2\x1a.polycentric.v2.PageParamsH\x00R\n" +
	"pageParams\x88\x01\x01\x12\x1f\n" +
	"\vomit_labels\x18\x03 \x03(\tR\n" +
	"omitLabelsB\x0e\n" +
	"\f_page_params*k\n" +
	"\rFeedAlgorithm\x12\x1e\n" +
	"\x1aFEED_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FEED_ALGORITHM_FOLLOWING\x10\x01\x12\x1c\n" +
	"\x18FEED_ALGORITHM_SUGGESTED\x10\x022\x8e\x05\n" +
	"\fFeedsService\x12Z\n" +
	"\x0fGetIdentityFeed\x12&.polycentric.v2.GetIdentityFeedRequest\x1a\x1f.polycentric.v2.GetFeedResponse\x12\\\n" +
	"\x10GetFollowingFeed\x12'.polycentric.v2.GetFollowingFeedRequest\x1a\x1f.polycentric.v2.GetFeedResponse\x12^\n" +
	"\x12GetRecommendedFeed\x12'.polycentric.v2.GetFollowingFeedRequest\x1a\x1f.polycentric.v2.GetFeedResponse\x12X\n" +
	"\x0eGetExploreFeed\x12%.polycentric.v2.GetExploreFeedRequest\x1a\x1f.polycentric.v2.GetFeedResponse\x12J\n" +
	"\aGetPost\x12\x1e.polycentric.v2.GetPostRequest\x1a\x1f.polycentric.v2.GetPostResponse\x12\\\n" +
	"\rGetPostThread\x12$.polycentric.v2.GetPostThreadRequest\x1a%.polycentric.v2.GetPostThreadResponse\x12`\n" +
	"\x12GetAttributionFeed\x12).polycentric.v2.GetAttributionFeedRequest\x1a\x1f.polycentric.v2.GetFeedResponseB\xcc\x01\n" +
	"\x12com.polycentric.v2B\n" +
	"FeedsProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_feeds_proto_rawDescOnce sync.Once
	file_polycentric_v2_feeds_proto_rawDescData []byte
)

func file_polycentric_v2_feeds_proto_rawDescGZIP() []byte {
	file_polycentric_v2_feeds_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_feeds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_feeds_proto_rawDesc), len(file_polycentric_v2_feeds_proto_rawDesc)))
	})
	return file_polycentric_v2_feeds_proto_rawDescData
}

var file_polycentric_v2_feeds_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polycentric_v2_feeds_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_polycentric_v2_feeds_proto_goTypes = []any{
	(FeedAlgorithm)(0),                // 0: polycentric.v2.FeedAlgorithm
	(*GetIdentityFeedRequest)(nil),    // 1: polycentric.v2.GetIdentityFeedRequest
	(*GetFollowingFeedRequest)(nil),   // 2: polycentric.v2.GetFollowingFeedRequest
	(*GetExploreFeedRequest)(nil),     // 3: polycentric.v2.GetExploreFeedRequest
	(*GetFeedResponse)(nil),           // 4: polycentric.v2.GetFeedResponse
	(*GetPostThreadResponse)(nil),     // 5: polycentric.v2.GetPostThreadResponse
	(*GetPostRequest)(nil),            // 6: polycentric.v2.GetPostRequest
	(*GetPostResponse)(nil),           // 7: polycentric.v2.GetPostResponse
	(*GetPostThreadRequest)(nil),      // 8: polycentric.v2.GetPostThreadRequest
	(*GetAttributionFeedRequest)(nil), // 9: polycentric.v2.GetAttributionFeedRequest
	(*PageParams)(nil),                // 10: polycentric.v2.PageParams
	(SortPostsBy)(0),                  // 11: polycentric.v2.SortPostsBy
	(*EventBundle)(nil),               // 12: polycentric.v2.EventBundle
	(*EventHint)(nil),                 // 13: polycentric.v2.EventHint
	(*PageInfo)(nil),                  // 14: polycentric.v2.PageInfo
	(*EventKey)(nil),                  // 15: polycentric.v2.EventKey
	(*AttributedTo)(nil),              // 16: polycentric.v2.AttributedTo
}
var file_polycentric_v2_feeds_proto_depIdxs = []int32{
	10, // 0: polycentric.v2.GetIdentityFeedRequest.page_params:type_name -> polycentric.v2.PageParams
	10, // 1: polycentric.v2.GetFollowingFeedRequest.page_params:type_name -> polycentric.v2.PageParams
	11, // 2: polycentric.v2.GetFollowingFeedRequest.sort_by:type_name -> polycentric.v2.SortPostsBy
	10, // 3: polycentric.v2.GetExploreFeedRequest.page_params:type_name -> polycentric.v2.PageParams
	11, // 4: polycentric.v2.GetExploreFeedRequest.sort_by:type_name -> polycentric.v2.SortPostsBy
	12, // 5: polycentric.v2.GetFeedResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	13, // 6: polycentric.v2.GetFeedResponse.event_hints:type_name -> polycentric.v2.EventHint
	14, // 7: polycentric.v2.GetFeedResponse.page_info:type_name -> polycentric.v2.PageInfo
	12, // 8: polycentric.v2.GetPostThreadResponse.thread:type_name -> polycentric.v2.EventBundle
	13, // 9: polycentric.v2.GetPostThreadResponse.event_hints:type_name -> polycentric.v2.EventHint
	12, // 10: polycentric.v2.GetPostResponse.candidates:type_name -> polycentric.v2.EventBundle
	13, // 11: polycentric.v2.GetPostResponse.event_hints:type_name -> polycentric.v2.EventHint
	15, // 12: polycentric.v2.GetPostThreadRequest.event_key:type_name -> polycentric.v2.EventKey
	16, // 13: polycentric.v2.GetAttributionFeedRequest.attributed_to:type_name -> polycentric.v2.AttributedTo
	10, // 14: polycentric.v2.GetAttributionFeedRequest.page_params:type_name -> polycentric.v2.PageParams
	1,  // 15: polycentric.v2.FeedsService.GetIdentityFeed:input_type -> polycentric.v2.GetIdentityFeedRequest
	2,  // 16: polycentric.v2.FeedsService.GetFollowingFeed:input_type -> polycentric.v2.GetFollowingFeedRequest
	2,  // 17: polycentric.v2.FeedsService.GetRecommendedFeed:input_type -> polycentric.v2.GetFollowingFeedRequest
	3,  // 18: polycentric.v2.FeedsService.GetExploreFeed:input_type -> polycentric.v2.GetExploreFeedRequest
	6,  // 19: polycentric.v2.FeedsService.GetPost:input_type -> polycentric.v2.GetPostRequest
	8,  // 20: polycentric.v2.FeedsService.GetPostThread:input_type -> polycentric.v2.GetPostThreadRequest
	9,  // 21: polycentric.v2.FeedsService.GetAttributionFeed:input_type -> polycentric.v2.GetAttributionFeedRequest
	4,  // 22: polycentric.v2.FeedsService.GetIdentityFeed:output_type -> polycentric.v2.GetFeedResponse
	4,  // 23: polycentric.v2.FeedsService.GetFollowingFeed:output_type -> polycentric.v2.GetFeedResponse
	4,  // 24: polycentric.v2.FeedsService.GetRecommendedFeed:output_type -> polycentric.v2.GetFeedResponse
	4,  // 25: polycentric.v2.FeedsService.GetExploreFeed:output_type -> polycentric.v2.GetFeedResponse
	7,  // 26: polycentric.v2.FeedsService.GetPost:output_type -> polycentric.v2.GetPostResponse
	5,  // 27: polycentric.v2.FeedsService.GetPostThread:output_type -> polycentric.v2.GetPostThreadResponse
	4,  // 28: polycentric.v2.FeedsService.GetAttributionFeed:output_type -> polycentric.v2.GetFeedResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_polycentric_v2_feeds_proto_init() }
func file_polycentric_v2_feeds_proto_init() {
	if File_polycentric_v2_feeds_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_search_proto_init()
	file_polycentric_v2_content_proto_init()
	file_polycentric_v2_event_key_proto_init()
	file_polycentric_v2_events_proto_init()
	file_polycentric_v2_feeds_proto_msgTypes[0].OneofWrappers = []any{}
	file_polycentric_v2_feeds_proto_msgTypes[1].OneofWrappers = []any{}
	file_polycentric_v2_feeds_proto_msgTypes[2].OneofWrappers = []any{}
	file_polycentric_v2_feeds_proto_msgTypes[3].OneofWrappers = []any{}
	file_polycentric_v2_feeds_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_feeds_proto_rawDesc), len(file_polycentric_v2_feeds_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_feeds_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_feeds_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_feeds_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_feeds_proto_msgTypes,
	}.Build()
	File_polycentric_v2_feeds_proto = out.File
	file_polycentric_v2_feeds_proto_goTypes = nil
	file_polycentric_v2_feeds_proto_depIdxs = nil
}
