// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/graph_service.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFollowingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity whose followed identities are returned.
	Identity      string      `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	PageParams    *PageParams `protobuf:"bytes,2,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingRequest) Reset() {
	*x = ListFollowingRequest{}
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingRequest) ProtoMessage() {}

func (x *ListFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_graph_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListFollowingRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ListFollowingRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

type ListFollowersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity whose followers are returned.
	Identity      string      `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	PageParams    *PageParams `protobuf:"bytes,2,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersRequest) Reset() {
	*x = ListFollowersRequest{}
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersRequest) ProtoMessage() {}

func (x *ListFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListFollowersRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_graph_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFollowersRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ListFollowersRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

type SuggestFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageParams    *PageParams            `protobuf:"bytes,1,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestFollowRequest) Reset() {
	*x = SuggestFollowRequest{}
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestFollowRequest) ProtoMessage() {}

func (x *SuggestFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestFollowRequest.ProtoReflect.Descriptor instead.
func (*SuggestFollowRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_graph_service_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestFollowRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

type ListFollowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The active (non-tombstoned) Follow events, newest first.
	EventBundles []*EventBundle `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	PageInfo     *PageInfo      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3,oneof" json:"page_info,omitempty"`
	// Relevant events for the users in the follow events
	EventHints    []*EventHint `protobuf:"bytes,3,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowsResponse) Reset() {
	*x = ListFollowsResponse{}
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowsResponse) ProtoMessage() {}

func (x *ListFollowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowsResponse.ProtoReflect.Descriptor instead.
func (*ListFollowsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_graph_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListFollowsResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *ListFollowsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListFollowsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type SuggestFollowResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Suggestions []*FollowSuggestion    `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	PageInfo    *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3,oneof" json:"page_info,omitempty"`
	// Contains profile update events for the suggested to-follow identities
	// (`FollowSuggestion.suggestion`). Note that the identity events for the
	// to-follow identities can be found in the suggestions.
	//
	// Also contains identity, profile update and follow events for the suggested
	// the identities of those who already follow those identities
	// (`FollowSuggestion.followers`).
	EventHints    []*EventHint `protobuf:"bytes,3,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestFollowResponse) Reset() {
	*x = SuggestFollowResponse{}
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestFollowResponse) ProtoMessage() {}

func (x *SuggestFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestFollowResponse.ProtoReflect.Descriptor instead.
func (*SuggestFollowResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_graph_service_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestFollowResponse) GetSuggestions() []*FollowSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *SuggestFollowResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *SuggestFollowResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type FollowSuggestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity (event) to follow.
	Suggestion *EventBundle `protobuf:"bytes,1,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	// Identities that are following the suggested identity.
	Followers     []string `protobuf:"bytes,2,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowSuggestion) Reset() {
	*x = FollowSuggestion{}
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowSuggestion) ProtoMessage() {}

func (x *FollowSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_graph_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowSuggestion.ProtoReflect.Descriptor instead.
func (*FollowSuggestion) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_graph_service_proto_rawDescGZIP(), []int{5}
}

func (x *FollowSuggestion) GetSuggestion() *EventBundle {
	if x != nil {
		return x.Suggestion
	}
	return nil
}

func (x *FollowSuggestion) GetFollowers() []string {
	if x != nil {
		return x.Followers
	}
	return nil
}

var File_polycentric_v2_graph_service_proto protoreflect.FileDescriptor

const file_polycentric_v2_graph_service_proto_rawDesc = "" +
	"\n" +
	"\"polycentric/v2/graph_service.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1bpolycentric/v2/events.proto\"\x84\x01\n" +
	"\x14ListFollowingRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12@\n" +
	"\vpage_params\x18\x02 \x01(\v2\x1a.polycentric.v2.PageParamsH\x00R\n" +
	"pageParams\x88\x01\x01B\x0e\n" +
	"\f_page_params\"\x84\x01\n" +
	"\x14ListFollowersRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12@\n" +
	"\vpage_params\x18\x02 \x01(\v2\x1a.polycentric.v2.PageParamsH\x00R\n" +
	"pageParams\x88\x01\x01B\x0e\n" +
	"\f_page_params\"h\n" +
	"\x14SuggestFollowRequest\x12@\n" +
	"\vpage_params\x18\x01 \x01(\v2\x1a.polycentric.v2.PageParamsH\x00R\n" +
	"pageParams\x88\x01\x01B\x0e\n" +
	"\f_page_params\"\xdd\x01\n" +
	"\x13ListFollowsResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.polycentric.v2.PageInfoH\x00R\bpageInfo\x88\x01\x01\x12:\n" +
	"\vevent_hints\x18\x03 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHintsB\f\n" +
	"\n" +
	"_page_info\"\xe1\x01\n" +
	"\x15SuggestFollowResponse\x12B\n" +
	"\vsuggestions\x18\x01 \x03(\v2 .polycentric.v2.FollowSuggestionR\vsuggestions\x12:\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.polycentric.v2.PageInfoH\x00R\bpageInfo\x88\x01\x01\x12:\n" +
	"\vevent_hints\x18\x03 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHintsB\f\n" +
	"\n" +
	"_page_info\"m\n" +
	"\x10FollowSuggestion\x12;\n" +
	"\n" +
	"suggestion\x18\x01 \x01(\v2\x1b.polycentric.v2.EventBundleR\n" +
	"suggestion\x12\x1c\n" +
	"\tfollowers\x18\x02 \x03(\tR\tfollowers2\xa4\x02\n" +
	"\fGraphService\x12Z\n" +
	"\rListFollowing\x12$.polycentric.v2.ListFollowingRequest\x1a#.polycentric.v2.ListFollowsResponse\x12Z\n" +
	"\rListFollowers\x12$.polycentric.v2.ListFollowersRequest\x1a#.polycentric.v2.ListFollowsResponse\x12\\\n" +
	"\rSuggestFollow\x12$.polycentric.v2.SuggestFollowRequest\x1a%.polycentric.v2.SuggestFollowResponseB\xd3\x01\n" +
	"\x12com.polycentric.v2B\x11GraphServiceProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_graph_service_proto_rawDescOnce sync.Once
	file_polycentric_v2_graph_service_proto_rawDescData []byte
)

func file_polycentric_v2_graph_service_proto_rawDescGZIP() []byte {
	file_polycentric_v2_graph_service_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_graph_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_graph_service_proto_rawDesc), len(file_polycentric_v2_graph_service_proto_rawDesc)))
	})
	return file_polycentric_v2_graph_service_proto_rawDescData
}

var file_polycentric_v2_graph_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_polycentric_v2_graph_service_proto_goTypes = []any{
	(*ListFollowingRequest)(nil),  // 0: polycentric.v2.ListFollowingRequest
	(*ListFollowersRequest)(nil),  // 1: polycentric.v2.ListFollowersRequest
	(*SuggestFollowRequest)(nil),  // 2: polycentric.v2.SuggestFollowRequest
	(*ListFollowsResponse)(nil),   // 3: polycentric.v2.ListFollowsResponse
	(*SuggestFollowResponse)(nil), // 4: polycentric.v2.SuggestFollowResponse
	(*FollowSuggestion)(nil),      // 5: polycentric.v2.FollowSuggestion
	(*PageParams)(nil),            // 6: polycentric.v2.PageParams
	(*EventBundle)(nil),           // 7: polycentric.v2.EventBundle
	(*PageInfo)(nil),              // 8: polycentric.v2.PageInfo
	(*EventHint)(nil),             // 9: polycentric.v2.EventHint
}
var file_polycentric_v2_graph_service_proto_depIdxs = []int32{
	6,  // 0: polycentric.v2.ListFollowingRequest.page_params:type_name -> polycentric.v2.PageParams
	6,  // 1: polycentric.v2.ListFollowersRequest.page_params:type_name -> polycentric.v2.PageParams
	6,  // 2: polycentric.v2.SuggestFollowRequest.page_params:type_name -> polycentric.v2.PageParams
	7,  // 3: polycentric.v2.ListFollowsResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	8,  // 4: polycentric.v2.ListFollowsResponse.page_info:type_name -> polycentric.v2.PageInfo
	9,  // 5: polycentric.v2.ListFollowsResponse.event_hints:type_name -> polycentric.v2.EventHint
	5,  // 6: polycentric.v2.SuggestFollowResponse.suggestions:type_name -> polycentric.v2.FollowSuggestion
	8,  // 7: polycentric.v2.SuggestFollowResponse.page_info:type_name -> polycentric.v2.PageInfo
	9,  // 8: polycentric.v2.SuggestFollowResponse.event_hints:type_name -> polycentric.v2.EventHint
	7,  // 9: polycentric.v2.FollowSuggestion.suggestion:type_name -> polycentric.v2.EventBundle
	0,  // 10: polycentric.v2.GraphService.ListFollowing:input_type -> polycentric.v2.ListFollowingRequest
	1,  // 11: polycentric.v2.GraphService.ListFollowers:input_type -> polycentric.v2.ListFollowersRequest
	2,  // 12: polycentric.v2.GraphService.SuggestFollow:input_type -> polycentric.v2.SuggestFollowRequest
	3,  // 13: polycentric.v2.GraphService.ListFollowing:output_type -> polycentric.v2.ListFollowsResponse
	3,  // 14: polycentric.v2.GraphService.ListFollowers:output_type -> polycentric.v2.ListFollowsResponse
	4,  // 15: polycentric.v2.GraphService.SuggestFollow:output_type -> polycentric.v2.SuggestFollowResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_polycentric_v2_graph_service_proto_init() }
func file_polycentric_v2_graph_service_proto_init() {
	if File_polycentric_v2_graph_service_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_events_proto_init()
	file_polycentric_v2_graph_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_polycentric_v2_graph_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_polycentric_v2_graph_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_polycentric_v2_graph_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_polycentric_v2_graph_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_graph_service_proto_rawDesc), len(file_polycentric_v2_graph_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_graph_service_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_graph_service_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_graph_service_proto_msgTypes,
	}.Build()
	File_polycentric_v2_graph_service_proto = out.File
	file_polycentric_v2_graph_service_proto_goTypes = nil
	file_polycentric_v2_graph_service_proto_depIdxs = nil
}
