// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/identity.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of the currently-active rotation keys.
	// These keys can publish events, including identity events with updates made
	// to the identity document.
	RotationKeys []*PublicKey `protobuf:"bytes,1,rep,name=rotation_keys,json=rotationKeys,proto3" json:"rotation_keys,omitempty"`
	// List of keys that are allowed to sign events (but not change the identity content).
	SigningKeys []*PublicKey `protobuf:"bytes,2,rep,name=signing_keys,json=signingKeys,proto3" json:"signing_keys,omitempty"`
	// In order to retain valid events from a revoked keypair, we store their last known
	// signature for each collection the key participated in.
	RevocationBounds []*RevocationBound `protobuf:"bytes,3,rep,name=revocation_bounds,json=revocationBounds,proto3" json:"revocation_bounds,omitempty"`
	// Preferred servers of this identity (where they push and pull from).
	// Absent means the identity has not configured a server list yet and
	// clients fall back to their defaults; present-but-empty is intentional.
	Servers *ServerList `protobuf:"bytes,4,opt,name=servers,proto3" json:"servers,omitempty"`
	// Backup key for recovering an account with no active sessions.
	// Its only use is for producing recovery signatures.
	RecoveryKey *PublicKey `protobuf:"bytes,5,opt,name=recovery_key,json=recoveryKey,proto3,oneof" json:"recovery_key,omitempty"`
	// Signature from the recovery key in the preceding identity document.
	// The content signed should be (identity_string, new_rotation_key).
	RecoverySignature []byte `protobuf:"bytes,6,opt,name=recovery_signature,json=recoverySignature,proto3,oneof" json:"recovery_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_polycentric_v2_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetRotationKeys() []*PublicKey {
	if x != nil {
		return x.RotationKeys
	}
	return nil
}

func (x *Identity) GetSigningKeys() []*PublicKey {
	if x != nil {
		return x.SigningKeys
	}
	return nil
}

func (x *Identity) GetRevocationBounds() []*RevocationBound {
	if x != nil {
		return x.RevocationBounds
	}
	return nil
}

func (x *Identity) GetServers() *ServerList {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Identity) GetRecoveryKey() *PublicKey {
	if x != nil {
		return x.RecoveryKey
	}
	return nil
}

func (x *Identity) GetRecoverySignature() []byte {
	if x != nil {
		return x.RecoverySignature
	}
	return nil
}

type ServerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerList) Reset() {
	*x = ServerList{}
	mi := &file_polycentric_v2_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerList) ProtoMessage() {}

func (x *ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerList.ProtoReflect.Descriptor instead.
func (*ServerList) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ServerList) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type RevocationBound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key that is revoked
	RevokedKey *PublicKey `protobuf:"bytes,1,opt,name=revoked_key,json=revokedKey,proto3" json:"revoked_key,omitempty"`
	// One target per collection `revoked_key` wrote in, anchoring proof
	// verification at that collection's head event.
	Targets       []*EventProofTarget `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevocationBound) Reset() {
	*x = RevocationBound{}
	mi := &file_polycentric_v2_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationBound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationBound) ProtoMessage() {}

func (x *RevocationBound) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationBound.ProtoReflect.Descriptor instead.
func (*RevocationBound) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_proto_rawDescGZIP(), []int{2}
}

func (x *RevocationBound) GetRevokedKey() *PublicKey {
	if x != nil {
		return x.RevokedKey
	}
	return nil
}

func (x *RevocationBound) GetTargets() []*EventProofTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Per-collection target for verifying an EventProof.
type EventProofTarget struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Collection int32                  `protobuf:"varint,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// Event's signature; matched by `EventProof.target_signature`.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Event's `previous_root` — the Merkle root proofs verify against.
	Root []byte `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	// Leaf count of the tree at `root` (the number of events the head's
	// signer was aware of when they signed it).
	LeafCount     uint64 `protobuf:"varint,4,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProofTarget) Reset() {
	*x = EventProofTarget{}
	mi := &file_polycentric_v2_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProofTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProofTarget) ProtoMessage() {}

func (x *EventProofTarget) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProofTarget.ProtoReflect.Descriptor instead.
func (*EventProofTarget) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_proto_rawDescGZIP(), []int{3}
}

func (x *EventProofTarget) GetCollection() int32 {
	if x != nil {
		return x.Collection
	}
	return 0
}

func (x *EventProofTarget) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EventProofTarget) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *EventProofTarget) GetLeafCount() uint64 {
	if x != nil {
		return x.LeafCount
	}
	return 0
}

var File_polycentric_v2_identity_proto protoreflect.FileDescriptor

const file_polycentric_v2_identity_proto_rawDesc = "" +
	"\n" +
	"\x1dpolycentric/v2/identity.proto\x12\x0epolycentric.v2\x1a\x1cpolycentric/v2/keypair.proto\"\xab\x03\n" +
	"\bIdentity\x12>\n" +
	"\rrotation_keys\x18\x01 \x03(\v2\x19.polycentric.v2.PublicKeyR\frotationKeys\x12<\n" +
	"\fsigning_keys\x18\x02 \x03(\v2\x19.polycentric.v2.PublicKeyR\vsigningKeys\x12L\n" +
	"\x11revocation_bounds\x18\x03 \x03(\v2\x1f.polycentric.v2.RevocationBoundR\x10revocationBounds\x124\n" +
	"\aservers\x18\x04 \x01(\v2\x1a.polycentric.v2.ServerListR\aservers\x12A\n" +
	"\frecovery_key\x18\x05 \x01(\v2\x19.polycentric.v2.PublicKeyH\x00R\vrecoveryKey\x88\x01\x01\x122\n" +
	"\x12recovery_signature\x18\x06 \x01(\fH\x01R\x11recoverySignature\x88\x01\x01B\x0f\n" +
	"\r_recovery_keyB\x15\n" +
	"\x13_recovery_signature\" \n" +
	"\n" +
	"ServerList\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"\x89\x01\n" +
	"\x0fRevocationBound\x12:\n" +
	"\vrevoked_key\x18\x01 \x01(\v2\x19.polycentric.v2.PublicKeyR\n" +
	"revokedKey\x12:\n" +
	"\atargets\x18\x02 \x03(\v2 .polycentric.v2.EventProofTargetR\atargets\"\x83\x01\n" +
	"\x10EventProofTarget\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\x05R\n" +
	"collection\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x12\n" +
	"\x04root\x18\x03 \x01(\fR\x04root\x12\x1d\n" +
	"\n" +
	"leaf_count\x18\x04 \x01(\x04R\tleafCountB\xcf\x01\n" +
	"\x12com.polycentric.v2B\rIdentityProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_identity_proto_rawDescOnce sync.Once
	file_polycentric_v2_identity_proto_rawDescData []byte
)

func file_polycentric_v2_identity_proto_rawDescGZIP() []byte {
	file_polycentric_v2_identity_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_identity_proto_rawDesc), len(file_polycentric_v2_identity_proto_rawDesc)))
	})
	return file_polycentric_v2_identity_proto_rawDescData
}

var file_polycentric_v2_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_polycentric_v2_identity_proto_goTypes = []any{
	(*Identity)(nil),         // 0: polycentric.v2.Identity
	(*ServerList)(nil),       // 1: polycentric.v2.ServerList
	(*RevocationBound)(nil),  // 2: polycentric.v2.RevocationBound
	(*EventProofTarget)(nil), // 3: polycentric.v2.EventProofTarget
	(*PublicKey)(nil),        // 4: polycentric.v2.PublicKey
}
var file_polycentric_v2_identity_proto_depIdxs = []int32{
	4, // 0: polycentric.v2.Identity.rotation_keys:type_name -> polycentric.v2.PublicKey
	4, // 1: polycentric.v2.Identity.signing_keys:type_name -> polycentric.v2.PublicKey
	2, // 2: polycentric.v2.Identity.revocation_bounds:type_name -> polycentric.v2.RevocationBound
	1, // 3: polycentric.v2.Identity.servers:type_name -> polycentric.v2.ServerList
	4, // 4: polycentric.v2.Identity.recovery_key:type_name -> polycentric.v2.PublicKey
	4, // 5: polycentric.v2.RevocationBound.revoked_key:type_name -> polycentric.v2.PublicKey
	3, // 6: polycentric.v2.RevocationBound.targets:type_name -> polycentric.v2.EventProofTarget
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_polycentric_v2_identity_proto_init() }
func file_polycentric_v2_identity_proto_init() {
	if File_polycentric_v2_identity_proto != nil {
		return
	}
	file_polycentric_v2_keypair_proto_init()
	file_polycentric_v2_identity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_identity_proto_rawDesc), len(file_polycentric_v2_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycentric_v2_identity_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_identity_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_identity_proto_msgTypes,
	}.Build()
	File_polycentric_v2_identity_proto = out.File
	file_polycentric_v2_identity_proto_goTypes = nil
	file_polycentric_v2_identity_proto_depIdxs = nil
}
