// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/identity_service.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// IsModerator: no extra fields.
type IsModeratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsModeratorRequest) Reset() {
	*x = IsModeratorRequest{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsModeratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsModeratorRequest) ProtoMessage() {}

func (x *IsModeratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsModeratorRequest.ProtoReflect.Descriptor instead.
func (*IsModeratorRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{0}
}

type IsModeratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsModerator   bool                   `protobuf:"varint,1,opt,name=is_moderator,json=isModerator,proto3" json:"is_moderator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsModeratorResponse) Reset() {
	*x = IsModeratorResponse{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsModeratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsModeratorResponse) ProtoMessage() {}

func (x *IsModeratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsModeratorResponse.ProtoReflect.Descriptor instead.
func (*IsModeratorResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{1}
}

func (x *IsModeratorResponse) GetIsModerator() bool {
	if x != nil {
		return x.IsModerator
	}
	return false
}

// *
// SetBanStatus: ban or unban an identity.
type SetBanStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity key being banned or unbanned.
	TargetIdentity string `protobuf:"bytes,1,opt,name=target_identity,json=targetIdentity,proto3" json:"target_identity,omitempty"`
	// Desired ban state: true to ban, false to unban.
	Banned        bool `protobuf:"varint,2,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBanStatusRequest) Reset() {
	*x = SetBanStatusRequest{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBanStatusRequest) ProtoMessage() {}

func (x *SetBanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBanStatusRequest.ProtoReflect.Descriptor instead.
func (*SetBanStatusRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetBanStatusRequest) GetTargetIdentity() string {
	if x != nil {
		return x.TargetIdentity
	}
	return ""
}

func (x *SetBanStatusRequest) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type SetBanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBanStatusResponse) Reset() {
	*x = SetBanStatusResponse{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBanStatusResponse) ProtoMessage() {}

func (x *SetBanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBanStatusResponse.ProtoReflect.Descriptor instead.
func (*SetBanStatusResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{3}
}

// *
// IsBanned: query whether an identity is banned.
type IsBannedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity key being asked about.
	TargetIdentity string `protobuf:"bytes,1,opt,name=target_identity,json=targetIdentity,proto3" json:"target_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsBannedRequest) Reset() {
	*x = IsBannedRequest{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBannedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBannedRequest) ProtoMessage() {}

func (x *IsBannedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBannedRequest.ProtoReflect.Descriptor instead.
func (*IsBannedRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{4}
}

func (x *IsBannedRequest) GetTargetIdentity() string {
	if x != nil {
		return x.TargetIdentity
	}
	return ""
}

type IsBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBanned      bool                   `protobuf:"varint,1,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBannedResponse) Reset() {
	*x = IsBannedResponse{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBannedResponse) ProtoMessage() {}

func (x *IsBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBannedResponse.ProtoReflect.Descriptor instead.
func (*IsBannedResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{5}
}

func (x *IsBannedResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

// *
// ListBans: paginated, optionally filtered list of banned identities.
type ListBansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max entries to return; the server clamps to its own bounds.
	Limit *uint32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Opaque cursor from a previous response's `page_info.end_cursor`.
	After *string `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`
	// Case-insensitive prefix filter: keep only identities beginning with
	// this value.
	Query         *string `protobuf:"bytes,3,opt,name=query,proto3,oneof" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBansRequest) Reset() {
	*x = ListBansRequest{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBansRequest) ProtoMessage() {}

func (x *ListBansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBansRequest.ProtoReflect.Descriptor instead.
func (*ListBansRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListBansRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListBansRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *ListBansRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

type ListBansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity keys banned on this server, most recently banned first.
	BannedIdentities []string  `protobuf:"bytes,1,rep,name=banned_identities,json=bannedIdentities,proto3" json:"banned_identities,omitempty"`
	PageInfo         *PageInfo `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListBansResponse) Reset() {
	*x = ListBansResponse{}
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBansResponse) ProtoMessage() {}

func (x *ListBansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_identity_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBansResponse.ProtoReflect.Descriptor instead.
func (*ListBansResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_identity_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListBansResponse) GetBannedIdentities() []string {
	if x != nil {
		return x.BannedIdentities
	}
	return nil
}

func (x *ListBansResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_polycentric_v2_identity_service_proto protoreflect.FileDescriptor

const file_polycentric_v2_identity_service_proto_rawDesc = "" +
	"\n" +
	"%polycentric/v2/identity_service.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\"\x14\n" +
	"\x12IsModeratorRequest\"8\n" +
	"\x13IsModeratorResponse\x12!\n" +
	"\fis_moderator\x18\x01 \x01(\bR\visModerator\"V\n" +
	"\x13SetBanStatusRequest\x12'\n" +
	"\x0ftarget_identity\x18\x01 \x01(\tR\x0etargetIdentity\x12\x16\n" +
	"\x06banned\x18\x02 \x01(\bR\x06banned\"\x16\n" +
	"\x14SetBanStatusResponse\":\n" +
	"\x0fIsBannedRequest\x12'\n" +
	"\x0ftarget_identity\x18\x01 \x01(\tR\x0etargetIdentity\"/\n" +
	"\x10IsBannedResponse\x12\x1b\n" +
	"\tis_banned\x18\x01 \x01(\bR\bisBanned\"\x80\x01\n" +
	"\x0fListBansRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x02 \x01(\tH\x01R\x05after\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x03 \x01(\tH\x02R\x05query\x88\x01\x01B\b\n" +
	"\x06_limitB\b\n" +
	"\x06_afterB\b\n" +
	"\x06_query\"v\n" +
	"\x10ListBansResponse\x12+\n" +
	"\x11banned_identities\x18\x01 \x03(\tR\x10bannedIdentities\x125\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.polycentric.v2.PageInfoR\bpageInfo2\xe2\x02\n" +
	"\x0fIdentityService\x12V\n" +
	"\vIsModerator\x12\".polycentric.v2.IsModeratorRequest\x1a#.polycentric.v2.IsModeratorResponse\x12Y\n" +
	"\fSetBanStatus\x12#.polycentric.v2.SetBanStatusRequest\x1a$.polycentric.v2.SetBanStatusResponse\x12M\n" +
	"\bIsBanned\x12\x1f.polycentric.v2.IsBannedRequest\x1a .polycentric.v2.IsBannedResponse\x12M\n" +
	"\bListBans\x12\x1f.polycentric.v2.ListBansRequest\x1a .polycentric.v2.ListBansResponseB\xd6\x01\n" +
	"\x12com.polycentric.v2B\x14IdentityServiceProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_identity_service_proto_rawDescOnce sync.Once
	file_polycentric_v2_identity_service_proto_rawDescData []byte
)

func file_polycentric_v2_identity_service_proto_rawDescGZIP() []byte {
	file_polycentric_v2_identity_service_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_identity_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_identity_service_proto_rawDesc), len(file_polycentric_v2_identity_service_proto_rawDesc)))
	})
	return file_polycentric_v2_identity_service_proto_rawDescData
}

var file_polycentric_v2_identity_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_polycentric_v2_identity_service_proto_goTypes = []any{
	(*IsModeratorRequest)(nil),   // 0: polycentric.v2.IsModeratorRequest
	(*IsModeratorResponse)(nil),  // 1: polycentric.v2.IsModeratorResponse
	(*SetBanStatusRequest)(nil),  // 2: polycentric.v2.SetBanStatusRequest
	(*SetBanStatusResponse)(nil), // 3: polycentric.v2.SetBanStatusResponse
	(*IsBannedRequest)(nil),      // 4: polycentric.v2.IsBannedRequest
	(*IsBannedResponse)(nil),     // 5: polycentric.v2.IsBannedResponse
	(*ListBansRequest)(nil),      // 6: polycentric.v2.ListBansRequest
	(*ListBansResponse)(nil),     // 7: polycentric.v2.ListBansResponse
	(*PageInfo)(nil),             // 8: polycentric.v2.PageInfo
}
var file_polycentric_v2_identity_service_proto_depIdxs = []int32{
	8, // 0: polycentric.v2.ListBansResponse.page_info:type_name -> polycentric.v2.PageInfo
	0, // 1: polycentric.v2.IdentityService.IsModerator:input_type -> polycentric.v2.IsModeratorRequest
	2, // 2: polycentric.v2.IdentityService.SetBanStatus:input_type -> polycentric.v2.SetBanStatusRequest
	4, // 3: polycentric.v2.IdentityService.IsBanned:input_type -> polycentric.v2.IsBannedRequest
	6, // 4: polycentric.v2.IdentityService.ListBans:input_type -> polycentric.v2.ListBansRequest
	1, // 5: polycentric.v2.IdentityService.IsModerator:output_type -> polycentric.v2.IsModeratorResponse
	3, // 6: polycentric.v2.IdentityService.SetBanStatus:output_type -> polycentric.v2.SetBanStatusResponse
	5, // 7: polycentric.v2.IdentityService.IsBanned:output_type -> polycentric.v2.IsBannedResponse
	7, // 8: polycentric.v2.IdentityService.ListBans:output_type -> polycentric.v2.ListBansResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_polycentric_v2_identity_service_proto_init() }
func file_polycentric_v2_identity_service_proto_init() {
	if File_polycentric_v2_identity_service_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_identity_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_identity_service_proto_rawDesc), len(file_polycentric_v2_identity_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_identity_service_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_identity_service_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_identity_service_proto_msgTypes,
	}.Build()
	File_polycentric_v2_identity_service_proto = out.File
	file_polycentric_v2_identity_service_proto_goTypes = nil
	file_polycentric_v2_identity_service_proto_depIdxs = nil
}
