// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/keypair.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_KEY_TYPE_UNSPECIFIED KeyType = 0
	KeyType_KEY_TYPE_ED25519     KeyType = 1
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEY_TYPE_UNSPECIFIED",
		1: "KEY_TYPE_ED25519",
	}
	KeyType_value = map[string]int32{
		"KEY_TYPE_UNSPECIFIED": 0,
		"KEY_TYPE_ED25519":     1,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_keypair_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_polycentric_v2_keypair_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_keypair_proto_rawDescGZIP(), []int{0}
}

// PublicKeys signs all events on the polycentric network. There is usually one public key per account, per device.
type PublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of key used. Defaults to ED25519.
	KeyType KeyType `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=polycentric.v2.KeyType" json:"key_type,omitempty"`
	// Value of the key
	Key           []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_polycentric_v2_keypair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_keypair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_keypair_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *PublicKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// The private key corresponding to a public key.
type PrivateKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of key used. Defaults to ED25519.
	KeyType KeyType `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=polycentric.v2.KeyType" json:"key_type,omitempty"`
	// Value of the key
	Key           []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	mi := &file_polycentric_v2_keypair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_keypair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_keypair_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateKey) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *PrivateKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_polycentric_v2_keypair_proto protoreflect.FileDescriptor

const file_polycentric_v2_keypair_proto_rawDesc = "" +
	"\n" +
	"\x1cpolycentric/v2/keypair.proto\x12\x0epolycentric.v2\"Q\n" +
	"\tPublicKey\x122\n" +
	"\bkey_type\x18\x01 \x01(\x0e2\x17.polycentric.v2.KeyTypeR\akeyType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"R\n" +
	"\n" +
	"PrivateKey\x122\n" +
	"\bkey_type\x18\x01 \x01(\x0e2\x17.polycentric.v2.KeyTypeR\akeyType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key*9\n" +
	"\aKeyType\x12\x18\n" +
	"\x14KEY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KEY_TYPE_ED25519\x10\x01B\xce\x01\n" +
	"\x12com.polycentric.v2B\fKeypairProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_keypair_proto_rawDescOnce sync.Once
	file_polycentric_v2_keypair_proto_rawDescData []byte
)

func file_polycentric_v2_keypair_proto_rawDescGZIP() []byte {
	file_polycentric_v2_keypair_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_keypair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_keypair_proto_rawDesc), len(file_polycentric_v2_keypair_proto_rawDesc)))
	})
	return file_polycentric_v2_keypair_proto_rawDescData
}

var file_polycentric_v2_keypair_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polycentric_v2_keypair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_polycentric_v2_keypair_proto_goTypes = []any{
	(KeyType)(0),       // 0: polycentric.v2.KeyType
	(*PublicKey)(nil),  // 1: polycentric.v2.PublicKey
	(*PrivateKey)(nil), // 2: polycentric.v2.PrivateKey
}
var file_polycentric_v2_keypair_proto_depIdxs = []int32{
	0, // 0: polycentric.v2.PublicKey.key_type:type_name -> polycentric.v2.KeyType
	0, // 1: polycentric.v2.PrivateKey.key_type:type_name -> polycentric.v2.KeyType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_polycentric_v2_keypair_proto_init() }
func file_polycentric_v2_keypair_proto_init() {
	if File_polycentric_v2_keypair_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_keypair_proto_rawDesc), len(file_polycentric_v2_keypair_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycentric_v2_keypair_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_keypair_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_keypair_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_keypair_proto_msgTypes,
	}.Build()
	File_polycentric_v2_keypair_proto = out.File
	file_polycentric_v2_keypair_proto_goTypes = nil
	file_polycentric_v2_keypair_proto_depIdxs = nil
}
