// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/notifications.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationKind int32

const (
	NotificationKind_NOTIFICATION_KIND_UNSPECIFIED           NotificationKind = 0
	NotificationKind_NOTIFICATION_KIND_FOLLOW                NotificationKind = 1
	NotificationKind_NOTIFICATION_KIND_REPLY                 NotificationKind = 2
	NotificationKind_NOTIFICATION_KIND_REPOST                NotificationKind = 3
	NotificationKind_NOTIFICATION_KIND_REACTION              NotificationKind = 4
	NotificationKind_NOTIFICATION_KIND_QUOTE                 NotificationKind = 5
	NotificationKind_NOTIFICATION_KIND_VERIFICATION_REQUEST  NotificationKind = 6
	NotificationKind_NOTIFICATION_KIND_VERIFICATION_COMPLETE NotificationKind = 7
	NotificationKind_NOTIFICATION_KIND_MENTION               NotificationKind = 8
)

// Enum value maps for NotificationKind.
var (
	NotificationKind_name = map[int32]string{
		0: "NOTIFICATION_KIND_UNSPECIFIED",
		1: "NOTIFICATION_KIND_FOLLOW",
		2: "NOTIFICATION_KIND_REPLY",
		3: "NOTIFICATION_KIND_REPOST",
		4: "NOTIFICATION_KIND_REACTION",
		5: "NOTIFICATION_KIND_QUOTE",
		6: "NOTIFICATION_KIND_VERIFICATION_REQUEST",
		7: "NOTIFICATION_KIND_VERIFICATION_COMPLETE",
		8: "NOTIFICATION_KIND_MENTION",
	}
	NotificationKind_value = map[string]int32{
		"NOTIFICATION_KIND_UNSPECIFIED":           0,
		"NOTIFICATION_KIND_FOLLOW":                1,
		"NOTIFICATION_KIND_REPLY":                 2,
		"NOTIFICATION_KIND_REPOST":                3,
		"NOTIFICATION_KIND_REACTION":              4,
		"NOTIFICATION_KIND_QUOTE":                 5,
		"NOTIFICATION_KIND_VERIFICATION_REQUEST":  6,
		"NOTIFICATION_KIND_VERIFICATION_COMPLETE": 7,
		"NOTIFICATION_KIND_MENTION":               8,
	}
)

func (x NotificationKind) Enum() *NotificationKind {
	p := new(NotificationKind)
	*p = x
	return p
}

func (x NotificationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationKind) Type() protoreflect.EnumType {
	return &file_polycentric_v2_notifications_proto_enumTypes[0]
}

func (x NotificationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationKind.Descriptor instead.
func (NotificationKind) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{0}
}

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event that triggered the notification
	TriggerEvent *EventBundle `protobuf:"bytes,1,opt,name=trigger_event,json=triggerEvent,proto3" json:"trigger_event,omitempty"`
	// Event that the notification is in relation to
	TargetEvent *EventBundle `protobuf:"bytes,2,opt,name=target_event,json=targetEvent,proto3" json:"target_event,omitempty"`
	// Kind of the notification
	Kind          NotificationKind `protobuf:"varint,3,opt,name=kind,proto3,enum=polycentric.v2.NotificationKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetTriggerEvent() *EventBundle {
	if x != nil {
		return x.TriggerEvent
	}
	return nil
}

func (x *Notification) GetTargetEvent() *EventBundle {
	if x != nil {
		return x.TargetEvent
	}
	return nil
}

func (x *Notification) GetKind() NotificationKind {
	if x != nil {
		return x.Kind
	}
	return NotificationKind_NOTIFICATION_KIND_UNSPECIFIED
}

type ListNotificationsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Return the 1 X number of notifications
	First *uint32 `protobuf:"varint,2,opt,name=first,proto3,oneof" json:"first,omitempty"`
	// Return notifications after a cursor
	After *string `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	// Label values for which the requester does not want to see content
	OmitLabels    []string `protobuf:"bytes,4,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ListNotificationsRequest) GetFirst() uint32 {
	if x != nil && x.First != nil {
		return *x.First
	}
	return 0
}

func (x *ListNotificationsRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *ListNotificationsRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	// Events that help the client resolve with fewer network calls
	EventHints    []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	PageInfo      *PageInfo    `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

func (x *ListNotificationsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type RegisterPushNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPushNotificationRequest) Reset() {
	*x = RegisterPushNotificationRequest{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushNotificationRequest) ProtoMessage() {}

func (x *RegisterPushNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushNotificationRequest.ProtoReflect.Descriptor instead.
func (*RegisterPushNotificationRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterPushNotificationRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RegisterPushNotificationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterPushNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPushNotificationResponse) Reset() {
	*x = RegisterPushNotificationResponse{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushNotificationResponse) ProtoMessage() {}

func (x *RegisterPushNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushNotificationResponse.ProtoReflect.Descriptor instead.
func (*RegisterPushNotificationResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{4}
}

type UnregisterPushNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterPushNotificationRequest) Reset() {
	*x = UnregisterPushNotificationRequest{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPushNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPushNotificationRequest) ProtoMessage() {}

func (x *UnregisterPushNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPushNotificationRequest.ProtoReflect.Descriptor instead.
func (*UnregisterPushNotificationRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterPushNotificationRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UnregisterPushNotificationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UnregisterPushNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterPushNotificationResponse) Reset() {
	*x = UnregisterPushNotificationResponse{}
	mi := &file_polycentric_v2_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPushNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPushNotificationResponse) ProtoMessage() {}

func (x *UnregisterPushNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPushNotificationResponse.ProtoReflect.Descriptor instead.
func (*UnregisterPushNotificationResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_notifications_proto_rawDescGZIP(), []int{6}
}

var File_polycentric_v2_notifications_proto protoreflect.FileDescriptor

const file_polycentric_v2_notifications_proto_rawDesc = "" +
	"\n" +
	"\"polycentric/v2/notifications.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1bpolycentric/v2/events.proto\x1a\x1bpolycentric/v2/server.proto\"\xc6\x01\n" +
	"\fNotification\x12@\n" +
	"\rtrigger_event\x18\x01 \x01(\v2\x1b.polycentric.v2.EventBundleR\ftriggerEvent\x12>\n" +
	"\ftarget_event\x18\x02 \x01(\v2\x1b.polycentric.v2.EventBundleR\vtargetEvent\x124\n" +
	"\x04kind\x18\x03 \x01(\x0e2 .polycentric.v2.NotificationKindR\x04kind\"\xa1\x01\n" +
	"\x18ListNotificationsRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x19\n" +
	"\x05first\x18\x02 \x01(\rH\x00R\x05first\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x01R\x05after\x88\x01\x01\x12\x1f\n" +
	"\vomit_labels\x18\x04 \x03(\tR\n" +
	"omitLabelsB\b\n" +
	"\x06_firstB\b\n" +
	"\x06_after\"\xd2\x01\n" +
	"\x19ListNotificationsResponse\x12B\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1c.polycentric.v2.NotificationR\rnotifications\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\x125\n" +
	"\tpage_info\x18\x03 \x01(\v2\x18.polycentric.v2.PageInfoR\bpageInfo\"Q\n" +
	"\x1fRegisterPushNotificationRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\"\n" +
	" RegisterPushNotificationResponse\"S\n" +
	"!UnregisterPushNotificationRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"$\n" +
	"\"UnregisterPushNotificationResponse*\xc3\x02\n" +
	"\x10NotificationKind\x12!\n" +
	"\x1dNOTIFICATION_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NOTIFICATION_KIND_FOLLOW\x10\x01\x12\x1b\n" +
	"\x17NOTIFICATION_KIND_REPLY\x10\x02\x12\x1c\n" +
	"\x18NOTIFICATION_KIND_REPOST\x10\x03\x12\x1e\n" +
	"\x1aNOTIFICATION_KIND_REACTION\x10\x04\x12\x1b\n" +
	"\x17NOTIFICATION_KIND_QUOTE\x10\x05\x12*\n" +
	"&NOTIFICATION_KIND_VERIFICATION_REQUEST\x10\x06\x12+\n" +
	"'NOTIFICATION_KIND_VERIFICATION_COMPLETE\x10\a\x12\x1d\n" +
	"\x19NOTIFICATION_KIND_MENTION\x10\b2\xdf\x02\n" +
	"\x13NotificationService\x12h\n" +
	"\x11ListNotifications\x12(.polycentric.v2.ListNotificationsRequest\x1a).polycentric.v2.ListNotificationsResponse\x12l\n" +
	"\x19RegisterPushNotifications\x12\x1d.polycentric.v2.SignedMessage\x1a0.polycentric.v2.RegisterPushNotificationResponse\x12p\n" +
	"\x1bUnregisterPushNotifications\x12\x1d.polycentric.v2.SignedMessage\x1a2.polycentric.v2.UnregisterPushNotificationResponseB\xd4\x01\n" +
	"\x12com.polycentric.v2B\x12NotificationsProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_notifications_proto_rawDescOnce sync.Once
	file_polycentric_v2_notifications_proto_rawDescData []byte
)

func file_polycentric_v2_notifications_proto_rawDescGZIP() []byte {
	file_polycentric_v2_notifications_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_notifications_proto_rawDesc), len(file_polycentric_v2_notifications_proto_rawDesc)))
	})
	return file_polycentric_v2_notifications_proto_rawDescData
}

var file_polycentric_v2_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polycentric_v2_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_polycentric_v2_notifications_proto_goTypes = []any{
	(NotificationKind)(0),                      // 0: polycentric.v2.NotificationKind
	(*Notification)(nil),                       // 1: polycentric.v2.Notification
	(*ListNotificationsRequest)(nil),           // 2: polycentric.v2.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),          // 3: polycentric.v2.ListNotificationsResponse
	(*RegisterPushNotificationRequest)(nil),    // 4: polycentric.v2.RegisterPushNotificationRequest
	(*RegisterPushNotificationResponse)(nil),   // 5: polycentric.v2.RegisterPushNotificationResponse
	(*UnregisterPushNotificationRequest)(nil),  // 6: polycentric.v2.UnregisterPushNotificationRequest
	(*UnregisterPushNotificationResponse)(nil), // 7: polycentric.v2.UnregisterPushNotificationResponse
	(*EventBundle)(nil),                        // 8: polycentric.v2.EventBundle
	(*EventHint)(nil),                          // 9: polycentric.v2.EventHint
	(*PageInfo)(nil),                           // 10: polycentric.v2.PageInfo
	(*SignedMessage)(nil),                      // 11: polycentric.v2.SignedMessage
}
var file_polycentric_v2_notifications_proto_depIdxs = []int32{
	8,  // 0: polycentric.v2.Notification.trigger_event:type_name -> polycentric.v2.EventBundle
	8,  // 1: polycentric.v2.Notification.target_event:type_name -> polycentric.v2.EventBundle
	0,  // 2: polycentric.v2.Notification.kind:type_name -> polycentric.v2.NotificationKind
	1,  // 3: polycentric.v2.ListNotificationsResponse.notifications:type_name -> polycentric.v2.Notification
	9,  // 4: polycentric.v2.ListNotificationsResponse.event_hints:type_name -> polycentric.v2.EventHint
	10, // 5: polycentric.v2.ListNotificationsResponse.page_info:type_name -> polycentric.v2.PageInfo
	2,  // 6: polycentric.v2.NotificationService.ListNotifications:input_type -> polycentric.v2.ListNotificationsRequest
	11, // 7: polycentric.v2.NotificationService.RegisterPushNotifications:input_type -> polycentric.v2.SignedMessage
	11, // 8: polycentric.v2.NotificationService.UnregisterPushNotifications:input_type -> polycentric.v2.SignedMessage
	3,  // 9: polycentric.v2.NotificationService.ListNotifications:output_type -> polycentric.v2.ListNotificationsResponse
	5,  // 10: polycentric.v2.NotificationService.RegisterPushNotifications:output_type -> polycentric.v2.RegisterPushNotificationResponse
	7,  // 11: polycentric.v2.NotificationService.UnregisterPushNotifications:output_type -> polycentric.v2.UnregisterPushNotificationResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_polycentric_v2_notifications_proto_init() }
func file_polycentric_v2_notifications_proto_init() {
	if File_polycentric_v2_notifications_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_events_proto_init()
	file_polycentric_v2_server_proto_init()
	file_polycentric_v2_notifications_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_notifications_proto_rawDesc), len(file_polycentric_v2_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_notifications_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_notifications_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_notifications_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_notifications_proto_msgTypes,
	}.Build()
	File_polycentric_v2_notifications_proto = out.File
	file_polycentric_v2_notifications_proto_goTypes = nil
	file_polycentric_v2_notifications_proto_depIdxs = nil
}
