// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/pairing_service.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Immutable state created at the start of a pairing session that uniquely
// identifies it.
type PairingSessionDigest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trusted source of truth for the identity being paired with.
	IssuerIdentity string `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	// Each issuer state must be signed by this key and this key must be
	// authorized for rotation.
	IssuerSigner *PublicKey `protobuf:"bytes,2,opt,name=issuer_signer,json=issuerSigner,proto3" json:"issuer_signer,omitempty"`
	// Random bitstring to add entropy and keep session identifiers unpredictable.
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Timestamp in posix epoch millis.
	// Used for expiration and preventing replay attacks.
	InitialTimestamp int64 `protobuf:"varint,4,opt,name=initial_timestamp,json=initialTimestamp,proto3" json:"initial_timestamp,omitempty"`
	// The number of milliseconds after the initial timestamp for which this
	// session is considered valid.
	TtlMillis     int64 `protobuf:"varint,5,opt,name=ttl_millis,json=ttlMillis,proto3" json:"ttl_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingSessionDigest) Reset() {
	*x = PairingSessionDigest{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingSessionDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingSessionDigest) ProtoMessage() {}

func (x *PairingSessionDigest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingSessionDigest.ProtoReflect.Descriptor instead.
func (*PairingSessionDigest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{0}
}

func (x *PairingSessionDigest) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *PairingSessionDigest) GetIssuerSigner() *PublicKey {
	if x != nil {
		return x.IssuerSigner
	}
	return nil
}

func (x *PairingSessionDigest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PairingSessionDigest) GetInitialTimestamp() int64 {
	if x != nil {
		return x.InitialTimestamp
	}
	return 0
}

func (x *PairingSessionDigest) GetTtlMillis() int64 {
	if x != nil {
		return x.TtlMillis
	}
	return 0
}

// Data to share out-of-band between the issuer and claimer.
// This means using copy/paste or a QR code.
type PairingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL of the server that holds this pairing session.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// SHA256 hash of the pairing session digest.
	DigestSha256  []byte `protobuf:"bytes,2,opt,name=digest_sha256,json=digestSha256,proto3" json:"digest_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingInfo) Reset() {
	*x = PairingInfo{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingInfo) ProtoMessage() {}

func (x *PairingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingInfo.ProtoReflect.Descriptor instead.
func (*PairingInfo) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{1}
}

func (x *PairingInfo) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *PairingInfo) GetDigestSha256() []byte {
	if x != nil {
		return x.DigestSha256
	}
	return nil
}

// Signed payload from issuers that contains pairing state information.
// Contains authenticated information about the pairing session for claimers and
// servers to read.
// Clients and servers should only obtain messages of this type from a
// `SignedIssuerState` message and must check its signature.
type IssuerPairingState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized `PairingSessionDigest` message.
	// Identifies the pairing session that this state belongs to.
	// This should be kept constant throughout the session.
	// Clients should verify that the SHA256 hash and content of this field
	// matches what they expect.
	SessionDigest []byte `protobuf:"bytes,1,opt,name=session_digest,json=sessionDigest,proto3" json:"session_digest,omitempty"`
	// The most recent identity event for this identity as reported by the issuer.
	// Claimers should verify the full identity chain before fully trusting the
	// content of this field.
	// Even when not fully trusted, it is still useful for:
	// - seeding the list of servers to query.
	// - deciding when to try claiming.
	IdentityState *EventBundle `protobuf:"bytes,2,opt,name=identity_state,json=identityState,proto3" json:"identity_state,omitempty"`
	// A counter that gets incremented for each new state in this pairing session.
	// This keeps updates well-ordered and prevents replay attacks from rolling
	// back state.
	// Starts at 1 for each pairing session.
	Sequence      int64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerPairingState) Reset() {
	*x = IssuerPairingState{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerPairingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerPairingState) ProtoMessage() {}

func (x *IssuerPairingState) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerPairingState.ProtoReflect.Descriptor instead.
func (*IssuerPairingState) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{2}
}

func (x *IssuerPairingState) GetSessionDigest() []byte {
	if x != nil {
		return x.SessionDigest
	}
	return nil
}

func (x *IssuerPairingState) GetIdentityState() *EventBundle {
	if x != nil {
		return x.IdentityState
	}
	return nil
}

func (x *IssuerPairingState) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Encapsulates an issuer's signed pairing state and its signature.
type SignedIssuerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized `IssuerPairingState` message from the issuer.
	StateBytes []byte `protobuf:"bytes,1,opt,name=state_bytes,json=stateBytes,proto3" json:"state_bytes,omitempty"`
	// Signature over `state_bytes`.
	// Must use the key pair specified in the digest.
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedIssuerState) Reset() {
	*x = SignedIssuerState{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedIssuerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedIssuerState) ProtoMessage() {}

func (x *SignedIssuerState) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedIssuerState.ProtoReflect.Descriptor instead.
func (*SignedIssuerState) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{3}
}

func (x *SignedIssuerState) GetStateBytes() []byte {
	if x != nil {
		return x.StateBytes
	}
	return nil
}

func (x *SignedIssuerState) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Server-aggregated state for a pairing session containing input from the
// issuer and claimers.
type PairingSessionState struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	IssuerState *SignedIssuerState     `protobuf:"bytes,1,opt,name=issuer_state,json=issuerState,proto3" json:"issuer_state,omitempty"`
	// Server-managed list of claimers.
	Claimers      []*PublicKey `protobuf:"bytes,2,rep,name=claimers,proto3" json:"claimers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingSessionState) Reset() {
	*x = PairingSessionState{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingSessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingSessionState) ProtoMessage() {}

func (x *PairingSessionState) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingSessionState.ProtoReflect.Descriptor instead.
func (*PairingSessionState) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{4}
}

func (x *PairingSessionState) GetIssuerState() *SignedIssuerState {
	if x != nil {
		return x.IssuerState
	}
	return nil
}

func (x *PairingSessionState) GetClaimers() []*PublicKey {
	if x != nil {
		return x.Claimers
	}
	return nil
}

// *
// Request payload for fetching a pairing session.
type GetPairingSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DigestSha256  []byte                 `protobuf:"bytes,1,opt,name=digest_sha256,json=digestSha256,proto3" json:"digest_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairingSessionRequest) Reset() {
	*x = GetPairingSessionRequest{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairingSessionRequest) ProtoMessage() {}

func (x *GetPairingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairingSessionRequest.ProtoReflect.Descriptor instead.
func (*GetPairingSessionRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPairingSessionRequest) GetDigestSha256() []byte {
	if x != nil {
		return x.DigestSha256
	}
	return nil
}

// *
// Wrapper request for PutPairingSession RPC.
type PutPairingSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerState   *SignedIssuerState     `protobuf:"bytes,1,opt,name=issuer_state,json=issuerState,proto3" json:"issuer_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPairingSessionRequest) Reset() {
	*x = PutPairingSessionRequest{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPairingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPairingSessionRequest) ProtoMessage() {}

func (x *PutPairingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPairingSessionRequest.ProtoReflect.Descriptor instead.
func (*PutPairingSessionRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{6}
}

func (x *PutPairingSessionRequest) GetIssuerState() *SignedIssuerState {
	if x != nil {
		return x.IssuerState
	}
	return nil
}

// *
// Wrapper response for PutPairingSession RPC.
type PutPairingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionState  *PairingSessionState   `protobuf:"bytes,1,opt,name=session_state,json=sessionState,proto3" json:"session_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPairingSessionResponse) Reset() {
	*x = PutPairingSessionResponse{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPairingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPairingSessionResponse) ProtoMessage() {}

func (x *PutPairingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPairingSessionResponse.ProtoReflect.Descriptor instead.
func (*PutPairingSessionResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{7}
}

func (x *PutPairingSessionResponse) GetSessionState() *PairingSessionState {
	if x != nil {
		return x.SessionState
	}
	return nil
}

// *
// Wrapper response for GetPairingSession RPC.
type GetPairingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionState  *PairingSessionState   `protobuf:"bytes,1,opt,name=session_state,json=sessionState,proto3" json:"session_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairingSessionResponse) Reset() {
	*x = GetPairingSessionResponse{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairingSessionResponse) ProtoMessage() {}

func (x *GetPairingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairingSessionResponse.ProtoReflect.Descriptor instead.
func (*GetPairingSessionResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetPairingSessionResponse) GetSessionState() *PairingSessionState {
	if x != nil {
		return x.SessionState
	}
	return nil
}

// *
// Wrapper request for JoinPairingSession RPC.
type JoinPairingSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA256 of the pairing session digest to join.
	DigestSha256 []byte `protobuf:"bytes,1,opt,name=digest_sha256,json=digestSha256,proto3" json:"digest_sha256,omitempty"`
	// Public key that the claimer wishes to join with.
	ClaimerKey    *PublicKey `protobuf:"bytes,2,opt,name=claimer_key,json=claimerKey,proto3" json:"claimer_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPairingSessionRequest) Reset() {
	*x = JoinPairingSessionRequest{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPairingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPairingSessionRequest) ProtoMessage() {}

func (x *JoinPairingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPairingSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinPairingSessionRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{9}
}

func (x *JoinPairingSessionRequest) GetDigestSha256() []byte {
	if x != nil {
		return x.DigestSha256
	}
	return nil
}

func (x *JoinPairingSessionRequest) GetClaimerKey() *PublicKey {
	if x != nil {
		return x.ClaimerKey
	}
	return nil
}

// *
// Wrapper response for JoinPairingSession RPC.
type JoinPairingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionState  *PairingSessionState   `protobuf:"bytes,1,opt,name=session_state,json=sessionState,proto3" json:"session_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPairingSessionResponse) Reset() {
	*x = JoinPairingSessionResponse{}
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPairingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPairingSessionResponse) ProtoMessage() {}

func (x *JoinPairingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_pairing_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPairingSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinPairingSessionResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_pairing_service_proto_rawDescGZIP(), []int{10}
}

func (x *JoinPairingSessionResponse) GetSessionState() *PairingSessionState {
	if x != nil {
		return x.SessionState
	}
	return nil
}

var File_polycentric_v2_pairing_service_proto protoreflect.FileDescriptor

const file_polycentric_v2_pairing_service_proto_rawDesc = "" +
	"\n" +
	"$polycentric/v2/pairing_service.proto\x12\x0epolycentric.v2\x1a\x1cpolycentric/v2/keypair.proto\x1a\x1bpolycentric/v2/events.proto\"\xe1\x01\n" +
	"\x14PairingSessionDigest\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12>\n" +
	"\rissuer_signer\x18\x02 \x01(\v2\x19.polycentric.v2.PublicKeyR\fissuerSigner\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12+\n" +
	"\x11initial_timestamp\x18\x04 \x01(\x03R\x10initialTimestamp\x12\x1d\n" +
	"\n" +
	"ttl_millis\x18\x05 \x01(\x03R\tttlMillis\"J\n" +
	"\vPairingInfo\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12#\n" +
	"\rdigest_sha256\x18\x02 \x01(\fR\fdigestSha256\"\x9b\x01\n" +
	"\x12IssuerPairingState\x12%\n" +
	"\x0esession_digest\x18\x01 \x01(\fR\rsessionDigest\x12B\n" +
	"\x0eidentity_state\x18\x02 \x01(\v2\x1b.polycentric.v2.EventBundleR\ridentityState\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\"R\n" +
	"\x11SignedIssuerState\x12\x1f\n" +
	"\vstate_bytes\x18\x01 \x01(\fR\n" +
	"stateBytes\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x92\x01\n" +
	"\x13PairingSessionState\x12D\n" +
	"\fissuer_state\x18\x01 \x01(\v2!.polycentric.v2.SignedIssuerStateR\vissuerState\x125\n" +
	"\bclaimers\x18\x02 \x03(\v2\x19.polycentric.v2.PublicKeyR\bclaimers\"?\n" +
	"\x18GetPairingSessionRequest\x12#\n" +
	"\rdigest_sha256\x18\x01 \x01(\fR\fdigestSha256\"`\n" +
	"\x18PutPairingSessionRequest\x12D\n" +
	"\fissuer_state\x18\x01 \x01(\v2!.polycentric.v2.SignedIssuerStateR\vissuerState\"e\n" +
	"\x19PutPairingSessionResponse\x12H\n" +
	"\rsession_state\x18\x01 \x01(\v2#.polycentric.v2.PairingSessionStateR\fsessionState\"e\n" +
	"\x19GetPairingSessionResponse\x12H\n" +
	"\rsession_state\x18\x01 \x01(\v2#.polycentric.v2.PairingSessionStateR\fsessionState\"|\n" +
	"\x19JoinPairingSessionRequest\x12#\n" +
	"\rdigest_sha256\x18\x01 \x01(\fR\fdigestSha256\x12:\n" +
	"\vclaimer_key\x18\x02 \x01(\v2\x19.polycentric.v2.PublicKeyR\n" +
	"claimerKey\"f\n" +
	"\x1aJoinPairingSessionResponse\x12H\n" +
	"\rsession_state\x18\x01 \x01(\v2#.polycentric.v2.PairingSessionStateR\fsessionState2\xd1\x02\n" +
	"\x0ePairingService\x12h\n" +
	"\x11PutPairingSession\x12(.polycentric.v2.PutPairingSessionRequest\x1a).polycentric.v2.PutPairingSessionResponse\x12h\n" +
	"\x11GetPairingSession\x12(.polycentric.v2.GetPairingSessionRequest\x1a).polycentric.v2.GetPairingSessionResponse\x12k\n" +
	"\x12JoinPairingSession\x12).polycentric.v2.JoinPairingSessionRequest\x1a*.polycentric.v2.JoinPairingSessionResponseB\xd5\x01\n" +
	"\x12com.polycentric.v2B\x13PairingServiceProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_pairing_service_proto_rawDescOnce sync.Once
	file_polycentric_v2_pairing_service_proto_rawDescData []byte
)

func file_polycentric_v2_pairing_service_proto_rawDescGZIP() []byte {
	file_polycentric_v2_pairing_service_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_pairing_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_pairing_service_proto_rawDesc), len(file_polycentric_v2_pairing_service_proto_rawDesc)))
	})
	return file_polycentric_v2_pairing_service_proto_rawDescData
}

var file_polycentric_v2_pairing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_polycentric_v2_pairing_service_proto_goTypes = []any{
	(*PairingSessionDigest)(nil),       // 0: polycentric.v2.PairingSessionDigest
	(*PairingInfo)(nil),                // 1: polycentric.v2.PairingInfo
	(*IssuerPairingState)(nil),         // 2: polycentric.v2.IssuerPairingState
	(*SignedIssuerState)(nil),          // 3: polycentric.v2.SignedIssuerState
	(*PairingSessionState)(nil),        // 4: polycentric.v2.PairingSessionState
	(*GetPairingSessionRequest)(nil),   // 5: polycentric.v2.GetPairingSessionRequest
	(*PutPairingSessionRequest)(nil),   // 6: polycentric.v2.PutPairingSessionRequest
	(*PutPairingSessionResponse)(nil),  // 7: polycentric.v2.PutPairingSessionResponse
	(*GetPairingSessionResponse)(nil),  // 8: polycentric.v2.GetPairingSessionResponse
	(*JoinPairingSessionRequest)(nil),  // 9: polycentric.v2.JoinPairingSessionRequest
	(*JoinPairingSessionResponse)(nil), // 10: polycentric.v2.JoinPairingSessionResponse
	(*PublicKey)(nil),                  // 11: polycentric.v2.PublicKey
	(*EventBundle)(nil),                // 12: polycentric.v2.EventBundle
}
var file_polycentric_v2_pairing_service_proto_depIdxs = []int32{
	11, // 0: polycentric.v2.PairingSessionDigest.issuer_signer:type_name -> polycentric.v2.PublicKey
	12, // 1: polycentric.v2.IssuerPairingState.identity_state:type_name -> polycentric.v2.EventBundle
	3,  // 2: polycentric.v2.PairingSessionState.issuer_state:type_name -> polycentric.v2.SignedIssuerState
	11, // 3: polycentric.v2.PairingSessionState.claimers:type_name -> polycentric.v2.PublicKey
	3,  // 4: polycentric.v2.PutPairingSessionRequest.issuer_state:type_name -> polycentric.v2.SignedIssuerState
	4,  // 5: polycentric.v2.PutPairingSessionResponse.session_state:type_name -> polycentric.v2.PairingSessionState
	4,  // 6: polycentric.v2.GetPairingSessionResponse.session_state:type_name -> polycentric.v2.PairingSessionState
	11, // 7: polycentric.v2.JoinPairingSessionRequest.claimer_key:type_name -> polycentric.v2.PublicKey
	4,  // 8: polycentric.v2.JoinPairingSessionResponse.session_state:type_name -> polycentric.v2.PairingSessionState
	6,  // 9: polycentric.v2.PairingService.PutPairingSession:input_type -> polycentric.v2.PutPairingSessionRequest
	5,  // 10: polycentric.v2.PairingService.GetPairingSession:input_type -> polycentric.v2.GetPairingSessionRequest
	9,  // 11: polycentric.v2.PairingService.JoinPairingSession:input_type -> polycentric.v2.JoinPairingSessionRequest
	7,  // 12: polycentric.v2.PairingService.PutPairingSession:output_type -> polycentric.v2.PutPairingSessionResponse
	8,  // 13: polycentric.v2.PairingService.GetPairingSession:output_type -> polycentric.v2.GetPairingSessionResponse
	10, // 14: polycentric.v2.PairingService.JoinPairingSession:output_type -> polycentric.v2.JoinPairingSessionResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_polycentric_v2_pairing_service_proto_init() }
func file_polycentric_v2_pairing_service_proto_init() {
	if File_polycentric_v2_pairing_service_proto != nil {
		return
	}
	file_polycentric_v2_keypair_proto_init()
	file_polycentric_v2_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_pairing_service_proto_rawDesc), len(file_polycentric_v2_pairing_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_pairing_service_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_pairing_service_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_pairing_service_proto_msgTypes,
	}.Build()
	File_polycentric_v2_pairing_service_proto = out.File
	file_polycentric_v2_pairing_service_proto_goTypes = nil
	file_polycentric_v2_pairing_service_proto_depIdxs = nil
}
