// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/profile_service.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_polycentric_v2_profile_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_profile_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_profile_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type GetProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity's latest profile events.
	EventBundles []*EventBundle `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	// Side information needed to validate the bundles (the identity's
	// key chain).
	EventHints []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	// Distinct identities this identity follows.
	FollowingCount uint64 `protobuf:"varint,3,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	// Distinct identities following this identity.
	FollowersCount uint64 `protobuf:"varint,4,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_polycentric_v2_profile_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_profile_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_profile_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *GetProfileResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

func (x *GetProfileResponse) GetFollowingCount() uint64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *GetProfileResponse) GetFollowersCount() uint64 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

var File_polycentric_v2_profile_service_proto protoreflect.FileDescriptor

const file_polycentric_v2_profile_service_proto_rawDesc = "" +
	"\n" +
	"$polycentric/v2/profile_service.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/events.proto\"/\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\xe4\x01\n" +
	"\x12GetProfileResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\x12'\n" +
	"\x0ffollowing_count\x18\x03 \x01(\x04R\x0efollowingCount\x12'\n" +
	"\x0ffollowers_count\x18\x04 \x01(\x04R\x0efollowersCount2e\n" +
	"\x0eProfileService\x12S\n" +
	"\n" +
	"GetProfile\x12!.polycentric.v2.GetProfileRequest\x1a\".polycentric.v2.GetProfileResponseB\xd5\x01\n" +
	"\x12com.polycentric.v2B\x13ProfileServiceProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_profile_service_proto_rawDescOnce sync.Once
	file_polycentric_v2_profile_service_proto_rawDescData []byte
)

func file_polycentric_v2_profile_service_proto_rawDescGZIP() []byte {
	file_polycentric_v2_profile_service_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_profile_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_profile_service_proto_rawDesc), len(file_polycentric_v2_profile_service_proto_rawDesc)))
	})
	return file_polycentric_v2_profile_service_proto_rawDescData
}

var file_polycentric_v2_profile_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_polycentric_v2_profile_service_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: polycentric.v2.GetProfileRequest
	(*GetProfileResponse)(nil), // 1: polycentric.v2.GetProfileResponse
	(*EventBundle)(nil),        // 2: polycentric.v2.EventBundle
	(*EventHint)(nil),          // 3: polycentric.v2.EventHint
}
var file_polycentric_v2_profile_service_proto_depIdxs = []int32{
	2, // 0: polycentric.v2.GetProfileResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	3, // 1: polycentric.v2.GetProfileResponse.event_hints:type_name -> polycentric.v2.EventHint
	0, // 2: polycentric.v2.ProfileService.GetProfile:input_type -> polycentric.v2.GetProfileRequest
	1, // 3: polycentric.v2.ProfileService.GetProfile:output_type -> polycentric.v2.GetProfileResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_polycentric_v2_profile_service_proto_init() }
func file_polycentric_v2_profile_service_proto_init() {
	if File_polycentric_v2_profile_service_proto != nil {
		return
	}
	file_polycentric_v2_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_profile_service_proto_rawDesc), len(file_polycentric_v2_profile_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_profile_service_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_profile_service_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_profile_service_proto_msgTypes,
	}.Build()
	File_polycentric_v2_profile_service_proto = out.File
	file_polycentric_v2_profile_service_proto_goTypes = nil
	file_polycentric_v2_profile_service_proto_depIdxs = nil
}
