// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/search.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortUsersBy int32

const (
	// Default sorting by relevancy.
	SortUsersBy_SORT_USERS_BY_DEFAULT SortUsersBy = 0
	// Alphabetic order of profile name.
	SortUsersBy_SORT_USERS_BY_ALPHA SortUsersBy = 1
)

// Enum value maps for SortUsersBy.
var (
	SortUsersBy_name = map[int32]string{
		0: "SORT_USERS_BY_DEFAULT",
		1: "SORT_USERS_BY_ALPHA",
	}
	SortUsersBy_value = map[string]int32{
		"SORT_USERS_BY_DEFAULT": 0,
		"SORT_USERS_BY_ALPHA":   1,
	}
)

func (x SortUsersBy) Enum() *SortUsersBy {
	p := new(SortUsersBy)
	*p = x
	return p
}

func (x SortUsersBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortUsersBy) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_search_proto_enumTypes[0].Descriptor()
}

func (SortUsersBy) Type() protoreflect.EnumType {
	return &file_polycentric_v2_search_proto_enumTypes[0]
}

func (x SortUsersBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortUsersBy.Descriptor instead.
func (SortUsersBy) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{0}
}

type SortPostsBy int32

const (
	// Default sorting by relevancy.
	SortPostsBy_SORT_POSTS_BY_DEFAULT SortPostsBy = 0
	// Top post first.
	SortPostsBy_SORT_POSTS_BY_TOP SortPostsBy = 1
	// / Latests post first.
	SortPostsBy_SORT_POSTS_BY_LATEST SortPostsBy = 2
)

// Enum value maps for SortPostsBy.
var (
	SortPostsBy_name = map[int32]string{
		0: "SORT_POSTS_BY_DEFAULT",
		1: "SORT_POSTS_BY_TOP",
		2: "SORT_POSTS_BY_LATEST",
	}
	SortPostsBy_value = map[string]int32{
		"SORT_POSTS_BY_DEFAULT": 0,
		"SORT_POSTS_BY_TOP":     1,
		"SORT_POSTS_BY_LATEST":  2,
	}
)

func (x SortPostsBy) Enum() *SortPostsBy {
	p := new(SortPostsBy)
	*p = x
	return p
}

func (x SortPostsBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortPostsBy) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_search_proto_enumTypes[1].Descriptor()
}

func (SortPostsBy) Type() protoreflect.EnumType {
	return &file_polycentric_v2_search_proto_enumTypes[1]
}

func (x SortPostsBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortPostsBy.Descriptor instead.
func (SortPostsBy) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{1}
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SortBy        *SortUsersBy           `protobuf:"varint,2,opt,name=sort_by,json=sortBy,proto3,enum=polycentric.v2.SortUsersBy,oneof" json:"sort_by,omitempty"`
	PageParams    *PageParams            `protobuf:"bytes,3,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_polycentric_v2_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetSortBy() SortUsersBy {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return SortUsersBy_SORT_USERS_BY_DEFAULT
}

func (x *SearchUsersRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

type SearchPostsRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Query      string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SortBy     *SortPostsBy           `protobuf:"varint,2,opt,name=sort_by,json=sortBy,proto3,enum=polycentric.v2.SortPostsBy,oneof" json:"sort_by,omitempty"`
	PageParams *PageParams            `protobuf:"bytes,3,opt,name=page_params,json=pageParams,proto3,oneof" json:"page_params,omitempty"`
	// Label values for which the requester does not want to see content.
	OmitLabels    []string `protobuf:"bytes,4,rep,name=omit_labels,json=omitLabels,proto3" json:"omit_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsRequest) Reset() {
	*x = SearchPostsRequest{}
	mi := &file_polycentric_v2_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsRequest) ProtoMessage() {}

func (x *SearchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsRequest.ProtoReflect.Descriptor instead.
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPostsRequest) GetSortBy() SortPostsBy {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return SortPostsBy_SORT_POSTS_BY_DEFAULT
}

func (x *SearchPostsRequest) GetPageParams() *PageParams {
	if x != nil {
		return x.PageParams
	}
	return nil
}

func (x *SearchPostsRequest) GetOmitLabels() []string {
	if x != nil {
		return x.OmitLabels
	}
	return nil
}

type SearchUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relevant search results.
	Results  []*SearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PageInfo *PageInfo       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3,oneof" json:"page_info,omitempty"`
	// Relevant events for the events in the search results.
	EventHints    []*EventHint `protobuf:"bytes,3,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_polycentric_v2_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUsersResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchUsersResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *SearchUsersResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type SearchPostsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relevant search results.
	Results  []*SearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PageInfo *PageInfo       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3,oneof" json:"page_info,omitempty"`
	// Relevant events for the events in the search results.
	EventHints    []*EventHint `protobuf:"bytes,3,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsResponse) Reset() {
	*x = SearchPostsResponse{}
	mi := &file_polycentric_v2_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsResponse) ProtoMessage() {}

func (x *SearchPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsResponse.ProtoReflect.Descriptor instead.
func (*SearchPostsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPostsResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchPostsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *SearchPostsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type SearchResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventBundle *EventBundle           `protobuf:"bytes,1,opt,name=event_bundle,json=eventBundle,proto3" json:"event_bundle,omitempty"`
	// Search rank, higher means more relevant.
	Rank          float32 `protobuf:"fixed32,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_polycentric_v2_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetEventBundle() *EventBundle {
	if x != nil {
		return x.EventBundle
	}
	return nil
}

func (x *SearchResult) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_polycentric_v2_search_proto protoreflect.FileDescriptor

const file_polycentric_v2_search_proto_rawDesc = "" +
	"\n" +
	"\x1bpolycentric/v2/search.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1bpolycentric/v2/events.proto\"\xc3\x01\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x129\n" +
	"\asort_by\x18\x02 \x01(\x0e2\x1b.polycentric.v2.SortUsersByH\x00R\x06sortBy\x88\x01\x01\x12@\n" +
	"\vpage_params\x18\x03 \x01(\v2\x1a.polycentric.v2.PageParamsH\x01R\n" +
	"pageParams\x88\x01\x01B\n" +
	"\n" +
	"\b_sort_byB\x0e\n" +
	"\f_page_params\"\xe4\x01\n" +
	"\x12SearchPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x129\n" +
	"\asort_by\x18\x02 \x01(\x0e2\x1b.polycentric.v2.SortPostsByH\x00R\x06sortBy\x88\x01\x01\x12@\n" +
	"\vpage_params\x18\x03 \x01(\v2\x1a.polycentric.v2.PageParamsH\x01R\n" +
	"pageParams\x88\x01\x01\x12\x1f\n" +
	"\vomit_labels\x18\x04 \x03(\tR\n" +
	"omitLabelsB\n" +
	"\n" +
	"\b_sort_byB\x0e\n" +
	"\f_page_params\"\xd3\x01\n" +
	"\x13SearchUsersResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.polycentric.v2.SearchResultR\aresults\x12:\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.polycentric.v2.PageInfoH\x00R\bpageInfo\x88\x01\x01\x12:\n" +
	"\vevent_hints\x18\x03 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHintsB\f\n" +
	"\n" +
	"_page_info\"\xd3\x01\n" +
	"\x13SearchPostsResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.polycentric.v2.SearchResultR\aresults\x12:\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.polycentric.v2.PageInfoH\x00R\bpageInfo\x88\x01\x01\x12:\n" +
	"\vevent_hints\x18\x03 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHintsB\f\n" +
	"\n" +
	"_page_info\"b\n" +
	"\fSearchResult\x12>\n" +
	"\fevent_bundle\x18\x01 \x01(\v2\x1b.polycentric.v2.EventBundleR\veventBundle\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x02R\x04rank*A\n" +
	"\vSortUsersBy\x12\x19\n" +
	"\x15SORT_USERS_BY_DEFAULT\x10\x00\x12\x17\n" +
	"\x13SORT_USERS_BY_ALPHA\x10\x01*Y\n" +
	"\vSortPostsBy\x12\x19\n" +
	"\x15SORT_POSTS_BY_DEFAULT\x10\x00\x12\x15\n" +
	"\x11SORT_POSTS_BY_TOP\x10\x01\x12\x18\n" +
	"\x14SORT_POSTS_BY_LATEST\x10\x022\xbf\x01\n" +
	"\rSearchService\x12V\n" +
	"\vSearchUsers\x12\".polycentric.v2.SearchUsersRequest\x1a#.polycentric.v2.SearchUsersResponse\x12V\n" +
	"\vSearchPosts\x12\".polycentric.v2.SearchPostsRequest\x1a#.polycentric.v2.SearchPostsResponseB\xcd\x01\n" +
	"\x12com.polycentric.v2B\vSearchProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_search_proto_rawDescOnce sync.Once
	file_polycentric_v2_search_proto_rawDescData []byte
)

func file_polycentric_v2_search_proto_rawDescGZIP() []byte {
	file_polycentric_v2_search_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_search_proto_rawDesc), len(file_polycentric_v2_search_proto_rawDesc)))
	})
	return file_polycentric_v2_search_proto_rawDescData
}

var file_polycentric_v2_search_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_polycentric_v2_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_polycentric_v2_search_proto_goTypes = []any{
	(SortUsersBy)(0),            // 0: polycentric.v2.SortUsersBy
	(SortPostsBy)(0),            // 1: polycentric.v2.SortPostsBy
	(*SearchUsersRequest)(nil),  // 2: polycentric.v2.SearchUsersRequest
	(*SearchPostsRequest)(nil),  // 3: polycentric.v2.SearchPostsRequest
	(*SearchUsersResponse)(nil), // 4: polycentric.v2.SearchUsersResponse
	(*SearchPostsResponse)(nil), // 5: polycentric.v2.SearchPostsResponse
	(*SearchResult)(nil),        // 6: polycentric.v2.SearchResult
	(*PageParams)(nil),          // 7: polycentric.v2.PageParams
	(*PageInfo)(nil),            // 8: polycentric.v2.PageInfo
	(*EventHint)(nil),           // 9: polycentric.v2.EventHint
	(*EventBundle)(nil),         // 10: polycentric.v2.EventBundle
}
var file_polycentric_v2_search_proto_depIdxs = []int32{
	0,  // 0: polycentric.v2.SearchUsersRequest.sort_by:type_name -> polycentric.v2.SortUsersBy
	7,  // 1: polycentric.v2.SearchUsersRequest.page_params:type_name -> polycentric.v2.PageParams
	1,  // 2: polycentric.v2.SearchPostsRequest.sort_by:type_name -> polycentric.v2.SortPostsBy
	7,  // 3: polycentric.v2.SearchPostsRequest.page_params:type_name -> polycentric.v2.PageParams
	6,  // 4: polycentric.v2.SearchUsersResponse.results:type_name -> polycentric.v2.SearchResult
	8,  // 5: polycentric.v2.SearchUsersResponse.page_info:type_name -> polycentric.v2.PageInfo
	9,  // 6: polycentric.v2.SearchUsersResponse.event_hints:type_name -> polycentric.v2.EventHint
	6,  // 7: polycentric.v2.SearchPostsResponse.results:type_name -> polycentric.v2.SearchResult
	8,  // 8: polycentric.v2.SearchPostsResponse.page_info:type_name -> polycentric.v2.PageInfo
	9,  // 9: polycentric.v2.SearchPostsResponse.event_hints:type_name -> polycentric.v2.EventHint
	10, // 10: polycentric.v2.SearchResult.event_bundle:type_name -> polycentric.v2.EventBundle
	2,  // 11: polycentric.v2.SearchService.SearchUsers:input_type -> polycentric.v2.SearchUsersRequest
	3,  // 12: polycentric.v2.SearchService.SearchPosts:input_type -> polycentric.v2.SearchPostsRequest
	4,  // 13: polycentric.v2.SearchService.SearchUsers:output_type -> polycentric.v2.SearchUsersResponse
	5,  // 14: polycentric.v2.SearchService.SearchPosts:output_type -> polycentric.v2.SearchPostsResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_polycentric_v2_search_proto_init() }
func file_polycentric_v2_search_proto_init() {
	if File_polycentric_v2_search_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_events_proto_init()
	file_polycentric_v2_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_polycentric_v2_search_proto_msgTypes[1].OneofWrappers = []any{}
	file_polycentric_v2_search_proto_msgTypes[2].OneofWrappers = []any{}
	file_polycentric_v2_search_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_search_proto_rawDesc), len(file_polycentric_v2_search_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_search_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_search_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_search_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_search_proto_msgTypes,
	}.Build()
	File_polycentric_v2_search_proto = out.File
	file_polycentric_v2_search_proto_goTypes = nil
	file_polycentric_v2_search_proto_depIdxs = nil
}
