// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/server.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Current version the server is running on.
type ServerVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersion) Reset() {
	*x = ServerVersion{}
	mi := &file_polycentric_v2_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersion) ProtoMessage() {}

func (x *ServerVersion) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersion.ProtoReflect.Descriptor instead.
func (*ServerVersion) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// *
// Relevant information about the current server, such as version, public endpoints, etc.
type ServerInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *ServerVersion         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// URL used to resolve HTTP assets (blobs, images, etc)
	CdnUrl        string `protobuf:"bytes,2,opt,name=cdn_url,json=cdnUrl,proto3" json:"cdn_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_polycentric_v2_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetVersion() *ServerVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ServerInfo) GetCdnUrl() string {
	if x != nil {
		return x.CdnUrl
	}
	return ""
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_polycentric_v2_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_server_proto_rawDescGZIP(), []int{2}
}

type GetServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerInfo    *ServerInfo            `protobuf:"bytes,1,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_polycentric_v2_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerInfoResponse) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

type SignedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	MessageBytes  []byte                 `protobuf:"bytes,2,opt,name=message_bytes,json=messageBytes,proto3" json:"message_bytes,omitempty"`
	PublicKey     *PublicKey             `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_polycentric_v2_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_server_proto_rawDescGZIP(), []int{4}
}

func (x *SignedMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedMessage) GetMessageBytes() []byte {
	if x != nil {
		return x.MessageBytes
	}
	return nil
}

func (x *SignedMessage) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_polycentric_v2_server_proto protoreflect.FileDescriptor

const file_polycentric_v2_server_proto_rawDesc = "" +
	"\n" +
	"\x1bpolycentric/v2/server.proto\x12\x0epolycentric.v2\x1a\x1cpolycentric/v2/keypair.proto\")\n" +
	"\rServerVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"^\n" +
	"\n" +
	"ServerInfo\x127\n" +
	"\aversion\x18\x01 \x01(\v2\x1d.polycentric.v2.ServerVersionR\aversion\x12\x17\n" +
	"\acdn_url\x18\x02 \x01(\tR\x06cdnUrl\"\x16\n" +
	"\x14GetServerInfoRequest\"T\n" +
	"\x15GetServerInfoResponse\x12;\n" +
	"\vserver_info\x18\x01 \x01(\v2\x1a.polycentric.v2.ServerInfoR\n" +
	"serverInfo\"\x8c\x01\n" +
	"\rSignedMessage\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12#\n" +
	"\rmessage_bytes\x18\x02 \x01(\fR\fmessageBytes\x128\n" +
	"\n" +
	"public_key\x18\x03 \x01(\v2\x19.polycentric.v2.PublicKeyR\tpublicKey2g\n" +
	"\rServerService\x12V\n" +
	"\aGetInfo\x12$.polycentric.v2.GetServerInfoRequest\x1a%.polycentric.v2.GetServerInfoResponseB\xcd\x01\n" +
	"\x12com.polycentric.v2B\vServerProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_server_proto_rawDescOnce sync.Once
	file_polycentric_v2_server_proto_rawDescData []byte
)

func file_polycentric_v2_server_proto_rawDescGZIP() []byte {
	file_polycentric_v2_server_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_server_proto_rawDesc), len(file_polycentric_v2_server_proto_rawDesc)))
	})
	return file_polycentric_v2_server_proto_rawDescData
}

var file_polycentric_v2_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_polycentric_v2_server_proto_goTypes = []any{
	(*ServerVersion)(nil),         // 0: polycentric.v2.ServerVersion
	(*ServerInfo)(nil),            // 1: polycentric.v2.ServerInfo
	(*GetServerInfoRequest)(nil),  // 2: polycentric.v2.GetServerInfoRequest
	(*GetServerInfoResponse)(nil), // 3: polycentric.v2.GetServerInfoResponse
	(*SignedMessage)(nil),         // 4: polycentric.v2.SignedMessage
	(*PublicKey)(nil),             // 5: polycentric.v2.PublicKey
}
var file_polycentric_v2_server_proto_depIdxs = []int32{
	0, // 0: polycentric.v2.ServerInfo.version:type_name -> polycentric.v2.ServerVersion
	1, // 1: polycentric.v2.GetServerInfoResponse.server_info:type_name -> polycentric.v2.ServerInfo
	5, // 2: polycentric.v2.SignedMessage.public_key:type_name -> polycentric.v2.PublicKey
	2, // 3: polycentric.v2.ServerService.GetInfo:input_type -> polycentric.v2.GetServerInfoRequest
	3, // 4: polycentric.v2.ServerService.GetInfo:output_type -> polycentric.v2.GetServerInfoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_polycentric_v2_server_proto_init() }
func file_polycentric_v2_server_proto_init() {
	if File_polycentric_v2_server_proto != nil {
		return
	}
	file_polycentric_v2_keypair_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_server_proto_rawDesc), len(file_polycentric_v2_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_server_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_server_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_server_proto_msgTypes,
	}.Build()
	File_polycentric_v2_server_proto = out.File
	file_polycentric_v2_server_proto_goTypes = nil
	file_polycentric_v2_server_proto_depIdxs = nil
}
