// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/verifications_service.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A claim with the verification state around it, so lists can show each
// claim's verified status from a single response.
type VerificationClaimBundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The VerificationClaim event.
	Claim *EventBundle `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	// VerificationTarget events published by the claim's owner
	Targets []*EventBundle `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	// VerificationVerify events.
	Verifies      []*EventBundle `protobuf:"bytes,3,rep,name=verifies,proto3" json:"verifies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationClaimBundle) Reset() {
	*x = VerificationClaimBundle{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationClaimBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationClaimBundle) ProtoMessage() {}

func (x *VerificationClaimBundle) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationClaimBundle.ProtoReflect.Descriptor instead.
func (*VerificationClaimBundle) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationClaimBundle) GetClaim() *EventBundle {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *VerificationClaimBundle) GetTargets() []*EventBundle {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *VerificationClaimBundle) GetVerifies() []*EventBundle {
	if x != nil {
		return x.Verifies
	}
	return nil
}

type ListVerificationClaimsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClaimedByIdentity string                 `protobuf:"bytes,1,opt,name=claimed_by_identity,json=claimedByIdentity,proto3" json:"claimed_by_identity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListVerificationClaimsRequest) Reset() {
	*x = ListVerificationClaimsRequest{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationClaimsRequest) ProtoMessage() {}

func (x *ListVerificationClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationClaimsRequest.ProtoReflect.Descriptor instead.
func (*ListVerificationClaimsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListVerificationClaimsRequest) GetClaimedByIdentity() string {
	if x != nil {
		return x.ClaimedByIdentity
	}
	return ""
}

type ListVerificationClaimsResponse struct {
	state        protoimpl.MessageState     `protogen:"open.v1"`
	ClaimBundles []*VerificationClaimBundle `protobuf:"bytes,1,rep,name=claim_bundles,json=claimBundles,proto3" json:"claim_bundles,omitempty"`
	// Additional events that may be helpful, like relevant identity and profiles
	EventHints    []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerificationClaimsResponse) Reset() {
	*x = ListVerificationClaimsResponse{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationClaimsResponse) ProtoMessage() {}

func (x *ListVerificationClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationClaimsResponse.ProtoReflect.Descriptor instead.
func (*ListVerificationClaimsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListVerificationClaimsResponse) GetClaimBundles() []*VerificationClaimBundle {
	if x != nil {
		return x.ClaimBundles
	}
	return nil
}

func (x *ListVerificationClaimsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type ListVerificationTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimEventKey *EventKey              `protobuf:"bytes,1,opt,name=claim_event_key,json=claimEventKey,proto3" json:"claim_event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerificationTargetsRequest) Reset() {
	*x = ListVerificationTargetsRequest{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationTargetsRequest) ProtoMessage() {}

func (x *ListVerificationTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationTargetsRequest.ProtoReflect.Descriptor instead.
func (*ListVerificationTargetsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListVerificationTargetsRequest) GetClaimEventKey() *EventKey {
	if x != nil {
		return x.ClaimEventKey
	}
	return nil
}

type ListVerificationTargetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VerificationTarget events for the claim, published by the claim's
	// owner — who has been asked to verify.
	EventBundles []*EventBundle `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	// Additional events that may be helpful, like relevant identity and profiles
	EventHints    []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerificationTargetsResponse) Reset() {
	*x = ListVerificationTargetsResponse{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationTargetsResponse) ProtoMessage() {}

func (x *ListVerificationTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationTargetsResponse.ProtoReflect.Descriptor instead.
func (*ListVerificationTargetsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListVerificationTargetsResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *ListVerificationTargetsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type ListVerificationVerifiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimEventKey *EventKey              `protobuf:"bytes,1,opt,name=claim_event_key,json=claimEventKey,proto3" json:"claim_event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerificationVerifiesRequest) Reset() {
	*x = ListVerificationVerifiesRequest{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationVerifiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationVerifiesRequest) ProtoMessage() {}

func (x *ListVerificationVerifiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationVerifiesRequest.ProtoReflect.Descriptor instead.
func (*ListVerificationVerifiesRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListVerificationVerifiesRequest) GetClaimEventKey() *EventKey {
	if x != nil {
		return x.ClaimEventKey
	}
	return nil
}

type ListVerificationVerifiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VerificationVerify events for the claim.
	EventBundles []*EventBundle `protobuf:"bytes,1,rep,name=event_bundles,json=eventBundles,proto3" json:"event_bundles,omitempty"`
	// Additional events that may be helpful, like relevant identity and profiles
	EventHints    []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerificationVerifiesResponse) Reset() {
	*x = ListVerificationVerifiesResponse{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerificationVerifiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerificationVerifiesResponse) ProtoMessage() {}

func (x *ListVerificationVerifiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerificationVerifiesResponse.ProtoReflect.Descriptor instead.
func (*ListVerificationVerifiesResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListVerificationVerifiesResponse) GetEventBundles() []*EventBundle {
	if x != nil {
		return x.EventBundles
	}
	return nil
}

func (x *ListVerificationVerifiesResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

type ListTargetedVerificationClaimsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetIdentity string                 `protobuf:"bytes,1,opt,name=target_identity,json=targetIdentity,proto3" json:"target_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTargetedVerificationClaimsRequest) Reset() {
	*x = ListTargetedVerificationClaimsRequest{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetedVerificationClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetedVerificationClaimsRequest) ProtoMessage() {}

func (x *ListTargetedVerificationClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetedVerificationClaimsRequest.ProtoReflect.Descriptor instead.
func (*ListTargetedVerificationClaimsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListTargetedVerificationClaimsRequest) GetTargetIdentity() string {
	if x != nil {
		return x.TargetIdentity
	}
	return ""
}

type ListTargetedVerificationClaimsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Claims whose owner targeted `target_identity`. The 'inbox'.
	ClaimBundles []*VerificationClaimBundle `protobuf:"bytes,1,rep,name=claim_bundles,json=claimBundles,proto3" json:"claim_bundles,omitempty"`
	// Additional events that may be helpful, like relevant identity and profiles
	EventHints    []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetedVerificationClaimsResponse) Reset() {
	*x = ListTargetedVerificationClaimsResponse{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetedVerificationClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetedVerificationClaimsResponse) ProtoMessage() {}

func (x *ListTargetedVerificationClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetedVerificationClaimsResponse.ProtoReflect.Descriptor instead.
func (*ListTargetedVerificationClaimsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListTargetedVerificationClaimsResponse) GetClaimBundles() []*VerificationClaimBundle {
	if x != nil {
		return x.ClaimBundles
	}
	return nil
}

func (x *ListTargetedVerificationClaimsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

// Reverse lookup: find the identities that claim something, starting from the
// claim's field values rather than from an identity. Answers "who claims this
// (e.g. this platform channel, this occupation), verified by a trusted party?"
// — the inverse of the identity-keyed queries above. Works for any claim type.
type ResolveVerifiedClaimsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional type scope: restrict to claims of exactly this schema, by the
	// schema's content digest. Unset (or empty value) = any schema. This is the
	// schema's content-addressed identifier; it only groups cross-client when
	// claimants pin identical canonical schema bytes.
	SchemaDigest *ContentDigest `protobuf:"bytes,1,opt,name=schema_digest,json=schemaDigest,proto3" json:"schema_digest,omitempty"`
	// Field key/value pairs a claim's (STRING) fields must contain, matched by
	// JSONB containment. A claim matches only when it contains every supplied
	// pair (AND); it may carry additional fields. A claim missing any supplied
	// field does not match. May be empty when `schema_digest` scopes the query.
	Fields map[string]string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Only return claims that carry a VerificationVerify authored by one of
	// these identities (the trust roots). Required and non-empty — this is what
	// makes a match "verified" rather than merely "claimed".
	VerifiedByIdentities []string `protobuf:"bytes,3,rep,name=verified_by_identities,json=verifiedByIdentities,proto3" json:"verified_by_identities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolveVerifiedClaimsRequest) Reset() {
	*x = ResolveVerifiedClaimsRequest{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVerifiedClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVerifiedClaimsRequest) ProtoMessage() {}

func (x *ResolveVerifiedClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVerifiedClaimsRequest.ProtoReflect.Descriptor instead.
func (*ResolveVerifiedClaimsRequest) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveVerifiedClaimsRequest) GetSchemaDigest() *ContentDigest {
	if x != nil {
		return x.SchemaDigest
	}
	return nil
}

func (x *ResolveVerifiedClaimsRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ResolveVerifiedClaimsRequest) GetVerifiedByIdentities() []string {
	if x != nil {
		return x.VerifiedByIdentities
	}
	return nil
}

type ResolveVerifiedClaimsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching claims, each wrapped with its targets and verifies (the verifies
	// include at least one authored by a trusted identity).
	ClaimBundles []*VerificationClaimBundle `protobuf:"bytes,1,rep,name=claim_bundles,json=claimBundles,proto3" json:"claim_bundles,omitempty"`
	// Additional events that may be helpful, like relevant identity and profiles
	EventHints    []*EventHint `protobuf:"bytes,2,rep,name=event_hints,json=eventHints,proto3" json:"event_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveVerifiedClaimsResponse) Reset() {
	*x = ResolveVerifiedClaimsResponse{}
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVerifiedClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVerifiedClaimsResponse) ProtoMessage() {}

func (x *ResolveVerifiedClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVerifiedClaimsResponse.ProtoReflect.Descriptor instead.
func (*ResolveVerifiedClaimsResponse) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveVerifiedClaimsResponse) GetClaimBundles() []*VerificationClaimBundle {
	if x != nil {
		return x.ClaimBundles
	}
	return nil
}

func (x *ResolveVerifiedClaimsResponse) GetEventHints() []*EventHint {
	if x != nil {
		return x.EventHints
	}
	return nil
}

var File_polycentric_v2_verifications_service_proto protoreflect.FileDescriptor

const file_polycentric_v2_verifications_service_proto_rawDesc = "" +
	"\n" +
	"*polycentric/v2/verifications_service.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1epolycentric/v2/event_key.proto\x1a\x1bpolycentric/v2/events.proto\"\xbc\x01\n" +
	"\x17VerificationClaimBundle\x121\n" +
	"\x05claim\x18\x01 \x01(\v2\x1b.polycentric.v2.EventBundleR\x05claim\x125\n" +
	"\atargets\x18\x02 \x03(\v2\x1b.polycentric.v2.EventBundleR\atargets\x127\n" +
	"\bverifies\x18\x03 \x03(\v2\x1b.polycentric.v2.EventBundleR\bverifies\"O\n" +
	"\x1dListVerificationClaimsRequest\x12.\n" +
	"\x13claimed_by_identity\x18\x01 \x01(\tR\x11claimedByIdentity\"\xaa\x01\n" +
	"\x1eListVerificationClaimsResponse\x12L\n" +
	"\rclaim_bundles\x18\x01 \x03(\v2'.polycentric.v2.VerificationClaimBundleR\fclaimBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"b\n" +
	"\x1eListVerificationTargetsRequest\x12@\n" +
	"\x0fclaim_event_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\rclaimEventKey\"\x9f\x01\n" +
	"\x1fListVerificationTargetsResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"c\n" +
	"\x1fListVerificationVerifiesRequest\x12@\n" +
	"\x0fclaim_event_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\rclaimEventKey\"\xa0\x01\n" +
	" ListVerificationVerifiesResponse\x12@\n" +
	"\revent_bundles\x18\x01 \x03(\v2\x1b.polycentric.v2.EventBundleR\feventBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"P\n" +
	"%ListTargetedVerificationClaimsRequest\x12'\n" +
	"\x0ftarget_identity\x18\x01 \x01(\tR\x0etargetIdentity\"\xb2\x01\n" +
	"&ListTargetedVerificationClaimsResponse\x12L\n" +
	"\rclaim_bundles\x18\x01 \x03(\v2'.polycentric.v2.VerificationClaimBundleR\fclaimBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints\"\xa5\x02\n" +
	"\x1cResolveVerifiedClaimsRequest\x12B\n" +
	"\rschema_digest\x18\x01 \x01(\v2\x1d.polycentric.v2.ContentDigestR\fschemaDigest\x12P\n" +
	"\x06fields\x18\x02 \x03(\v28.polycentric.v2.ResolveVerifiedClaimsRequest.FieldsEntryR\x06fields\x124\n" +
	"\x16verified_by_identities\x18\x03 \x03(\tR\x14verifiedByIdentities\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x1dResolveVerifiedClaimsResponse\x12L\n" +
	"\rclaim_bundles\x18\x01 \x03(\v2'.polycentric.v2.VerificationClaimBundleR\fclaimBundles\x12:\n" +
	"\vevent_hints\x18\x02 \x03(\v2\x19.polycentric.v2.EventHintR\n" +
	"eventHints2\x92\x05\n" +
	"\x14VerificationsService\x12w\n" +
	"\x16ListVerificationClaims\x12-.polycentric.v2.ListVerificationClaimsRequest\x1a..polycentric.v2.ListVerificationClaimsResponse\x12z\n" +
	"\x17ListVerificationTargets\x12..polycentric.v2.ListVerificationTargetsRequest\x1a/.polycentric.v2.ListVerificationTargetsResponse\x12}\n" +
	"\x18ListVerificationVerifies\x12/.polycentric.v2.ListVerificationVerifiesRequest\x1a0.polycentric.v2.ListVerificationVerifiesResponse\x12\x8f\x01\n" +
	"\x1eListTargetedVerificationClaims\x125.polycentric.v2.ListTargetedVerificationClaimsRequest\x1a6.polycentric.v2.ListTargetedVerificationClaimsResponse\x12t\n" +
	"\x15ResolveVerifiedClaims\x12,.polycentric.v2.ResolveVerifiedClaimsRequest\x1a-.polycentric.v2.ResolveVerifiedClaimsResponseB\xdb\x01\n" +
	"\x12com.polycentric.v2B\x19VerificationsServiceProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_verifications_service_proto_rawDescOnce sync.Once
	file_polycentric_v2_verifications_service_proto_rawDescData []byte
)

func file_polycentric_v2_verifications_service_proto_rawDescGZIP() []byte {
	file_polycentric_v2_verifications_service_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_verifications_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_verifications_service_proto_rawDesc), len(file_polycentric_v2_verifications_service_proto_rawDesc)))
	})
	return file_polycentric_v2_verifications_service_proto_rawDescData
}

var file_polycentric_v2_verifications_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_polycentric_v2_verifications_service_proto_goTypes = []any{
	(*VerificationClaimBundle)(nil),                // 0: polycentric.v2.VerificationClaimBundle
	(*ListVerificationClaimsRequest)(nil),          // 1: polycentric.v2.ListVerificationClaimsRequest
	(*ListVerificationClaimsResponse)(nil),         // 2: polycentric.v2.ListVerificationClaimsResponse
	(*ListVerificationTargetsRequest)(nil),         // 3: polycentric.v2.ListVerificationTargetsRequest
	(*ListVerificationTargetsResponse)(nil),        // 4: polycentric.v2.ListVerificationTargetsResponse
	(*ListVerificationVerifiesRequest)(nil),        // 5: polycentric.v2.ListVerificationVerifiesRequest
	(*ListVerificationVerifiesResponse)(nil),       // 6: polycentric.v2.ListVerificationVerifiesResponse
	(*ListTargetedVerificationClaimsRequest)(nil),  // 7: polycentric.v2.ListTargetedVerificationClaimsRequest
	(*ListTargetedVerificationClaimsResponse)(nil), // 8: polycentric.v2.ListTargetedVerificationClaimsResponse
	(*ResolveVerifiedClaimsRequest)(nil),           // 9: polycentric.v2.ResolveVerifiedClaimsRequest
	(*ResolveVerifiedClaimsResponse)(nil),          // 10: polycentric.v2.ResolveVerifiedClaimsResponse
	nil,                                            // 11: polycentric.v2.ResolveVerifiedClaimsRequest.FieldsEntry
	(*EventBundle)(nil),                            // 12: polycentric.v2.EventBundle
	(*EventHint)(nil),                              // 13: polycentric.v2.EventHint
	(*EventKey)(nil),                               // 14: polycentric.v2.EventKey
	(*ContentDigest)(nil),                          // 15: polycentric.v2.ContentDigest
}
var file_polycentric_v2_verifications_service_proto_depIdxs = []int32{
	12, // 0: polycentric.v2.VerificationClaimBundle.claim:type_name -> polycentric.v2.EventBundle
	12, // 1: polycentric.v2.VerificationClaimBundle.targets:type_name -> polycentric.v2.EventBundle
	12, // 2: polycentric.v2.VerificationClaimBundle.verifies:type_name -> polycentric.v2.EventBundle
	0,  // 3: polycentric.v2.ListVerificationClaimsResponse.claim_bundles:type_name -> polycentric.v2.VerificationClaimBundle
	13, // 4: polycentric.v2.ListVerificationClaimsResponse.event_hints:type_name -> polycentric.v2.EventHint
	14, // 5: polycentric.v2.ListVerificationTargetsRequest.claim_event_key:type_name -> polycentric.v2.EventKey
	12, // 6: polycentric.v2.ListVerificationTargetsResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	13, // 7: polycentric.v2.ListVerificationTargetsResponse.event_hints:type_name -> polycentric.v2.EventHint
	14, // 8: polycentric.v2.ListVerificationVerifiesRequest.claim_event_key:type_name -> polycentric.v2.EventKey
	12, // 9: polycentric.v2.ListVerificationVerifiesResponse.event_bundles:type_name -> polycentric.v2.EventBundle
	13, // 10: polycentric.v2.ListVerificationVerifiesResponse.event_hints:type_name -> polycentric.v2.EventHint
	0,  // 11: polycentric.v2.ListTargetedVerificationClaimsResponse.claim_bundles:type_name -> polycentric.v2.VerificationClaimBundle
	13, // 12: polycentric.v2.ListTargetedVerificationClaimsResponse.event_hints:type_name -> polycentric.v2.EventHint
	15, // 13: polycentric.v2.ResolveVerifiedClaimsRequest.schema_digest:type_name -> polycentric.v2.ContentDigest
	11, // 14: polycentric.v2.ResolveVerifiedClaimsRequest.fields:type_name -> polycentric.v2.ResolveVerifiedClaimsRequest.FieldsEntry
	0,  // 15: polycentric.v2.ResolveVerifiedClaimsResponse.claim_bundles:type_name -> polycentric.v2.VerificationClaimBundle
	13, // 16: polycentric.v2.ResolveVerifiedClaimsResponse.event_hints:type_name -> polycentric.v2.EventHint
	1,  // 17: polycentric.v2.VerificationsService.ListVerificationClaims:input_type -> polycentric.v2.ListVerificationClaimsRequest
	3,  // 18: polycentric.v2.VerificationsService.ListVerificationTargets:input_type -> polycentric.v2.ListVerificationTargetsRequest
	5,  // 19: polycentric.v2.VerificationsService.ListVerificationVerifies:input_type -> polycentric.v2.ListVerificationVerifiesRequest
	7,  // 20: polycentric.v2.VerificationsService.ListTargetedVerificationClaims:input_type -> polycentric.v2.ListTargetedVerificationClaimsRequest
	9,  // 21: polycentric.v2.VerificationsService.ResolveVerifiedClaims:input_type -> polycentric.v2.ResolveVerifiedClaimsRequest
	2,  // 22: polycentric.v2.VerificationsService.ListVerificationClaims:output_type -> polycentric.v2.ListVerificationClaimsResponse
	4,  // 23: polycentric.v2.VerificationsService.ListVerificationTargets:output_type -> polycentric.v2.ListVerificationTargetsResponse
	6,  // 24: polycentric.v2.VerificationsService.ListVerificationVerifies:output_type -> polycentric.v2.ListVerificationVerifiesResponse
	8,  // 25: polycentric.v2.VerificationsService.ListTargetedVerificationClaims:output_type -> polycentric.v2.ListTargetedVerificationClaimsResponse
	10, // 26: polycentric.v2.VerificationsService.ResolveVerifiedClaims:output_type -> polycentric.v2.ResolveVerifiedClaimsResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_polycentric_v2_verifications_service_proto_init() }
func file_polycentric_v2_verifications_service_proto_init() {
	if File_polycentric_v2_verifications_service_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_event_key_proto_init()
	file_polycentric_v2_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_verifications_service_proto_rawDesc), len(file_polycentric_v2_verifications_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polycentric_v2_verifications_service_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_verifications_service_proto_depIdxs,
		MessageInfos:      file_polycentric_v2_verifications_service_proto_msgTypes,
	}.Build()
	File_polycentric_v2_verifications_service_proto = out.File
	file_polycentric_v2_verifications_service_proto_goTypes = nil
	file_polycentric_v2_verifications_service_proto_depIdxs = nil
}
