// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polycentric/v2/verifications.proto

package polycentricv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical byte encoding per kind (claims are hashed, so reject non-canonical):
//
//	STRING -> UTF-8        INT   -> int64 little-endian, 8 bytes
//	BOOL   -> 0x00 / 0x01  BYTES -> verbatim
type FieldKind int32

const (
	FieldKind_FIELD_KIND_UNSPECIFIED FieldKind = 0
	FieldKind_FIELD_KIND_STRING      FieldKind = 1
	FieldKind_FIELD_KIND_INT         FieldKind = 2
	FieldKind_FIELD_KIND_BOOL        FieldKind = 3
	FieldKind_FIELD_KIND_BYTES       FieldKind = 4
)

// Enum value maps for FieldKind.
var (
	FieldKind_name = map[int32]string{
		0: "FIELD_KIND_UNSPECIFIED",
		1: "FIELD_KIND_STRING",
		2: "FIELD_KIND_INT",
		3: "FIELD_KIND_BOOL",
		4: "FIELD_KIND_BYTES",
	}
	FieldKind_value = map[string]int32{
		"FIELD_KIND_UNSPECIFIED": 0,
		"FIELD_KIND_STRING":      1,
		"FIELD_KIND_INT":         2,
		"FIELD_KIND_BOOL":        3,
		"FIELD_KIND_BYTES":       4,
	}
)

func (x FieldKind) Enum() *FieldKind {
	p := new(FieldKind)
	*p = x
	return p
}

func (x FieldKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldKind) Descriptor() protoreflect.EnumDescriptor {
	return file_polycentric_v2_verifications_proto_enumTypes[0].Descriptor()
}

func (FieldKind) Type() protoreflect.EnumType {
	return &file_polycentric_v2_verifications_proto_enumTypes[0]
}

func (x FieldKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldKind.Descriptor instead.
func (FieldKind) EnumDescriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{0}
}

// Schema that defines the verification
// These are self describing schemas and are intended to be specified in
// a `VerificationClaim`.
type VerificationSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human readable name of the schema (ie. X Verification).
	Name          string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*FieldDef `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationSchema) Reset() {
	*x = VerificationSchema{}
	mi := &file_polycentric_v2_verifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSchema) ProtoMessage() {}

func (x *VerificationSchema) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSchema.ProtoReflect.Descriptor instead.
func (*VerificationSchema) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerificationSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VerificationSchema) GetFields() []*FieldDef {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FieldDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key used in VerificationClaim.fields, e.g. "handle", "proof_url".
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// How to decode this field's bytes.
	Kind FieldKind `protobuf:"varint,2,opt,name=kind,proto3,enum=polycentric.v2.FieldKind" json:"kind,omitempty"`
	// Semantic refinement of kind: "url", "email", "iso8601-date", "hex".
	// Free-form so new formats need no proto change.
	Format        string  `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Required      bool    `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Description   string  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Regex         *string `protobuf:"bytes,6,opt,name=regex,proto3,oneof" json:"regex,omitempty"`
	MaxLen        *uint32 `protobuf:"varint,7,opt,name=max_len,json=maxLen,proto3,oneof" json:"max_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDef) Reset() {
	*x = FieldDef{}
	mi := &file_polycentric_v2_verifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDef) ProtoMessage() {}

func (x *FieldDef) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDef.ProtoReflect.Descriptor instead.
func (*FieldDef) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{1}
}

func (x *FieldDef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldDef) GetKind() FieldKind {
	if x != nil {
		return x.Kind
	}
	return FieldKind_FIELD_KIND_UNSPECIFIED
}

func (x *FieldDef) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FieldDef) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldDef) GetRegex() string {
	if x != nil && x.Regex != nil {
		return *x.Regex
	}
	return ""
}

func (x *FieldDef) GetMaxLen() uint32 {
	if x != nil && x.MaxLen != nil {
		return *x.MaxLen
	}
	return 0
}

// Protobuf serialization is non-deteministic. We hash the serialized schema
// so we have the canonical hash - this aids with grouping of claims.
type SerializedVerificationSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized VerificationSchema.
	SchemaBytes []byte `protobuf:"bytes,1,opt,name=schema_bytes,json=schemaBytes,proto3" json:"schema_bytes,omitempty"`
	// Digest over schema_bytes. Verify digest == hash(schema_bytes).
	Digest        *ContentDigest `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializedVerificationSchema) Reset() {
	*x = SerializedVerificationSchema{}
	mi := &file_polycentric_v2_verifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedVerificationSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedVerificationSchema) ProtoMessage() {}

func (x *SerializedVerificationSchema) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedVerificationSchema.ProtoReflect.Descriptor instead.
func (*SerializedVerificationSchema) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{2}
}

func (x *SerializedVerificationSchema) GetSchemaBytes() []byte {
	if x != nil {
		return x.SchemaBytes
	}
	return nil
}

func (x *SerializedVerificationSchema) GetDigest() *ContentDigest {
	if x != nil {
		return x.Digest
	}
	return nil
}

// Claim a user makes
type VerificationClaim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The schema this claim instantiates, carried inline.
	Schema *SerializedVerificationSchema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Values keyed by FieldDef.key, decoded per the schema's FieldKind.
	Fields        map[string][]byte `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationClaim) Reset() {
	*x = VerificationClaim{}
	mi := &file_polycentric_v2_verifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationClaim) ProtoMessage() {}

func (x *VerificationClaim) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationClaim.ProtoReflect.Descriptor instead.
func (*VerificationClaim) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationClaim) GetSchema() *SerializedVerificationSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *VerificationClaim) GetFields() map[string][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Targets a claim at one or more identities. Separate from the claim so
// targeting can be set (or changed) after the claim is created.
type VerificationTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The claim event being targeted.
	ClaimEventKey *EventKey `protobuf:"bytes,1,opt,name=claim_event_key,json=claimEventKey,proto3" json:"claim_event_key,omitempty"`
	// Identities the claim is intended for.
	TargetIdentities []string `protobuf:"bytes,2,rep,name=target_identities,json=targetIdentities,proto3" json:"target_identities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerificationTarget) Reset() {
	*x = VerificationTarget{}
	mi := &file_polycentric_v2_verifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationTarget) ProtoMessage() {}

func (x *VerificationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationTarget.ProtoReflect.Descriptor instead.
func (*VerificationTarget) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{4}
}

func (x *VerificationTarget) GetClaimEventKey() *EventKey {
	if x != nil {
		return x.ClaimEventKey
	}
	return nil
}

func (x *VerificationTarget) GetTargetIdentities() []string {
	if x != nil {
		return x.TargetIdentities
	}
	return nil
}

// ── A verification of a claim ──
type VerificationVerify struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The claim event being verified. The event's author is the verifier.
	ClaimEventKey *EventKey `protobuf:"bytes,1,opt,name=claim_event_key,json=claimEventKey,proto3" json:"claim_event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationVerify) Reset() {
	*x = VerificationVerify{}
	mi := &file_polycentric_v2_verifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationVerify) ProtoMessage() {}

func (x *VerificationVerify) ProtoReflect() protoreflect.Message {
	mi := &file_polycentric_v2_verifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationVerify.ProtoReflect.Descriptor instead.
func (*VerificationVerify) Descriptor() ([]byte, []int) {
	return file_polycentric_v2_verifications_proto_rawDescGZIP(), []int{5}
}

func (x *VerificationVerify) GetClaimEventKey() *EventKey {
	if x != nil {
		return x.ClaimEventKey
	}
	return nil
}

var File_polycentric_v2_verifications_proto protoreflect.FileDescriptor

const file_polycentric_v2_verifications_proto_rawDesc = "" +
	"\n" +
	"\"polycentric/v2/verifications.proto\x12\x0epolycentric.v2\x1a\x1bpolycentric/v2/common.proto\x1a\x1epolycentric/v2/event_key.proto\"|\n" +
	"\x12VerificationSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x06fields\x18\x03 \x03(\v2\x18.polycentric.v2.FieldDefR\x06fields\"\xf0\x01\n" +
	"\bFieldDef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x19.polycentric.v2.FieldKindR\x04kind\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\x05regex\x18\x06 \x01(\tH\x00R\x05regex\x88\x01\x01\x12\x1c\n" +
	"\amax_len\x18\a \x01(\rH\x01R\x06maxLen\x88\x01\x01B\b\n" +
	"\x06_regexB\n" +
	"\n" +
	"\b_max_len\"x\n" +
	"\x1cSerializedVerificationSchema\x12!\n" +
	"\fschema_bytes\x18\x01 \x01(\fR\vschemaBytes\x125\n" +
	"\x06digest\x18\x02 \x01(\v2\x1d.polycentric.v2.ContentDigestR\x06digest\"\xdb\x01\n" +
	"\x11VerificationClaim\x12D\n" +
	"\x06schema\x18\x01 \x01(\v2,.polycentric.v2.SerializedVerificationSchemaR\x06schema\x12E\n" +
	"\x06fields\x18\x02 \x03(\v2-.polycentric.v2.VerificationClaim.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x83\x01\n" +
	"\x12VerificationTarget\x12@\n" +
	"\x0fclaim_event_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\rclaimEventKey\x12+\n" +
	"\x11target_identities\x18\x02 \x03(\tR\x10targetIdentities\"V\n" +
	"\x12VerificationVerify\x12@\n" +
	"\x0fclaim_event_key\x18\x01 \x01(\v2\x18.polycentric.v2.EventKeyR\rclaimEventKey*}\n" +
	"\tFieldKind\x12\x1a\n" +
	"\x16FIELD_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FIELD_KIND_STRING\x10\x01\x12\x12\n" +
	"\x0eFIELD_KIND_INT\x10\x02\x12\x13\n" +
	"\x0fFIELD_KIND_BOOL\x10\x03\x12\x14\n" +
	"\x10FIELD_KIND_BYTES\x10\x04B\xd4\x01\n" +
	"\x12com.polycentric.v2B\x12VerificationsProtoP\x01ZQcode.futo.org/harbor/harbor/dev/loadtest/internal/pb/polycentric/v2;polycentricv2\xa2\x02\x03PXX\xaa\x02\x0ePolycentric.V2\xca\x02\x0ePolycentric\\V2\xe2\x02\x1aPolycentric\\V2\\GPBMetadata\xea\x02\x0fPolycentric::V2b\x06proto3"

var (
	file_polycentric_v2_verifications_proto_rawDescOnce sync.Once
	file_polycentric_v2_verifications_proto_rawDescData []byte
)

func file_polycentric_v2_verifications_proto_rawDescGZIP() []byte {
	file_polycentric_v2_verifications_proto_rawDescOnce.Do(func() {
		file_polycentric_v2_verifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polycentric_v2_verifications_proto_rawDesc), len(file_polycentric_v2_verifications_proto_rawDesc)))
	})
	return file_polycentric_v2_verifications_proto_rawDescData
}

var file_polycentric_v2_verifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polycentric_v2_verifications_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_polycentric_v2_verifications_proto_goTypes = []any{
	(FieldKind)(0),                       // 0: polycentric.v2.FieldKind
	(*VerificationSchema)(nil),           // 1: polycentric.v2.VerificationSchema
	(*FieldDef)(nil),                     // 2: polycentric.v2.FieldDef
	(*SerializedVerificationSchema)(nil), // 3: polycentric.v2.SerializedVerificationSchema
	(*VerificationClaim)(nil),            // 4: polycentric.v2.VerificationClaim
	(*VerificationTarget)(nil),           // 5: polycentric.v2.VerificationTarget
	(*VerificationVerify)(nil),           // 6: polycentric.v2.VerificationVerify
	nil,                                  // 7: polycentric.v2.VerificationClaim.FieldsEntry
	(*ContentDigest)(nil),                // 8: polycentric.v2.ContentDigest
	(*EventKey)(nil),                     // 9: polycentric.v2.EventKey
}
var file_polycentric_v2_verifications_proto_depIdxs = []int32{
	2, // 0: polycentric.v2.VerificationSchema.fields:type_name -> polycentric.v2.FieldDef
	0, // 1: polycentric.v2.FieldDef.kind:type_name -> polycentric.v2.FieldKind
	8, // 2: polycentric.v2.SerializedVerificationSchema.digest:type_name -> polycentric.v2.ContentDigest
	3, // 3: polycentric.v2.VerificationClaim.schema:type_name -> polycentric.v2.SerializedVerificationSchema
	7, // 4: polycentric.v2.VerificationClaim.fields:type_name -> polycentric.v2.VerificationClaim.FieldsEntry
	9, // 5: polycentric.v2.VerificationTarget.claim_event_key:type_name -> polycentric.v2.EventKey
	9, // 6: polycentric.v2.VerificationVerify.claim_event_key:type_name -> polycentric.v2.EventKey
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_polycentric_v2_verifications_proto_init() }
func file_polycentric_v2_verifications_proto_init() {
	if File_polycentric_v2_verifications_proto != nil {
		return
	}
	file_polycentric_v2_common_proto_init()
	file_polycentric_v2_event_key_proto_init()
	file_polycentric_v2_verifications_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polycentric_v2_verifications_proto_rawDesc), len(file_polycentric_v2_verifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polycentric_v2_verifications_proto_goTypes,
		DependencyIndexes: file_polycentric_v2_verifications_proto_depIdxs,
		EnumInfos:         file_polycentric_v2_verifications_proto_enumTypes,
		MessageInfos:      file_polycentric_v2_verifications_proto_msgTypes,
	}.Build()
	File_polycentric_v2_verifications_proto = out.File
	file_polycentric_v2_verifications_proto_goTypes = nil
	file_polycentric_v2_verifications_proto_depIdxs = nil
}
