import type { ApiModel } from './types';

const COMPONENTS = '@site/src/components/grpc';

/**
 * The reference as an MDX partial: a heading per service and method (so the
 * page's table of contents lists them) with the components that render each.
 */
export function renderReferenceMdx(model: ApiModel): string {
  const lines: string[] = [
    '{/* Generated by plugins/grpc-api from the proto files. Do not edit. */}',
    '',
    `import { ApiProvider, FileSchemas, Method, ServiceIntro, Toolbar } from '${COMPONENTS}';`,
    '',
    '<ApiProvider>',
    '',
    '<Toolbar />',
    '',
  ];
  for (const service of model.services) {
    lines.push(
      `## ${service.name} {#${service.name}}`,
      '',
      `<ServiceIntro name="${service.name}" />`,
      '',
    );
    for (const method of service.methods) {
      lines.push(
        `### ${method.name} {#${service.name}.${method.name}}`,
        '',
        `<Method service="${service.name}" name="${method.name}" />`,
        '',
      );
    }
  }
  lines.push(
    '## Schemas {#schemas}',
    '',
    `Every message and enum of the \`${model.package}\` package, by file. Type names in the field lists above link here.`,
    '',
  );
  for (const file of model.files) {
    if (file.messages.length === 0 && file.enums.length === 0) continue;
    const base = file.name.slice(file.name.lastIndexOf('/') + 1);
    lines.push(
      `### ${base} {#file-${base}}`,
      '',
      `<FileSchemas name="${file.name}" />`,
      '',
    );
  }
  lines.push('</ApiProvider>', '');
  return lines.join('\n');
}
